// 🇩🇪 Deutsch – anspruchsvolle Grammatik, Expertenwortschatz und stilsicheres Schreiben.
// Kein Anfängerkurs: Es geht um das Deutsch in Berichten, Briefen, Artikeln und Fachtexten.
import type { KursDef } from '../../typen'

export const DEUTSCH: KursDef = {
  id: 'deutsch',
  titel: 'Deutsch',
  emoji: '🇩🇪',
  claim: 'Meistere anspruchsvolles Deutsch.',
  domain: 'deutsch',
  wissen: 'Deutsch-Wissen',
  sprache: 'de-DE',
  thema: 'kurs-deutsch',
  module: [
    { id: 'de.m1', titel: 'Fundamente der Grammatik', emoji: '🧱', text: 'Kasus, Deklination und Präpositionen, wie sie in gutem Deutsch stehen' },
    { id: 'de.m2', titel: 'Komplexe Sätze', emoji: '🧩', text: 'Konnektoren, Nebensätze, Relativsätze und die Ordnung im Mittelfeld' },
    { id: 'de.m3', titel: 'Verbformen und Modus', emoji: '🎭', text: 'Passiv, Konjunktiv II, Konjunktiv I und indirekte Rede' },
    { id: 'de.m4', titel: 'Satzbau und Syntax', emoji: '🏗️', text: 'Partizipialattribute sowie Nominal- und Verbalstil' },
    { id: 'de.m5', titel: 'Präzision und Stil', emoji: '✍️', text: 'Zeichensetzung, Register, Stil und Wörter, die man leicht verwechselt' },
    { id: 'de.m6', titel: 'Expertenwortschatz', emoji: '💎', text: 'Verben, Adjektive und Nomen für genaues Ausdrücken' },
    { id: 'de.m7', titel: 'Akademisch und beruflich', emoji: '🎓', text: 'Kollokationen, Redewendungen, Korrespondenz und Wissenschaftssprache' },
    { id: 'de.m8', titel: 'Meisterschaft', emoji: '🏆', text: 'Die feinen Fallstricke – für alle, die es ganz genau wissen wollen' },
  ],
  ziele: [
    { id: 'de.genitiv', titel: 'Präpositionen mit Genitiv', modul: 'de.m1' },
    { id: 'de.rektion', titel: 'Verben und ihr Kasus', modul: 'de.m1' },
    { id: 'de.adjektiv', titel: 'Adjektivdeklination', modul: 'de.m1' },
    { id: 'de.ndekl', titel: 'n-Deklination', modul: 'de.m1' },
    { id: 'de.konnektoren', titel: 'Konnektoren', modul: 'de.m2' },
    { id: 'de.nebensatz', titel: 'Nebensätze und Verbstellung', modul: 'de.m2' },
    { id: 'de.relativ', titel: 'Relativsätze', modul: 'de.m2' },
    { id: 'de.wortstellung', titel: 'Wortstellung', modul: 'de.m2' },
    { id: 'de.passiv', titel: 'Passiv und Passiversatz', modul: 'de.m3' },
    { id: 'de.konj2', titel: 'Konjunktiv II', modul: 'de.m3' },
    { id: 'de.konj1', titel: 'Konjunktiv I und indirekte Rede', modul: 'de.m3' },
    { id: 'de.partizip', titel: 'Partizipialattribute', modul: 'de.m4' },
    { id: 'de.nominal', titel: 'Nominal- und Verbalstil', modul: 'de.m4' },
    { id: 'de.komma', titel: 'Kommasetzung', modul: 'de.m5' },
    { id: 'de.register', titel: 'Register', modul: 'de.m5' },
    { id: 'de.stil', titel: 'Stil und Präzision', modul: 'de.m5' },
    { id: 'de.wortwahl', titel: 'Verwechslungsgefahr', modul: 'de.m5' },
    { id: 'de.verben', titel: 'Anspruchsvolle Verben', modul: 'de.m6' },
    { id: 'de.adjektive', titel: 'Anspruchsvolle Adjektive', modul: 'de.m6' },
    { id: 'de.nomen', titel: 'Anspruchsvolle Nomen', modul: 'de.m6' },
    { id: 'de.kollokation', titel: 'Kollokationen', modul: 'de.m7' },
    { id: 'de.idiom', titel: 'Redewendungen', modul: 'de.m7' },
    { id: 'de.beruf', titel: 'Berufliche Korrespondenz', modul: 'de.m7' },
    { id: 'de.wissenschaft', titel: 'Wissenschaftssprache', modul: 'de.m7' },
    { id: 'de.meister', titel: 'Feinheiten für Meister', modul: 'de.m8' },
  ],
  spiele: [
    {
      id: 'de.detektiv',
      mechanik: 'fehler',
      name: 'Sprachdetektiv',
      emoji: '🕵️',
      kurz: 'Ein Satz, ein Fehler – finde ihn.',
      anleitung: 'Tippe auf das Wort, das nicht stimmt. Dann wähle die richtige Form.',
      tempo: 'genau',
      runden: 3,
      bitte: {
        wer: [
          { name: 'Lukas', emoji: '🧑‍🎓', rolle: 'Student' },
          { name: 'Frau Berger', emoji: '👩‍🏫', rolle: 'Lehrerin' },
        ],
        saetze: [
          'Ich verstehe diesen Satz nicht – irgendwas stimmt da nicht.',
          'In meiner Hausarbeit steckt ein Fehler, den ich nicht finde.',
        ],
      },
    },
    {
      id: 'de.architekt',
      mechanik: 'bau',
      name: 'Satzarchitekt',
      emoji: '🏗️',
      kurz: 'Aus Bausteinen wird ein Satz.',
      anleitung: 'Tippe die Bausteine in der richtigen Reihenfolge an. Tippst du einen gesetzten Baustein an, kommt er zurück.',
      tempo: 'denken',
      runden: 3,
    },
    {
      id: 'de.kontext',
      mechanik: 'wahl',
      name: 'Wort im Kontext',
      emoji: '🎯',
      kurz: 'Welches Wort trifft es am genauesten?',
      anleitung: 'Mehrere Wörter klingen passend – nur eines trifft genau. Achte auf Bedeutung, Zusammenhang und Register.',
      tempo: 'kontext',
      runden: 4,
      bitte: {
        wer: [{ name: 'Herr Albers', emoji: '👨‍💼', rolle: 'Redakteur' }],
        saetze: ['Mir fehlt für meinen Artikel das richtige Wort.'],
      },
    },
    {
      id: 'de.stil',
      mechanik: 'wahl',
      name: 'Stil-Upgrade',
      emoji: '✨',
      kurz: 'Aus holprig wird souverän.',
      anleitung: 'Wähle die Fassung, die im verlangten Register am besten klingt – präzise, knapp und korrekt.',
      tempo: 'kontext',
      runden: 3,
      bitte: {
        wer: [{ name: 'Sophie', emoji: '👩‍💼', rolle: 'Projektleiterin' }],
        saetze: ['Meine E-Mail an den Vorstand klingt noch zu locker. Hilfst du mir?'],
      },
    },
    {
      id: 'de.duell',
      mechanik: 'duell',
      name: 'Grammatik-Duell',
      emoji: '⚔️',
      kurz: 'Zwei Sätze – nur einer ist richtig.',
      anleitung: 'Tippe auf den korrekten Satz. Die Unterschiede werden mit jeder Stufe feiner.',
      tempo: 'schnell',
      runden: 5,
    },
    {
      id: 'de.umformung',
      mechanik: 'wahl',
      name: 'Umformung',
      emoji: '🔁',
      kurz: 'Aktiv, Passiv, Konjunktiv – forme um.',
      anleitung: 'Forme den Satz wie verlangt um. Nur eine Fassung ist korrekt und sagt dasselbe.',
      tempo: 'denken',
      runden: 3,
    },
    {
      id: 'de.lektorat',
      mechanik: 'fehler',
      name: 'Lektorat',
      emoji: '📝',
      kurz: 'Ein echter Text, mehrere Fehler.',
      anleitung: 'Du prüfst einen Text vor dem Versand. Tippe jede fehlerhafte Stelle an und verbessere sie. Fertig? Dann gib ihn frei.',
      tempo: 'genau',
      runden: 1,
      lang: true,
      ab: 2,
      skin: 'mail',
    },
    {
      id: 'de.wortschatz',
      mechanik: 'paare',
      name: 'Expertenwortschatz',
      emoji: '💎',
      kurz: 'Wort und Bedeutung finden zueinander.',
      anleitung: 'Verbinde jedes Wort mit seiner Bedeutung: erst links antippen, dann rechts.',
      tempo: 'schnell',
      runden: 5,
      spalten: ['Wort', 'Bedeutung'],
    },
    {
      id: 'de.kasus',
      mechanik: 'sortieren',
      name: 'Kasus-Sortierer',
      emoji: '🧲',
      kurz: 'Akkusativ, Dativ oder Genitiv?',
      anleitung: 'Welchen Fall verlangt das Wort? Ordne jede Karte zu – per Knopf oder durch Wischen.',
      tempo: 'schnell',
      runden: 6,
      faecher: [
        { name: 'Akkusativ', emoji: '🎯' },
        { name: 'Dativ', emoji: '🎁' },
        { name: 'Genitiv', emoji: '🔑' },
      ],
    },
    {
      id: 'de.register',
      mechanik: 'sortieren',
      name: 'Register-Sortierer',
      emoji: '🎚️',
      kurz: 'Förmlich, neutral oder salopp?',
      anleitung: 'Ordne jede Formulierung ihrem Register zu.',
      tempo: 'schnell',
      runden: 6,
      faecher: [
        { name: 'Förmlich', emoji: '🎩' },
        { name: 'Neutral', emoji: '🙂' },
        { name: 'Salopp', emoji: '🧢' },
      ],
    },
  ],
  laden: () => import('./inhalt').then((m) => m.INHALT),
}
