// 🇬🇧 Englisch – von den ersten Sätzen bis zum entspannten Small Talk.
// Kein Grammatikkurs: Hier zählt, was man wirklich sagt – und wie es natürlich klingt.
import type { KursDef } from '../../typen'

export const ENGLISCH: KursDef = {
  id: 'englisch',
  titel: 'Englisch',
  emoji: '🇬🇧',
  claim: 'Sprich Englisch, wie es wirklich klingt.',
  domain: 'englisch',
  wissen: 'Englisch-Wissen',
  sprache: 'en-GB',
  thema: 'kurs-englisch',
  module: [
    { id: 'en.m1', titel: 'Sich vorstellen', emoji: '👋', text: 'Begrüßen, Namen nennen, sagen, woher man kommt' },
    { id: 'en.m2', titel: 'Fragen stellen', emoji: '❓', text: 'W-Fragen, kurze Antworten, Zahlen und Uhrzeiten' },
    { id: 'en.m3', titel: 'Alltag', emoji: '☀️', text: 'Tagesablauf, Hobbys und was man gerade macht' },
    { id: 'en.m4', titel: 'Einkaufen', emoji: '🛍️', text: 'Im Laden fragen, Größen, Preise und Bezahlen' },
    { id: 'en.m5', titel: 'Essen und Trinken', emoji: '☕', text: 'Bestellen, Vorlieben nennen, im Restaurant zurechtkommen' },
    { id: 'en.m6', titel: 'Unterwegs', emoji: '✈️', text: 'Flughafen, Bahn, Hotel und nach dem Weg fragen' },
    { id: 'en.m7', titel: 'Small Talk', emoji: '💬', text: 'Wetter, Wochenende, natürlich reagieren und nachfragen' },
    { id: 'en.m8', titel: 'Miteinander', emoji: '🤝', text: 'Höflich bitten, sich entschuldigen, einladen und absagen' },
    { id: 'en.m9', titel: 'Arbeit', emoji: '💼', text: 'Termine, Absprachen und kurze Nachrichten' },
    { id: 'en.m10', titel: 'Gespräche meistern', emoji: '🏆', text: 'Unerwartetes auffangen, typische Fallen und elegant abschließen' },
  ],
  ziele: [
    { id: 'en.greet', titel: 'Begrüßen und verabschieden', modul: 'en.m1' },
    { id: 'en.intro', titel: 'Sich vorstellen', modul: 'en.m1' },
    { id: 'en.origin', titel: 'Herkunft und Wohnort', modul: 'en.m1' },
    { id: 'en.wh', titel: 'W-Fragen', modul: 'en.m2' },
    { id: 'en.yesno', titel: 'Kurze Antworten', modul: 'en.m2' },
    { id: 'en.numbers', titel: 'Zahlen, Uhrzeit, Preise', modul: 'en.m2' },
    { id: 'en.routine', titel: 'Tagesablauf', modul: 'en.m3' },
    { id: 'en.hobbys', titel: 'Hobbys und Freizeit', modul: 'en.m3' },
    { id: 'en.shop', titel: 'Im Laden', modul: 'en.m4' },
    { id: 'en.money', titel: 'Bezahlen', modul: 'en.m4' },
    { id: 'en.order', titel: 'Bestellen', modul: 'en.m5' },
    { id: 'en.food', titel: 'Essen und Vorlieben', modul: 'en.m5' },
    { id: 'en.travel', titel: 'Bahn und Flughafen', modul: 'en.m6' },
    { id: 'en.hotel', titel: 'Im Hotel', modul: 'en.m6' },
    { id: 'en.directions', titel: 'Nach dem Weg fragen', modul: 'en.m6' },
    { id: 'en.smalltalk', titel: 'Small Talk beginnen', modul: 'en.m7' },
    { id: 'en.reactions', titel: 'Natürlich reagieren', modul: 'en.m7' },
    { id: 'en.followup', titel: 'Nachfragen', modul: 'en.m7' },
    { id: 'en.polite', titel: 'Höflich bitten', modul: 'en.m8' },
    { id: 'en.apology', titel: 'Entschuldigen', modul: 'en.m8' },
    { id: 'en.invite', titel: 'Einladen, zusagen, absagen', modul: 'en.m8' },
    { id: 'en.work', titel: 'Arbeit und Termine', modul: 'en.m9' },
    { id: 'en.email', titel: 'Kurze Nachrichten', modul: 'en.m9' },
    { id: 'en.recovery', titel: 'Unerwartetes auffangen', modul: 'en.m10' },
    { id: 'en.falsefriends', titel: 'Typisch deutsche Fallen', modul: 'en.m10' },
    { id: 'en.ending', titel: 'Gespräche beenden', modul: 'en.m10' },
  ],
  spiele: [
    {
      id: 'en.gespraech',
      mechanik: 'dialog',
      name: 'Gespräch',
      emoji: '💬',
      kurz: 'Ein echtes Hin und Her.',
      anleitung: 'Antworte so, wie man es wirklich sagt. Dein Gegenüber reagiert auf jede Antwort.',
      tempo: 'kontext',
      runden: 1,
      lang: true,
      bitte: {
        wer: [
          { name: 'Emily', emoji: '👩‍🦰', rolle: 'Austauschschülerin' },
          { name: 'Tom', emoji: '🧑‍🦱', rolle: 'Tourist' },
        ],
        saetze: [
          'Morgen kommt Besuch aus England – kannst du mit mir ein Gespräch üben?',
          'Ich muss gleich auf Englisch telefonieren. Übst du kurz mit mir?',
        ],
      },
    },
    {
      id: 'en.situation',
      mechanik: 'dialog',
      name: 'Situation',
      emoji: '🎬',
      kurz: 'Café, Hotel, Bahnhof – mit einem Ziel.',
      anleitung: 'Du hast ein Ziel. Bring das Gespräch dorthin – höflich und natürlich.',
      tempo: 'kontext',
      runden: 1,
      lang: true,
      ab: 2,
      bitte: {
        wer: [{ name: 'Nora', emoji: '🧳', rolle: 'Reisende' }],
        saetze: ['Ich fliege morgen nach London und habe Angst vor dem Check-in. Üben wir das?'],
      },
    },
    {
      id: 'en.antwort',
      mechanik: 'wahl',
      name: 'Natürliche Antwort',
      emoji: '🗣️',
      kurz: 'Was sagt man wirklich?',
      anleitung: 'Alle Antworten sind verständlich – aber nur eine klingt wie von einer Muttersprachlerin.',
      tempo: 'kontext',
      runden: 4,
    },
    {
      id: 'en.hoeren',
      mechanik: 'hoeren',
      name: 'Hören',
      emoji: '👂',
      kurz: 'Zuhören und verstehen.',
      anleitung: 'Höre den Satz – auch mehrmals oder langsam – und wähle, was gemeint ist.',
      tempo: 'genau',
      runden: 4,
    },
    {
      id: 'en.retten',
      mechanik: 'wahl',
      name: 'Gespräch retten',
      emoji: '🛟',
      kurz: 'Wenn es unerwartet wird.',
      anleitung: 'Dein Gegenüber sagt etwas Überraschendes. Wie hältst du das Gespräch am Laufen?',
      tempo: 'denken',
      runden: 3,
      ab: 2,
    },
    {
      id: 'en.satzbau',
      mechanik: 'bau',
      name: 'Satzbau',
      emoji: '🧱',
      kurz: 'Aus Bausteinen wird ein Satz.',
      anleitung: 'Tippe die Bausteine in der richtigen Reihenfolge an.',
      tempo: 'denken',
      runden: 3,
    },
    {
      id: 'en.paare',
      mechanik: 'paare',
      name: 'Wortpaare',
      emoji: '🔗',
      kurz: 'Wendung und Bedeutung.',
      anleitung: 'Verbinde jede Wendung mit ihrer Bedeutung: erst links antippen, dann rechts.',
      tempo: 'schnell',
      runden: 5,
      spalten: ['English', 'Deutsch'],
    },
    {
      id: 'en.natuerlich',
      mechanik: 'duell',
      name: 'Klingt natürlich?',
      emoji: '⚖️',
      kurz: 'Zwei Sätze – einer klingt komisch.',
      anleitung: 'Beide Sätze sind grammatisch möglich. Welcher klingt für englische Ohren normal?',
      tempo: 'schnell',
      runden: 5,
    },
  ],
  laden: () => import('./inhalt').then((m) => m.INHALT),
}
