// 🇬🇧 Englisch – natürliche Antworten, Rettungsanker, Natürlichkeits-Duelle, Hören,
// Satzbau und Wortpaare. Alles Alltagssprache: kein Lehrbuch-Englisch, sondern das,
// was in London, Manchester oder Dublin wirklich gesagt wird.
import type { BauItem, DuellItem, HoerItem, PaarItem, Stufe, WahlItem } from '../../typen'
import { bausteine, optionen } from '../werkzeug'

// ---------- Natürliche Antwort ----------

function antwort(
  id: string,
  ziel: string,
  stufe: Stufe,
  sprecher: { name: string; emoji: string; text: string; de: string },
  liste: string[],
  erklaerung: string,
): WahlItem {
  return {
    id,
    spiel: 'en.antwort',
    art: 'wahl',
    ziel,
    stufe,
    aufgabe: 'Was antwortest du?',
    sprache: 'en-GB',
    sprecher,
    optionen: optionen(liste),
    erklaerung,
  }
}

const EMMA = { name: 'Emma', emoji: '👩' }
const TOM = { name: 'Tom', emoji: '🧑' }
const SUE = { name: 'Sue', emoji: '👩‍🦰' }
const BEN = { name: 'Ben', emoji: '🧔' }

export const ANTWORTEN: WahlItem[] = [
  antwort('en.an.01', 'en.greet', 1, { ...EMMA, text: "How's it going?", de: 'Wie läuft’s?' }, [
    'Not bad, thanks. You?',
    '~0.5 I am fine, thank you. And you?::Korrekt, klingt aber nach Lehrbuch. Im Alltag kürzer.',
    'I am going to the office.::„How’s it going?“ heißt „Wie geht’s?“ – nicht „Wohin gehst du?“',
    'Yes, it goes.::Das gibt es im Englischen nicht.',
  ], '„How’s it going?“ beantwortet man kurz und gibt die Frage zurück: „Not bad, thanks. You?“'),
  antwort('en.an.31', 'en.intro', 1, { ...EMMA, text: "Hi, I don't think we've met. I'm Emma.", de: 'Hi, ich glaube, wir kennen uns noch nicht. Ich bin Emma.' }, [
    "Hi Emma, I'm Jonas. Nice to meet you.",
    '~0.5 Hello Emma. My name is Jonas.::Korrekt, klingt aber etwas förmlich.',
    'I know, you are Emma.::Wirkt seltsam – sie stellt sich gerade vor.',
    'Emma is a nice name.::Hier stellt man sich selbst vor.',
  ], 'Vorstellen geht immer gleich: Name nennen und „Nice to meet you“ anhängen.'),
  antwort('en.an.32', 'en.intro', 2, { ...BEN, text: 'And what brings you to Bristol?', de: 'Und was führt dich nach Bristol?' }, [
    "I'm here for work – just for a few months.",
    '~0.5 I am here because of my job.::Verständlich – „I’m here for work“ ist knapper.',
    'The train brings me.::Die Frage meint den Grund, nicht das Verkehrsmittel.',
    'That is a secret.::Wirkt abweisend.',
  ], '„What brings you to …?“ fragt nach dem Grund für den Aufenthalt.'),
  antwort('en.an.02', 'en.apology', 1, { ...TOM, text: "Sorry, I'm running a little late.", de: 'Sorry, ich verspäte mich etwas.' }, [
    "No worries, take your time.",
    '~0.4 It is okay. I wait.::Verständlich, aber holprig: „No worries, take your time.“',
    'I acknowledge your delay.::So spricht niemand – das klingt nach Behörde.',
    'Why are you always late?::Ein Vorwurf, obwohl er sich gerade entschuldigt hat.',
  ], '„No worries“ ist die britische Allzweckantwort auf kleine Entschuldigungen.'),
  antwort('en.an.03', 'en.reactions', 2, { ...SUE, text: "I've just got a new job!", de: 'Ich habe gerade eine neue Stelle bekommen!' }, [
    "Congratulations! That's brilliant news.",
    '~0.5 That is good for you.::Grammatisch richtig, klingt aber kühl.',
    'Okay.::Zu wenig Reaktion – das wirkt desinteressiert.',
    'Why did you leave the old one?::Erst freuen, dann fragen.',
  ], 'Gute Nachrichten werden im Englischen deutlich beklatscht: „Congratulations!“, „That’s brilliant!“'),
  antwort('en.an.04', 'en.reactions', 2, { ...BEN, text: 'My cat died last week.', de: 'Meine Katze ist letzte Woche gestorben.' }, [
    "Oh no, I'm so sorry to hear that.",
    '~0.4 I am sad for you.::Gut gemeint, aber unüblich: „I’m sorry to hear that.“',
    "That's nice.::Klingt so, als hättest du nicht zugehört.",
    'Okay, and?::Sehr kalt.',
  ], '„I’m sorry to hear that“ ist die feste Wendung für schlechte Nachrichten – sie bedeutet Mitgefühl, nicht Schuld.'),
  antwort('en.an.05', 'en.polite', 2, { ...EMMA, text: 'Could you pass me the salt?', de: 'Könntest du mir das Salz reichen?' }, [
    'Here you go.',
    '~0.5 Yes, of course. There it is.::Geht – beim Überreichen sagt man „Here you go“ oder „Here you are“.',
    'Yes, I could.::Witzig gemeint, wirkt aber schnippisch.',
    'Take it yourself.::Unfreundlich.',
  ], 'Wenn du etwas überreichst: „Here you go“ (locker) oder „Here you are“ (etwas förmlicher).'),
  antwort('en.an.06', 'en.smalltalk', 2, { ...TOM, text: "Lovely weather today, isn't it?", de: 'Schönes Wetter heute, oder?' }, [
    "It is, isn't it? Finally!",
    '~0.5 Yes, it is nice.::Richtig, aber das Gespräch stockt.',
    'Yes, the weather is very lovely today in this city.::Zu viel – Small Talk bleibt leicht.',
    "I don't care about weather.::Damit ist das Gespräch beendet.",
  ], 'Der britische Small-Talk-Trick: zustimmen und ein kleines Wort anhängen („Finally!“, „At last!“).'),
  antwort('en.an.07', 'en.invite', 3, { ...SUE, text: 'Do you fancy a coffee after work?', de: 'Hast du nach der Arbeit Lust auf einen Kaffee?' }, [
    "I'd love to, but I can't today. Another time?",
    '~0.5 No, I have no time today.::Verständlich, klingt aber schroff.',
    'Maybe.::Zu vage – das wirkt desinteressiert.',
    'I must work until late, so no.::Zu viel Erklärung, kein Gegenangebot.',
  ], 'Absagen klingen freundlich mit drei Teilen: Interesse – Absage – Alternative.'),
  antwort('en.an.08', 'en.wh', 1, { ...BEN, text: 'What do you do?', de: 'Was machst du beruflich?' }, [
    "I'm a nurse. What about you?",
    '~0.5 I work as a nurse in a hospital.::Richtig – etwas lang für den Einstieg.',
    'I do sport and cooking.::Die Frage zielt auf den Beruf.',
    'I am doing nothing.::Klingt, als wolltest du nicht reden.',
  ], '„What do you do?“ fragt nach dem Beruf. Die Antwort ist kurz – und die Rückfrage gehört dazu.'),
  antwort('en.an.09', 'en.numbers', 1, { name: 'Kasse', emoji: '🧾', text: "That'll be four pounds fifty, please.", de: 'Das macht 4,50 Pfund, bitte.' }, [
    'Here you are. Can I pay by card?',
    '~0.5 Okay. I take the card.::Verständlich – „Can I pay by card?“ ist üblich.',
    "That's too much.::Über den Preis zu diskutieren ist im Laden unüblich.",
    'Four pounds fifty what?::Gemeint sind Pfund – das wurde gesagt.',
  ], '„That’ll be …“ heißt: So viel kostet es. Antwort: zahlen oder nach der Zahlart fragen.'),
  antwort('en.an.10', 'en.followup', 3, { ...EMMA, text: "I spent the weekend in the Lake District.", de: 'Ich war am Wochenende im Lake District.' }, [
    'Oh nice! Did you do much walking?',
    '~0.5 That sounds good.::Freundlich, aber ohne Nachfrage bleibt es stehen.',
    'I have never been there.::Über dich statt über sie – erst nachfragen.',
    'Is that in England?::Kann man fragen, bremst hier aber.',
  ], 'Eine Nachfrage zum Erzählten hält das Gespräch in Gang – das ist wichtiger als perfekte Grammatik.'),
  antwort('en.an.11', 'en.ending', 3, { ...TOM, text: 'Anyway, I should get going.', de: 'Naja, ich sollte los.' }, [
    'Of course – it was lovely to see you.',
    '~0.5 Okay, bye.::Passt, klingt aber abrupt.',
    'Why? We just started talking.::Das setzt ihn unter Druck.',
    'Wait, one more thing …::Nur wenn es wirklich wichtig ist.',
  ], '„I should get going“ ist das höfliche Signal zum Abschied. Man nimmt es an und sagt etwas Nettes.'),
  antwort('en.an.12', 'en.order', 1, { name: 'Kellnerin', emoji: '👩‍🍳', text: 'Are you ready to order?', de: 'Möchten Sie bestellen?' }, [
    "Yes – could I have the soup, please?",
    '~0.5 Yes. I take the soup.::Verständlich – „Could I have …?“ ist die übliche Form.',
    'I want soup now.::Klingt fordernd.',
    'Give me two minutes more … actually no.::Unentschlossen – dann lieber klar um Zeit bitten.',
  ], 'Bestellen geht fast immer mit „Could I have …, please?“'),
  antwort('en.an.13', 'en.shop', 2, { name: 'Verkäufer', emoji: '🧑‍💼', text: 'Can I help you at all?', de: 'Kann ich Ihnen helfen?' }, [
    "I'm just browsing, thanks.",
    '~0.5 No, thank you, I only look.::Fast – die feste Wendung ist „I’m just browsing“.',
    'No.::Sehr knapp.',
    'Yes, bring me shoes.::Klingt wie ein Befehl.',
  ], '„I’m just browsing, thanks“ – so bleibt man höflich, ohne Hilfe zu brauchen.'),
  antwort('en.an.14', 'en.hotel', 2, { name: 'Rezeption', emoji: '🛎️', text: 'How was your stay?', de: 'Wie war Ihr Aufenthalt?' }, [
    'Really good, thank you – especially the breakfast.',
    '~0.5 It was good.::Richtig, aber ein Detail macht es persönlich.',
    'It was okay, the room was small and loud.::Kritik geht – aber dann lieber konstruktiv und freundlich.',
    'Why do you ask?::Wirkt misstrauisch.',
  ], 'Auf „How was …?“ antwortet man mit einem Wort plus Detail: „Really good – especially the breakfast.“'),
  antwort('en.an.15', 'en.directions', 2, { ...BEN, text: 'Excuse me, do you know where the museum is?', de: 'Entschuldigung, wissen Sie, wo das Museum ist?' }, [
    "Sorry, I'm not from here either.",
    '~0.5 I don’t know it.::Verständlich – die übliche Wendung ist „Sorry, I’m not from around here.“',
    'No.::Wirkt unfreundlich.',
    'Museum? What museum?::Klingt genervt.',
  ], 'Wenn du nicht helfen kannst: „Sorry, I’m not from around here.“ Das ist freundlich und klar.'),
  antwort('en.an.16', 'en.work', 3, { ...SUE, text: 'Could you send me the report by Friday?', de: 'Kannst du mir den Bericht bis Freitag schicken?' }, [
    "Sure, I'll send it over on Thursday.",
    '~0.5 Yes, that is possible.::Geht – eine konkrete Zusage ist besser.',
    "I'll try.::Klingt unverbindlich.",
    'Friday is impossible for me.::Ohne Alternative bleibt das Problem stehen.',
  ], 'Im Beruf zählt eine klare Zusage mit Termin: „Sure, I’ll send it over on Thursday.“'),
  antwort('en.an.17', 'en.email', 3, { name: 'Nachricht', emoji: '💬', text: 'Thanks for your help yesterday!', de: 'Danke für deine Hilfe gestern!' }, [
    'No problem at all – glad it worked out.',
    '~0.5 You are welcome.::Passt – ein Zusatz wirkt wärmer.',
    'It was my job.::Klingt abweisend.',
    'You owe me one.::Als Scherz möglich, sonst unhöflich.',
  ], 'Auf Dank antwortet man locker: „No problem at all“, „Any time“, „Glad I could help“.'),
  antwort('en.an.18', 'en.recovery', 4, { ...EMMA, text: "Sorry, I didn't catch that.", de: 'Entschuldigung, das habe ich nicht verstanden.' }, [
    'Sorry – I asked if you knew where the station is.',
    '~0.5 I said, where is the station.::Verständlich – mit „I asked if …“ klingt es runder.',
    'Never mind.::Damit gibst du zu früh auf.',
    'You must listen better.::Ein Vorwurf hilft nicht weiter.',
  ], 'Nicht verstanden? Einfach den Satz ruhig wiederholen – „Sorry, I asked if …“'),
  antwort('en.an.19', 'en.falsefriends', 4, { name: 'Kassiererin', emoji: '🧾', text: 'Would you like a receipt?', de: 'Möchten Sie den Kassenbon?' }, [
    'Yes, please.',
    '~0.3 Yes, I become one.::„become“ heißt „werden“, nicht „bekommen“ – ein Klassiker.',
    'No, I get it myself.::Klingt, als wolltest du ihn selbst drucken.',
    'What is a receipt?::Hier wäre ein einfaches Ja besser.',
  ], 'Der Klassiker unter den falschen Freunden: „become“ heißt werden. Bekommen ist „get“ oder „receive“.'),
  antwort('en.an.20', 'en.yesno', 1, { ...TOM, text: 'Have you been to London before?', de: 'Warst du schon mal in London?' }, [
    "Yes, I have – twice, actually.",
    '~0.5 Yes.::Richtig, aber das Gespräch endet sofort.',
    'Yes, I was been there.::Grammatisch falsch.',
    'No, never, I don’t like big cities.::Die Begründung klingt schroff.',
  ], 'Kurzantworten wiederholen das Hilfsverb: „Have you …?“ – „Yes, I have.“'),
  antwort('en.an.21', 'en.routine', 2, { ...BEN, text: 'What time do you usually start work?', de: 'Wann fängst du normalerweise an zu arbeiten?' }, [
    'Around half eight, most days.',
    '~0.5 At 8:30 o’clock.::„o’clock“ nur bei vollen Stunden: eight o’clock.',
    'I start with work at half nine.::„start work“ ohne „with“ – und „half nine“ heißt 8:30.',
    'It depends.::Ohne Zusatz bleibt es leer.',
  ], 'Achtung: „half eight“ heißt im britischen Englisch 8:30 – nicht 7:30 wie im Deutschen.'),
  antwort('en.an.22', 'en.hobbys', 2, { ...SUE, text: 'What do you do in your free time?', de: 'Was machst du in deiner Freizeit?' }, [
    "I play five-a-side football on Tuesdays. How about you?",
    '~0.5 I like football and reading books.::Passt – mit einem Detail wird es lebendiger.',
    'Nothing special.::Beendet das Gespräch.',
    'I am making sport.::„I do sport“ oder konkret: „I play football“.',
  ], 'Konkrete Details („on Tuesdays“) geben dem Gegenüber etwas zum Nachfragen.'),
  antwort('en.an.23', 'en.food', 2, { name: 'Gastgeber', emoji: '🧑‍🍳', text: 'Is there anything you don’t eat?', de: 'Gibt es etwas, das du nicht isst?' }, [
    "I don't eat pork, but everything else is fine.",
    '~0.5 I am vegetarian since two years.::Fast: „I’ve been vegetarian for two years.“',
    'No, I eat all.::Fast – „I eat everything“.',
    'I hate fish, it is disgusting.::Zu heftig für eine Einladung.',
  ], 'Vorlieben nennt man sachlich: „I don’t eat …, but everything else is fine.“'),
  antwort('en.an.24', 'en.travel', 3, { name: 'Schaffner', emoji: '🧑‍✈️', text: 'Tickets, please.', de: 'Die Fahrkarten, bitte.' }, [
    "Here you are. Is this the right train for York?",
    '~0.5 Here. Yes, York?::Verständlich, aber zerhackt.',
    'I have no ticket.::Das wird teuer – und war nicht gemeint.',
    'Wait a moment, I search.::„I’m just looking for it“ klingt natürlicher.',
  ], 'Die Kontrolle ist eine gute Gelegenheit, kurz nachzufragen: „Is this the right train for …?“'),
  antwort('en.an.25', 'en.money', 2, { name: 'Kellner', emoji: '🧑‍🍳', text: 'Would you like to pay together or separately?', de: 'Möchten Sie zusammen oder getrennt zahlen?' }, [
    'Separately, please.',
    '~0.5 Each for himself.::Verständlich, aber unüblich: „Separately, please.“',
    'Together, but I pay only my food.::Widersprüchlich.',
    'I pay nothing.::Das gibt Ärger.',
  ], 'Im Restaurant reicht ein Wort: „Together“ oder „Separately, please.“'),
  antwort('en.an.26', 'en.origin', 1, { ...EMMA, text: 'Whereabouts in Germany are you from?', de: 'Wo genau in Deutschland kommst du her?' }, [
    "A small town near Frankfurt – you probably don't know it.",
    '~0.5 From Germany.::Die Frage war genauer gemeint.',
    'Germany is in Europe.::Das war nicht gefragt.',
    'Why do you want to know?::Wirkt misstrauisch bei einer normalen Frage.',
  ], '„Whereabouts …?“ heißt „Wo genau …?“ – die Antwort darf ruhig ein kleiner Ort sein.'),
  antwort('en.an.27', 'en.polite', 3, { name: 'Nachbar', emoji: '🧓', text: 'Would you mind moving your car?', de: 'Würden Sie bitte Ihr Auto wegfahren?' }, [
    "Not at all – I'll move it right now.",
    '~0.3 Yes, of course.::Achtung: Bei „Would you mind …?“ heißt „Yes“ eigentlich „Doch, stört mich“.',
    'Yes, I mind.::Das heißt: Nein, ich will nicht.',
    'It is allowed to park here.::Streit statt Lösung.',
  ], 'Fiese Falle: Auf „Would you mind …?“ antwortet man „Not at all“ oder „Of course not“, wenn man einverstanden ist.'),
  antwort('en.an.28', 'en.smalltalk', 3, { ...TOM, text: 'Did you see the match last night?', de: 'Hast du gestern das Spiel gesehen?' }, [
    "I missed it, actually. Was it any good?",
    '~0.5 No, I didn’t see it.::Richtig – eine Rückfrage hält das Thema am Leben.',
    'I don’t like football.::Beendet das Thema abrupt.',
    'Which match?::Kann man fragen, wirkt aber wenig interessiert.',
  ], '„I missed it, actually“ plus Rückfrage – so bleibt man im Gespräch, auch ohne das Thema zu kennen.'),
  antwort('en.an.29', 'en.invite', 3, { ...SUE, text: "We're having people round on Saturday. You're welcome to come.", de: 'Wir haben Samstag Leute da. Du kannst gern kommen.' }, [
    "That's really kind – I'd love to. What time?",
    '~0.5 Yes, I come.::Verständlich – „I’d love to“ zeigt Freude.',
    'Maybe, I will see.::Wirkt unverbindlich.',
    'Who else is coming? I don’t like crowds.::Klingt abweisend.',
  ], 'Einladungen nimmt man warm an: „That’s really kind – I’d love to.“'),
  antwort('en.an.30', 'en.ending', 4, { ...BEN, text: "Right, I'd better let you go.", de: 'Gut, ich will dich nicht länger aufhalten.' }, [
    'Same here – have a good evening!',
    '~0.5 Okay. Bye.::Passt, ein warmer Schluss wirkt besser.',
    'You can stay longer if you want.::Er hat den Abschied schon eingeleitet.',
    'Finally.::Sehr unhöflich.',
  ], '„I’d better let you go“ ist eine höfliche Formel zum Schluss – kein Vorwurf.'),
  antwort('en.an.33', 'en.wh', 1, { ...TOM, text: 'What do you do, then?', de: 'Und was machst du so?' }, [
    "I work in a hospital – I'm a nurse.",
    '~0.5 I am working as a nurse in a hospital.::Verständlich, aber für den Beruf nimmt man das einfache Present.',
    'I do sport and I read.::„What do you do?“ fragt nach dem Beruf, nicht nach Hobbys.',
    'I do nothing at the moment, sorry.::Klingt schroff – „I’m between jobs at the moment“ wäre freundlicher.',
  ], '„What do you do?“ heißt: Was machst du beruflich? Die Antwort steht im einfachen Present.'),
  antwort('en.an.34', 'en.routine', 1, { ...SUE, text: 'Have you had a busy day?', de: 'War dein Tag anstrengend?' }, [
    'Yes, pretty hectic – but it’s done now.',
    '~0.5 Yes, I had much to do.::Verständlich; „a lot to do“ klingt natürlicher als „much to do“.',
    'My day was busy since eight hours.::Dauer mit „for“ – und besser: „I’ve been busy since eight.“',
    'Yes, I am busy person.::Hier fehlt „a“ – und gefragt war der Tag, nicht dein Charakter.',
  ], 'Auf „Have you had a busy day?“ antwortet man kurz und hängt eine kleine Wertung an.'),
  antwort('en.an.35', 'en.hobbys', 2, { ...BEN, text: 'Do you do anything to switch off after work?', de: 'Machst du nach der Arbeit etwas zum Abschalten?' }, [
    'I go for a run most evenings – it really clears my head.',
    '~0.5 Yes, I do sport.::Richtig, aber konkret ist interessanter: „I go running.“',
    'I switch off the light.::„switch off“ heißt hier: abschalten, entspannen.',
    'No, I work always.::Wortstellung: „I always work.“ – und das Gespräch stockt.',
  ], '„To switch off“ heißt im Alltag: den Kopf freibekommen.'),
  antwort('en.an.36', 'en.shop', 1, { ...EMMA, text: 'Are you alright there? Can I help at all?', de: 'Alles klar bei Ihnen? Kann ich helfen?' }, [
    "I'm just browsing, thanks.",
    '~0.5 No, thank you, I only look.::Verständlich – die übliche Wendung ist „I’m just browsing“.',
    'Yes, I am alright, thank you for asking me.::Im Laden ist die Frage nur eine Höflichkeitsformel.',
    'No.::Zu knapp – ein „thanks“ gehört dazu.',
  ], 'Im Laden heißt „Are you alright there?“ schlicht: Kann ich helfen? Standardantwort: „I’m just browsing, thanks.“'),
  antwort('en.an.37', 'en.money', 2, { ...TOM, text: "That's twelve pounds forty. Cash or card?", de: 'Das macht zwölf Pfund vierzig. Bar oder Karte?' }, [
    'Card, please. Can I tap?',
    '~0.5 With card, please.::Fast – „by card“ oder einfach „card, please“.',
    'I pay with money.::Bargeld heißt „cash“.',
    'Twelve pounds is too much for that.::An der Kasse wirkt das unhöflich.',
  ], 'Kontaktlos zahlen heißt „to tap“ – „Can I tap?“ hört man in Großbritannien ständig.'),
  antwort('en.an.38', 'en.order', 1, { ...SUE, text: 'Are you ready to order?', de: 'Möchten Sie bestellen?' }, [
    'Yes – could I have the soup to start, please?',
    '~0.5 Yes, I take the soup.::Verständlich, aber im Lokal sagt man „I’ll have …“ oder „Could I have …“.',
    'Yes, I am ready.::Richtig, aber die Bestellung fehlt – die Kellnerin wartet.',
    'I become the soup.::„become“ heißt „werden“ – der Klassiker unter den Fehlern.',
  ], 'Im Restaurant bestellt man mit „I’ll have …“ oder höflicher „Could I have …, please?“'),
  antwort('en.an.39', 'en.food', 2, { ...BEN, text: 'Would you like anything else? Dessert, maybe?', de: 'Darf es noch etwas sein? Vielleicht ein Dessert?' }, [
    "No, thanks – I'm absolutely stuffed.",
    '~0.5 No thank you, I am full.::Passt; „stuffed“ klingt entspannter und ist sehr üblich.',
    'No, I have enough.::Klingt leicht genervt – als wäre etwas zu viel gewesen.',
    'I am fed up, thank you.::„fed up“ heißt genervt, nicht satt.',
  ], '„I’m full“ oder lockerer „I’m stuffed“ heißt: Ich bin satt.'),
  antwort('en.an.40', 'en.hotel', 2, { ...EMMA, text: 'Did you have a good journey?', de: 'Hatten Sie eine gute Anreise?' }, [
    'Yes, thanks – it was easier than I expected.',
    '~0.5 Yes, the journey was good.::Richtig, nur etwas hölzern.',
    'The journey was 400 kilometres long.::Gefragt war, wie es war, nicht wie weit.',
    'It was a catastrophe with the train always.::Wortstellung und Ton – „The train was a nightmare, actually.“',
  ], 'Small Talk beim Einchecken: kurz antworten und eine kleine Wertung anhängen.'),
  antwort('en.an.41', 'en.work', 2, { ...TOM, text: 'Could we move the call to half four?', de: 'Können wir das Telefonat auf halb fünf verschieben?' }, [
    'Half four works for me – I’ll update the invite.',
    '~0.5 Yes, we can move the call.::Passt, aber bestätige lieber die neue Uhrzeit.',
    'Half four is half past three?::„half four“ heißt im Britischen 16:30.',
    'No, I have no time never.::Doppelte Verneinung – und sehr unfreundlich.',
  ], 'Britisch „half four“ = 16:30. Bei Terminen bestätigt man die Zeit immer noch einmal.'),
  antwort('en.an.42', 'en.email', 3, { ...SUE, text: 'Sorry to chase, but did you get a chance to look at my email?', de: 'Sorry fürs Nachhaken – konntest du dir meine Mail schon ansehen?' }, [
    "Sorry, it's been a hectic week – I'll get back to you today.",
    '~0.5 Not yet, I had much work.::Verständlich, aber ohne Zusage bleibt die Sache offen.',
    'Why do you chase me?::„to chase“ ist im Büro ganz normal: freundlich nachhaken.',
    'I have seen the email but not read it.::Ehrlich, aber ohne Lösung – nenne einen Zeitpunkt.',
  ], '„Sorry to chase“ ist höfliches Nachhaken. Gute Antwort: kurz erklären und einen Zeitpunkt nennen.'),
]

// ---------- Gespräch retten ----------

function retten(
  id: string,
  ziel: string,
  stufe: Stufe,
  sprecher: { name: string; emoji: string; text: string; de: string },
  liste: string[],
  erklaerung: string,
): WahlItem {
  return {
    id,
    spiel: 'en.retten',
    art: 'wahl',
    ziel,
    stufe,
    aufgabe: 'Wie rettest du das Gespräch?',
    sprache: 'en-GB',
    sprecher,
    optionen: optionen(liste),
    erklaerung,
  }
}

export const RETTEN: WahlItem[] = [
  retten('en.re.01', 'en.recovery', 2, { ...EMMA, text: "Oh, you're from Germany? I've always wanted to visit!", de: 'Oh, du bist aus Deutschland? Da wollte ich immer schon hin!' }, [
    'You should! Which part would you like to see?',
    '~0.5 Yes, Germany is nice.::Freundlich, aber das Gespräch stockt.',
    'Germany is a country in Europe.::Das weiß sie.',
    'It’s not that special.::Bremst die Begeisterung aus.',
  ], 'Begeisterung aufgreifen und zurückfragen – daraus wird ein Gespräch.'),
  retten('en.re.02', 'en.recovery', 2, { ...TOM, text: 'Sorry, my English is terrible.', de: 'Sorry, mein Englisch ist furchtbar.' }, [
    "Don't worry, mine isn't perfect either. We'll manage.",
    '~0.5 It is okay.::Kurz und freundlich – mit einem Zusatz nimmt man mehr Druck.',
    'Yes, I noticed.::Autsch.',
    'Should we speak German?::Gut gemeint, nimmt ihm aber die Übung.',
  ], 'Unsicherheit nimmt man am besten die Spitze, indem man sich selbst dazustellt.'),
  retten('en.re.03', 'en.recovery', 3, { ...SUE, text: "Actually, I've just been made redundant.", de: 'Ehrlich gesagt wurde mir gerade gekündigt.' }, [
    "I'm really sorry to hear that. How are you holding up?",
    '~0.4 That is bad luck.::Etwas leicht für die Situation.',
    'Why did they fire you?::Die Frage ist zu direkt.',
    'My job is very secure.::Über dich statt über sie.',
  ], 'Bei schlechten Nachrichten: Mitgefühl zeigen und nach dem Befinden fragen – nicht nach Details.'),
  retten('en.re.04', 'en.recovery', 3, { ...BEN, text: '…', de: '(Schweigen)' }, [
    "So, how's your week been?",
    '~0.5 It is very quiet now.::Ehrlich, aber es hilft nur mit einer Frage weiter.',
    'Why are you so quiet?::Setzt unter Druck.',
    'Okay, bye then.::Zu schnell aufgegeben.',
  ], 'Gegen Stille hilft eine offene Frage – „So, how’s your week been?“ passt fast immer.'),
  retten('en.re.05', 'en.recovery', 3, { ...EMMA, text: "You look exactly like my ex-boyfriend.", de: 'Du siehst genauso aus wie mein Ex-Freund.' }, [
    "Ha! I hope that's a good thing.",
    '~0.5 Really? That is strange.::Geht – Humor entschärft besser.',
    'Do you miss him?::Sehr persönlich für den Anfang.',
    'That’s weird, please stop.::Zu harsch für eine harmlose Bemerkung.',
  ], 'Humor ist der eleganteste Ausweg aus unerwarteten Bemerkungen.'),
  retten('en.re.06', 'en.recovery', 4, { ...TOM, text: "Sorry, could you speak up? It's really loud in here.", de: 'Sorry, könntest du lauter sprechen? Hier ist es sehr laut.' }, [
    "Of course – is this better? I was asking about the meeting.",
    '~0.5 Yes. I asked about the meeting.::Passt – mit „is this better?“ zeigst du Rücksicht.',
    'I always speak like this.::Wirkt unfreundlich.',
    'Let’s talk later then.::Möglich, aber das Gespräch endet.',
  ], 'Wiederholen und dabei die Situation anerkennen: „Of course – is this better?“'),
  retten('en.re.07', 'en.recovery', 4, { ...SUE, text: 'Wait – have we met before?', de: 'Moment – kennen wir uns?' }, [
    "Possibly! Were you at the conference in Leeds?",
    '~0.5 I don’t think so.::Kann sein – eine Vermutung hält das Gespräch offen.',
    'No, definitely not.::Sehr bestimmt und etwas abweisend.',
    'Everyone says that to me.::Klingt genervt.',
  ], 'Offen bleiben und einen Anhaltspunkt anbieten – so klärt sich schnell, ob man sich kennt.'),
  retten('en.re.08', 'en.recovery', 4, { ...BEN, text: "I'm afraid I completely disagree with you.", de: 'Ich muss Ihnen leider völlig widersprechen.' }, [
    "That's fair enough – what makes you see it differently?",
    '~0.5 Okay, that is your opinion.::Höflich, aber das Gespräch endet.',
    'You are wrong.::Führt in den Streit.',
    'Sorry, forget what I said.::Zu schnell eingeknickt.',
  ], 'Widerspruch nimmt man an und fragt nach – „What makes you see it differently?“'),
  retten('en.re.09', 'en.recovery', 5, { ...EMMA, text: "Sorry, I have to take this call.", de: 'Sorry, ich muss rangehen.' }, [
    'No problem at all – take your time.',
    '~0.5 Okay, I wait here.::Passt, klingt aber steif.',
    'Now? We were talking.::Macht Druck.',
    'Fine.::Der Ton wirkt eingeschnappt.',
  ], '„Take your time“ ist die entspannte Reaktion, wenn jemand kurz weg muss.'),
]

// ---------- Klingt das natürlich? ----------

function duell(id: string, ziel: string, stufe: Stufe, richtig: string, falsch: string, warum: string, frage?: string): DuellItem {
  return {
    id,
    spiel: 'en.natuerlich',
    art: 'duell',
    ziel,
    stufe,
    a: richtig,
    b: falsch,
    richtig: 'a',
    warum,
    sprache: 'en-GB',
    frage: frage ?? 'Welcher Satz klingt für englische Ohren normal?',
  }
}

export const NATUERLICH: DuellItem[] = [
  duell('en.na.01', 'en.falsefriends', 1, 'Could I get a receipt, please?', 'Could I become a receipt, please?', '„become“ heißt „werden“. Bekommen ist „get“.'),
  duell('en.na.02', 'en.routine', 1, "I've lived here for two years.", 'I live here since two years.', 'Was in der Vergangenheit begann und andauert: Present Perfect mit „for“.'),
  duell('en.na.03', 'en.greet', 1, 'See you on Monday.', 'See you at Monday.', 'Bei Wochentagen steht „on“.'),
  duell('en.na.04', 'en.wh', 1, 'Do you know what time it is?', 'Do you know how late it is?', '„Wie spät ist es?“ heißt auf Englisch „What time is it?“'),
  duell('en.na.05', 'en.hobbys', 2, "I'm looking forward to the weekend.", 'I look forward on the weekend.', '„look forward to“ – die Präposition ist fest.'),
  duell('en.na.06', 'en.smalltalk', 2, 'It depends on the weather.', 'It depends of the weather.', '„depend on“ – nie „of“.'),
  duell('en.na.07', 'en.reactions', 2, "I'm bored.", "I'm boring.", '„I’m boring“ hieße: Ich bin langweilig.', 'Welcher Satz sagt: Mir ist langweilig?'),
  duell('en.na.08', 'en.shop', 2, 'Can I borrow your pen?', 'Can I lend your pen?', '„borrow“ = sich leihen, „lend“ = verleihen.'),
  duell('en.na.09', 'en.work', 2, 'I made a mistake.', 'I did a mistake.', 'Fehler „macht“ man mit „make“.'),
  duell('en.na.10', 'en.work', 3, 'She gave me some good advice.', 'She gave me a good advice.', '„advice“ ist unzählbar – kein „a“ und kein Plural.'),
  duell('en.na.11', 'en.email', 3, 'The information is very helpful.', 'The informations are very helpful.', '„information“ gibt es nur im Singular.'),
  duell('en.na.12', 'en.travel', 2, "I'm on holiday next week.", 'I make holidays next week.', 'Urlaub „macht“ man im Englischen nicht.'),
  duell('en.na.13', 'en.order', 2, "I'd like to book a table for two people.", "I'd like to reserve a table for two persons.", '„people“ statt „persons“ – „persons“ steht fast nur in Amtstexten.'),
  duell('en.na.14', 'en.recovery', 1, "Sorry, I don't understand.", 'Sorry, I understand not.', 'Verneinung mit „don’t“ – nicht am Satzende.'),
  duell('en.na.15', 'en.travel', 2, 'How was your flight?', 'How was your fly?', '„flight“ ist der Flug, „fly“ die Fliege.'),
  duell('en.na.16', 'en.polite', 2, "Thanks, that's very kind of you.", 'Thanks, that is very kind from you.', 'Die feste Wendung heißt „kind of you“.'),
  duell('en.na.17', 'en.invite', 3, "I'm afraid I can't make it.", "I'm afraid I can't do it possible.", '„make it“ = es schaffen, hinkommen.'),
  duell('en.na.18', 'en.hobbys', 2, "We're going to the cinema tonight.", 'We go in the cinema tonight.', '„go to the cinema“ – und für feste Pläne das Present Progressive.'),
  duell('en.na.19', 'en.numbers', 2, 'It costs ten pounds.', 'It costs ten pound.', 'Nach Zahlen steht der Plural: pounds.'),
  duell('en.na.20', 'en.directions', 3, 'Could you speak more slowly, please?', 'Could you speak more slow, please?', 'Zum Verb gehört das Adverb „slowly“.'),
  duell('en.na.21', 'en.work', 3, 'She works in marketing.', 'She works by marketing.', 'Branchen mit „in“: in marketing, in IT, in sales.'),
  duell('en.na.22', 'en.followup', 3, 'What are you up to this weekend?', 'What are you making this weekend?', '„be up to something“ = etwas vorhaben.'),
  duell('en.na.23', 'en.greet', 3, 'Nice to see you again!', 'Nice to meet you again!', '„meet“ nimmt man beim ersten Mal, danach „see“.', 'Ihr kennt euch schon – welcher Satz passt?'),
  duell('en.na.24', 'en.apology', 3, "I'm sorry for the delay.", "I'm sorry for the delay of me.", 'Kurz und fest: „sorry for the delay“.'),
  duell('en.na.25', 'en.origin', 2, 'He is married to Anna.', 'He is married with Anna.', '„married to“ – nicht „with“.'),
  duell('en.na.26', 'en.yesno', 2, 'I agree with you.', 'I am agree with you.', '„agree“ ist schon das Verb – ohne „am“.'),
  duell('en.na.27', 'en.travel', 3, 'We arrived at the airport at six.', 'We arrived to the airport at six.', '„arrive at“ (Ort) oder „arrive in“ (Stadt, Land).'),
  duell('en.na.28', 'en.food', 3, "I don't eat meat.", 'I eat no meat.', 'Die übliche Verneinung ist „don’t eat“.'),
  duell('en.na.29', 'en.money', 3, 'How much does it cost?', 'How much costs it?', 'Bei Fragen mit „does“ bleibt das Verb in der Grundform am Ende.'),
  duell('en.na.30', 'en.ending', 4, "It's been lovely talking to you.", 'It was lovely to talk with you.', 'Die übliche Abschiedsformel: „It’s been lovely talking to you.“'),
  duell('en.na.31', 'en.hotel', 3, 'Is breakfast included?', 'Is the breakfast inside?', '„included“ = inbegriffen.'),
  duell('en.na.32', 'en.falsefriends', 4, "Can you give me a hand?", 'Can you give me a hand of help?', '„give me a hand“ heißt schon: hilf mir.'),
  duell('en.na.33', 'en.falsefriends', 4, "I'm going to the chemist's.", "I'm going to the drugstore for medicine.", 'In Großbritannien heißt die Apotheke „chemist’s“ oder „pharmacy“.', 'Du bist in England – welcher Satz passt?'),
  duell('en.na.34', 'en.falsefriends', 5, 'My boss is in a meeting.', 'My chef is in a meeting.', '„chef“ ist der Küchenchef, der Vorgesetzte heißt „boss“ oder „manager“.'),
  duell('en.na.35', 'en.falsefriends', 5, 'Where is my mobile?', 'Where is my handy?', '„handy“ ist ein Adjektiv (praktisch). Das Telefon heißt „mobile“ oder „phone“.'),
  duell('en.na.36', 'en.recovery', 4, 'Sorry, could you say that again?', 'Sorry, can you repeat that one more time again?', 'Kurz und höflich: „Could you say that again?“'),
  duell('en.na.37', 'en.origin', 1, "I'm from Munich.", 'I am out of Munich.', 'Herkunft immer mit „from“ – „out of“ heißt „aus … heraus“.'),
  duell('en.na.38', 'en.intro', 2, 'Nice to meet you.', 'Nice to know you.', 'Beim Kennenlernen sagt man „meet“ – „know“ setzt voraus, dass man sich schon kennt.'),
  duell('en.na.39', 'en.wh', 1, 'How old are you?', 'How old have you?', 'Das Alter steht im Englischen mit „be“, nicht mit „have“.'),
  duell('en.na.40', 'en.numbers', 3, "What's the date today?", 'What date have we today?', 'Das Datum erfragt man mit „What’s the date?“ – „Den Wievielten haben wir?“ lässt sich nicht wörtlich übersetzen.'),
  duell('en.na.41', 'en.routine', 2, 'I go to work by bike.', 'I drive with the bike to work.', 'Verkehrsmittel mit „by“ – und Fahrrad fährt man nicht mit „drive“.'),
  duell('en.na.42', 'en.hobbys', 2, 'I like cooking.', 'I cook gladly.', '„gern“ gibt es nicht als eigenes Wort – es steckt in „like + -ing“.'),
  duell('en.na.43', 'en.shop', 2, 'Can I try this on?', 'Can I try this at?', '„try on“ heißt anprobieren – die Partikel gehört fest dazu.'),
  duell('en.na.44', 'en.money', 2, "Here's your change.", "Here's your rest.", 'Wechselgeld heißt „change“; „rest“ ist der Rest von etwas anderem.'),
  duell('en.na.45', 'en.shop', 3, "It doesn't fit.", "It doesn't fit to me.", '„fit“ steht ohne „to“ – es passt oder eben nicht.'),
  duell('en.na.46', 'en.order', 1, 'Can we have the menu, please?', 'Can we have the map, please?', 'Die Speisekarte heißt „menu“ – „map“ ist die Landkarte.'),
  duell('en.na.47', 'en.food', 2, "I'm full, thanks.", "I'm fed up, thanks.", '„fed up“ heißt genervt. Satt ist man mit „full“.'),
  duell('en.na.48', 'en.order', 3, 'Shall we split the bill?', 'Shall we pay separate?', 'Getrennt zahlen heißt „split the bill“ – oder „pay separately“ mit Adverb.'),
  duell('en.na.49', 'en.smalltalk', 3, "I haven't seen you in ages.", 'I have you long not seen.', 'Im Englischen bleibt das Verb direkt beim Hilfsverb – die deutsche Wortstellung passt hier nicht.'),
  duell('en.na.50', 'en.followup', 3, 'What do you mean exactly?', 'What mean you exactly?', 'Fragen im Present brauchen „do“.'),
  duell('en.na.51', 'en.polite', 2, 'Could you help me, please?', 'Can you please to help me?', 'Nach „can“ und „could“ steht die Grundform ohne „to“.'),
  duell('en.na.52', 'en.apology', 2, 'It was my fault.', 'It was my guilt.', '„guilt“ ist Schuld im moralischen Sinn – ein Versehen ist „my fault“.'),
  duell('en.na.53', 'en.email', 3, 'Please find the file attached.', 'In the annex you find the file.', 'In Mails heißt der Anhang „attachment“ – „annex“ steht in Verträgen und Gesetzen.'),
]

// ---------- Hören ----------

function hoer(id: string, ziel: string, stufe: Stufe, text: string, de: string, frage: string, liste: string[], erklaerung?: string): HoerItem {
  return {
    id,
    spiel: 'en.hoeren',
    art: 'hoeren',
    ziel,
    stufe,
    sprache: 'en-GB',
    text,
    de,
    frage,
    optionen: optionen(liste),
    ...(erklaerung ? { erklaerung } : {}),
  }
}

export const HOEREN: HoerItem[] = [
  hoer('en.ho.01', 'en.directions', 1, 'Could you tell me where the nearest cash machine is?', 'Können Sie mir sagen, wo der nächste Geldautomat ist?', 'Was sucht die Person?', [
    'Einen Geldautomaten',
    'Eine Bäckerei',
    'Die Bushaltestelle',
    'Eine Wechselstube',
  ], '„cash machine“ (auch „cashpoint“) ist der Geldautomat.'),
  hoer('en.ho.02', 'en.travel', 1, 'The train to Edinburgh leaves from platform nine.', 'Der Zug nach Edinburgh fährt von Gleis neun.', 'Von welchem Gleis fährt der Zug?', ['Gleis 9', 'Gleis 5', 'Gleis 19', 'Gleis 90']),
  hoer('en.ho.03', 'en.numbers', 1, "I'll be there in about twenty minutes.", 'Ich bin in etwa zwanzig Minuten da.', 'Wann kommt die Person?', [
    'In ungefähr 20 Minuten',
    'In 12 Minuten',
    'Um 20 Uhr',
    'In zwei Stunden',
  ]),
  hoer('en.ho.04', 'en.order', 2, "Sorry, we're fully booked tonight.", 'Tut mir leid, wir sind heute Abend ausgebucht.', 'Was bedeutet das?', [
    'Heute Abend ist kein Tisch mehr frei.',
    'Das Restaurant hat heute geschlossen.',
    'Man muss vorher anrufen.',
    'Es gibt nur noch Plätze draußen.',
  ]),
  hoer('en.ho.05', 'en.order', 1, 'Would you like anything to drink?', 'Möchten Sie etwas trinken?', 'Welche Antwort passt?', [
    'Just some water, please.',
    'Yes, I am very thirsty person.',
    'No, I drink nothing never.',
    'I would like to eat pizza.',
  ]),
  hoer('en.ho.06', 'en.shop', 2, "I'm afraid we've sold out of that in your size.", 'Leider ist das in Ihrer Größe ausverkauft.', 'Was ist das Problem?', [
    'Die Größe ist nicht mehr da.',
    'Das Geschäft schließt gleich.',
    'Der Artikel ist teurer geworden.',
    'Die Farbe gibt es nicht.',
  ], '„sold out“ = ausverkauft.'),
  hoer('en.ho.07', 'en.hotel', 2, 'Breakfast is served from seven until half ten.', 'Frühstück gibt es von sieben bis halb elf.', 'Bis wann gibt es Frühstück?', [
    'Bis 10:30 Uhr',
    'Bis 9:30 Uhr',
    'Bis 10:00 Uhr',
    'Bis 11:30 Uhr',
  ], 'Im britischen Englisch heißt „half ten“ 10:30 – Vorsicht, im Deutschen wäre „halb zehn“ 9:30.'),
  hoer('en.ho.08', 'en.work', 3, "Let's push the meeting back to Thursday.", 'Lass uns das Treffen auf Donnerstag verschieben.', 'Was soll passieren?', [
    'Das Treffen wird auf Donnerstag verlegt.',
    'Das Treffen fällt aus.',
    'Das Treffen wird vorgezogen.',
    'Das Treffen dauert länger.',
  ], '„push back“ = nach hinten verschieben.'),
  hoer('en.ho.09', 'en.invite', 2, 'Do you fancy grabbing a bite after work?', 'Hast du Lust, nach der Arbeit eine Kleinigkeit essen zu gehen?', 'Worum geht es?', [
    'Eine Einladung zum Essen',
    'Eine Bitte um Hilfe',
    'Eine Absage',
    'Eine Frage nach der Uhrzeit',
  ], '„grab a bite“ = schnell etwas essen.'),
  hoer('en.ho.10', 'en.apology', 2, "I'm ever so sorry, I completely forgot.", 'Es tut mir schrecklich leid, ich habe es völlig vergessen.', 'Was tut die Person?', [
    'Sie entschuldigt sich.',
    'Sie macht einen Vorschlag.',
    'Sie bedankt sich.',
    'Sie sagt ab.',
  ]),
  hoer('en.ho.11', 'en.numbers', 2, "That'll be twelve pounds fifty, please.", 'Das macht 12,50 Pfund, bitte.', 'Wie viel kostet es?', ['£12,50', '£12,15', '£20,50', '£15,20']),
  hoer('en.ho.12', 'en.smalltalk', 3, "It's absolutely chucking it down out there.", 'Draußen schüttet es wie aus Eimern.', 'Wie ist das Wetter?', [
    'Es regnet stark.',
    'Es ist windig.',
    'Es schneit.',
    'Es ist sehr heiß.',
  ], '„chucking it down“ ist britische Umgangssprache für starken Regen.'),
  hoer('en.ho.13', 'en.travel', 3, 'This service is delayed by approximately fifteen minutes.', 'Dieser Zug hat etwa fünfzehn Minuten Verspätung.', 'Was ist los?', [
    'Der Zug hat etwa 15 Minuten Verspätung.',
    'Der Zug fällt aus.',
    'Der Zug fährt von einem anderen Gleis.',
    'Der Zug ist 50 Minuten zu spät.',
  ], 'In Bahnhöfen heißt der Zug oft „service“.'),
  hoer('en.ho.14', 'en.polite', 3, 'Would you mind if I sat here?', 'Hätten Sie etwas dagegen, wenn ich mich hierhin setze?', 'Welche Antwort heißt „Ja, setz dich“?', [
    'Not at all, go ahead.',
    'Yes, I would mind.',
    'Yes, please sit.',
    'Of course I mind.',
  ], 'Bei „Would you mind …?“ heißt „Not at all“: Nein, stört mich nicht – also ja, gern.'),
  hoer('en.ho.15', 'en.work', 4, "I'll get back to you by the end of the day.", 'Ich melde mich bis zum Ende des Tages bei dir.', 'Was sagt die Person zu?', [
    'Sie meldet sich heute noch.',
    'Sie kommt morgen vorbei.',
    'Sie hat schon geantwortet.',
    'Sie kann nicht helfen.',
  ]),
  hoer('en.ho.16', 'en.food', 3, 'Are you allergic to anything?', 'Sind Sie gegen etwas allergisch?', 'Was wird gefragt?', [
    'Ob man Allergien hat',
    'Ob man Vegetarier ist',
    'Ob es geschmeckt hat',
    'Ob man nachbestellen möchte',
  ]),
  hoer('en.ho.17', 'en.hobbys', 3, 'I used to play tennis, but I gave it up years ago.', 'Ich habe früher Tennis gespielt, aber vor Jahren aufgehört.', 'Was stimmt?', [
    'Die Person spielt heute kein Tennis mehr.',
    'Die Person spielt jede Woche Tennis.',
    'Die Person will gerade anfangen.',
    'Die Person hat nie Tennis gespielt.',
  ], '„used to“ beschreibt etwas Früheres, das heute nicht mehr gilt.'),
  hoer('en.ho.18', 'en.ending', 4, "Right, I'd best be off.", 'So, ich mache mich mal auf den Weg.', 'Was bedeutet das?', [
    'Die Person will gehen.',
    'Die Person hat keine Zeit verloren.',
    'Die Person ist beleidigt.',
    'Die Person will noch bleiben.',
  ], '„I’d best be off“ ist eine britische Abschiedsformel.'),
  hoer('en.ho.19', 'en.greet', 1, 'How do you do?', 'Sehr erfreut.', 'Wann sagt man das?', [
    'Bei einer sehr förmlichen ersten Begegnung',
    'Wenn man sich gut kennt',
    'Beim Abschied',
    'Wenn man sich entschuldigt',
  ], '„How do you do?“ ist sehr förmlich und heute selten – die Antwort darauf ist ebenfalls „How do you do?“'),
  hoer('en.ho.20', 'en.recovery', 4, "Sorry, you've lost me there.", 'Sorry, jetzt komme ich nicht mehr mit.', 'Was meint die Person?', [
    'Sie hat den Faden verloren.',
    'Sie hat sich verlaufen.',
    'Sie muss gehen.',
    'Sie ist anderer Meinung.',
  ], '„You’ve lost me“ heißt: Ich verstehe gerade nicht mehr.'),
  hoer('en.ho.21', 'en.intro', 1, "Hi, I'm Sarah – I work in the design team.", 'Hi, ich bin Sarah – ich arbeite im Design-Team.', 'Was erfahren wir über Sarah?', [
    'Sie arbeitet im Design-Team',
    'Sie sucht das Design-Team',
    'Sie leitet die Firma',
    'Sie ist neu und hat noch kein Team',
  ]),
  hoer('en.ho.22', 'en.origin', 1, "I'm originally from Ireland, but I live in London now.", 'Ich komme ursprünglich aus Irland, wohne aber jetzt in London.', 'Wo wohnt die Person heute?', [
    'In London',
    'In Irland',
    'In Dublin',
    'Sie zieht bald nach Irland',
  ], '„originally from“ = ursprünglich aus – der heutige Wohnort kommt danach.'),
  hoer('en.ho.23', 'en.greet', 2, "Lovely to see you again – it's been ages!", 'Schön, dich wiederzusehen – das ist ewig her!', 'Was stimmt?', [
    'Die beiden kennen sich und haben sich lange nicht gesehen',
    'Die beiden treffen sich zum ersten Mal',
    'Sie haben sich gestern gesehen',
    'Die Person verabschiedet sich gerade',
  ], '„It’s been ages“ heißt: Das ist ewig her.'),
  hoer('en.ho.24', 'en.numbers', 1, 'The meeting starts at quarter past three.', 'Das Treffen beginnt um Viertel nach drei.', 'Wann beginnt das Treffen?', [
    'Um 15:15',
    'Um 15:45',
    'Um 14:45',
    'Um 03:30',
  ], '„quarter past“ = Viertel nach, „quarter to“ = Viertel vor.'),
  hoer('en.ho.25', 'en.wh', 2, 'Sorry, how do you spell your surname?', 'Entschuldigung, wie schreibt sich Ihr Nachname?', 'Was möchte die Person?', [
    'Den Nachnamen buchstabiert bekommen',
    'Den Vornamen wissen',
    'Wissen, wie man den Namen ausspricht',
    'Die Adresse aufschreiben',
  ], '„surname“ ist der Nachname, „to spell“ heißt buchstabieren.'),
  hoer('en.ho.26', 'en.routine', 1, 'I usually get up at half six during the week.', 'Unter der Woche stehe ich meistens um halb sieben auf.', 'Wann steht die Person auf?', [
    'Um 06:30',
    'Um 05:30',
    'Um 06:06',
    'Um 18:30',
  ], 'Achtung: Britisch „half six“ heißt 6:30 – also halb sieben, nicht halb sechs.'),
  hoer('en.ho.27', 'en.hobbys', 2, "I've taken up running – three times a week now.", 'Ich habe mit dem Laufen angefangen – dreimal die Woche.', 'Was ist neu?', [
    'Die Person hat mit Laufen angefangen',
    'Die Person hat mit Laufen aufgehört',
    'Die Person läuft dreimal im Monat',
    'Die Person will nächstes Jahr anfangen',
  ], '„to take up something“ = mit etwas anfangen.'),
  hoer('en.ho.28', 'en.routine', 2, 'I work from home on Tuesdays and Thursdays.', 'Dienstags und donnerstags arbeite ich von zu Hause.', 'An welchen Tagen ist die Person im Homeoffice?', [
    'Dienstag und Donnerstag',
    'Montag und Donnerstag',
    'Dienstag und Freitag',
    'Nur donnerstags',
  ]),
  hoer('en.ho.29', 'en.shop', 1, 'Have you got this in a size ten?', 'Haben Sie das in Größe zehn?', 'Was möchte die Person?', [
    'Dasselbe Teil in einer bestimmten Größe',
    'Zehn Stück davon',
    'Den Preis wissen',
    'Etwas zurückgeben',
  ], '„Have you got this in a size …?“ ist die Standardfrage im Laden.'),
  hoer('en.ho.30', 'en.money', 2, "That'll be fourteen pounds fifty, please.", 'Das macht vierzehn Pfund fünfzig, bitte.', 'Wie viel kostet es?', [
    '14,50 £',
    '40,15 £',
    '15,40 £',
    '4,50 £',
  ]),
  hoer('en.ho.31', 'en.shop', 2, "I'm afraid we've sold out of those, but we're getting more in on Friday.", 'Leider sind die ausverkauft, aber am Freitag kommt Nachschub.', 'Was sagt die Verkäuferin?', [
    'Ausverkauft – ab Freitag wieder da',
    'Es sind noch welche im Lager',
    'Das Produkt gibt es nicht mehr',
    'Am Freitag ist das Geschäft zu',
  ], '„sold out“ = ausverkauft, „to get something in“ = neu hereinbekommen.'),
  hoer('en.ho.32', 'en.order', 2, 'Would you like still or sparkling water?', 'Möchten Sie stilles Wasser oder mit Kohlensäure?', 'Wonach wird gefragt?', [
    'Ob das Wasser Kohlensäure haben soll',
    'Ob Sie Wasser oder Wein möchten',
    'Ob das Wasser kalt sein soll',
    'Ob Sie eine Flasche oder ein Glas möchten',
  ], '„still“ = ohne Kohlensäure, „sparkling“ = mit.'),
  hoer('en.ho.33', 'en.smalltalk', 2, "It's meant to brighten up later.", 'Später soll es aufklaren.', 'Was sagt die Person über das Wetter?', [
    'Später soll es aufklaren',
    'Es soll den ganzen Tag regnen',
    'Es wird deutlich kälter',
    'Sie weiß nichts über das Wetter',
  ], '„It’s meant to …“ heißt: Es soll (laut Vorhersage) …'),
  hoer('en.ho.34', 'en.followup', 3, 'How did it go in the end?', 'Und, wie ist es am Ende gelaufen?', 'Was will die Person wissen?', [
    'Wie die Sache ausgegangen ist',
    'Wohin du gegangen bist',
    'Wann du losgefahren bist',
    'Ob du bis zum Ende geblieben bist',
  ], '„How did it go?“ fragt nach dem Ausgang einer Sache.'),
  hoer('en.ho.35', 'en.reactions', 2, 'That must have been really stressful.', 'Das war bestimmt richtig stressig.', 'Was macht die Person gerade?', [
    'Sie zeigt Verständnis',
    'Sie beschwert sich',
    'Sie fragt nach Details',
    'Sie erzählt von sich selbst',
  ], '„That must have been …“ ist die übliche mitfühlende Reaktion.'),
  hoer('en.ho.36', 'en.invite', 2, "We're having a few people round on Saturday – fancy coming?", 'Wir haben am Samstag ein paar Leute da – hast du Lust zu kommen?', 'Was passiert hier?', [
    'Du wirst eingeladen',
    'Jemand sagt dir ab',
    'Jemand fragt nach dem Weg',
    'Jemand bittet um Hilfe beim Aufräumen',
  ], '„to have people round“ = Leute zu sich einladen, „fancy …?“ = Hast du Lust?'),
  hoer('en.ho.37', 'en.work', 2, 'Could we push the call back to half four?', 'Können wir das Telefonat auf halb fünf schieben?', 'Was wird vorgeschlagen?', [
    'Das Telefonat auf 16:30 verschieben',
    'Das Telefonat auf 15:30 vorziehen',
    'Das Telefonat ganz absagen',
    'Vier Personen dazuholen',
  ], '„to push back“ = nach hinten schieben; „half four“ ist 16:30.'),
  hoer('en.ho.38', 'en.email', 3, "I'll drop you a line once I've heard back from them.", 'Ich melde mich, sobald ich von ihnen gehört habe.', 'Was passiert als Nächstes?', [
    'Die Person meldet sich, sobald sie Antwort hat',
    'Die Person ruft sofort an',
    'Die Person wartet auf deine Antwort',
    'Die Person hat die Sache abgegeben',
  ], '„to drop someone a line“ = sich kurz melden.'),
  hoer('en.ho.39', 'en.recovery', 3, "Sorry, I didn't quite catch that – could you say it again?", 'Sorry, das habe ich nicht ganz verstanden – kannst du es wiederholen?', 'Was braucht die Person?', [
    'Eine Wiederholung',
    'Eine Übersetzung',
    'Einen Stift',
    'Mehr Zeit zum Nachdenken',
  ], '„I didn’t catch that“ ist der höflichste Weg, um eine Wiederholung zu bitten.'),
  hoer('en.ho.40', 'en.ending', 3, "Right, I'd better get going – my train's at six.", 'Also, ich mache mich mal auf den Weg – mein Zug fährt um sechs.', 'Was tut die Person?', [
    'Sie verabschiedet sich',
    'Sie kommt gerade an',
    'Sie fragt nach dem Zug',
    'Sie lädt dich ein',
  ], '„I’d better get going“ leitet den Abschied ein.'),
]

// ---------- Satzbau ----------

function bau(id: string, ziel: string, stufe: Stufe, text: string, bedeutung: string, erklaerung: string, extra?: string[]): BauItem {
  return {
    id,
    spiel: 'en.satzbau',
    art: 'bau',
    ziel,
    stufe,
    teile: bausteine(text),
    fest: 1,
    bedeutung,
    sprache: 'en-GB',
    ...(extra ? { extra } : {}),
    erklaerung,
  }
}

export const SATZBAU: BauItem[] = [
  bau('en.sb.01', 'en.order', 1, 'Could | I | have | the bill, | please?', 'Könnte ich bitte die Rechnung haben?', 'Höfliche Bitten beginnen mit „Could I have …“ und enden mit „please“.'),
  bau('en.sb.27', 'en.intro', 1, "Hi, | I'm | Jonas – | nice | to | meet you.", 'Hi, ich bin Jonas – freut mich.', 'Die Standardvorstellung: Name plus „nice to meet you“.'),
  bau('en.sb.28', 'en.intro', 2, 'Could | you | spell | your name | for me, | please?', 'Könnten Sie Ihren Namen bitte buchstabieren?', '„spell“ heißt buchstabieren – sehr nützlich mit deutschen Namen.'),
  bau('en.sb.02', 'en.routine', 2, "I've | been | learning | English | for | three years.", 'Ich lerne seit drei Jahren Englisch.', 'Andauernde Zeitspanne: Present Perfect Progressive mit „for“.', ['since']),
  bau('en.sb.03', 'en.travel', 1, 'What | time | does | the next train | leave?', 'Wann fährt der nächste Zug?', 'Fragen mit „does“: Das Hauptverb bleibt in der Grundform.'),
  bau('en.sb.04', 'en.hobbys', 2, "I'm | looking | forward | to | the weekend.", 'Ich freue mich auf das Wochenende.', '„look forward to“ – die Präposition gehört fest dazu.', ['on']),
  bau('en.sb.05', 'en.polite', 2, 'Would | you | mind | opening | the window?', 'Würden Sie bitte das Fenster öffnen?', 'Nach „Would you mind“ steht die -ing-Form.', ['to open']),
  bau('en.sb.06', 'en.directions', 1, 'There | is | a supermarket | around | the corner.', 'Um die Ecke ist ein Supermarkt.', '„There is …“ sagt, dass es etwas gibt.'),
  bau('en.sb.07', 'en.money', 1, 'How | much | does | it | cost?', 'Wie viel kostet es?', 'Frageform mit „does“ – das Verb bleibt unverändert.'),
  bau('en.sb.08', 'en.invite', 3, "I'd | rather | stay | at home | tonight.", 'Ich würde heute Abend lieber zu Hause bleiben.', '„I’d rather“ + Grundform drückt eine Vorliebe aus.'),
  bau('en.sb.09', 'en.directions', 2, 'Do | you | know | where | the station | is?', 'Wissen Sie, wo der Bahnhof ist?', 'In der indirekten Frage steht das Verb hinten: „where the station is“.'),
  bau('en.sb.10', 'en.invite', 3, "I'm | afraid | I | can't | make it | on Friday.", 'Leider schaffe ich es am Freitag nicht.', '„I’m afraid …“ macht eine Absage freundlich.'),
  bau('en.sb.11', 'en.work', 3, 'She | has | been | working | here | since | May.', 'Sie arbeitet seit Mai hier.', 'Mit einem Zeitpunkt steht „since“, mit einer Dauer „for“.', ['for']),
  bau('en.sb.12', 'en.work', 2, 'Let | me | know | if | you | need | anything.', 'Sag Bescheid, wenn du etwas brauchst.', '„Let me know“ ist die übliche Wendung für „Sag mir Bescheid“.'),
  bau('en.sb.13', 'en.travel', 2, 'It | takes | about | twenty minutes | by bus.', 'Mit dem Bus dauert es etwa zwanzig Minuten.', 'Für die Dauer nimmt man „It takes …“.'),
  bau('en.sb.14', 'en.email', 3, 'Could | you | send | me | the file, | please?', 'Könntest du mir bitte die Datei schicken?', 'Nach „send“ kommt erst die Person, dann die Sache.'),
  bau('en.sb.15', 'en.routine', 3, "I | haven't | seen | him | since | last year.", 'Ich habe ihn seit letztem Jahr nicht gesehen.', 'Present Perfect mit „since“ + Zeitpunkt.'),
  bau('en.sb.16', 'en.invite', 2, 'Do | you | fancy | going | for | a walk?', 'Hast du Lust, spazieren zu gehen?', 'Nach „fancy“ steht die -ing-Form.', ['to go']),
  bau('en.sb.17', 'en.email', 2, 'Thanks | for | letting | me | know.', 'Danke für die Info.', 'Nach „thanks for“ steht die -ing-Form.'),
  bau('en.sb.18', 'en.apology', 3, "I'm | sorry | for | the | late | reply.", 'Entschuldigung für die späte Antwort.', 'Feste Wendung in Mails: „Sorry for the late reply.“'),
  bau('en.sb.19', 'en.wh', 2, 'How | long | have | you | been | waiting?', 'Wie lange wartest du schon?', 'Dauer bis jetzt: Present Perfect Progressive.'),
  bau('en.sb.20', 'en.origin', 3, 'I | used | to | live | in Manchester.', 'Früher habe ich in Manchester gelebt.', '„used to“ beschreibt Früheres, das heute nicht mehr gilt.'),
  bau('en.sb.21', 'en.invite', 2, 'Would | you | like | to | join | us?', 'Möchtest du mitkommen?', 'Nach „Would you like“ steht „to“ + Grundform.'),
  bau('en.sb.22', 'en.work', 4, 'The meeting | has | been | moved | to | Thursday.', 'Das Treffen wurde auf Donnerstag verschoben.', 'Passiv im Present Perfect: has been + Partizip.'),
  bau('en.sb.23', 'en.money', 2, 'Can | I | pay | by | card?', 'Kann ich mit Karte zahlen?', 'Zahlungsart mit „by“: by card, by bank transfer.', ['with']),
  bau('en.sb.24', 'en.travel', 4, 'I | think | I | left | my umbrella | on the train.', 'Ich glaube, ich habe meinen Schirm im Zug liegen lassen.', '„leave“ heißt hier: etwas liegen lassen.'),
  bau('en.sb.25', 'en.smalltalk', 2, 'What | do | you | usually | do | at the weekend?', 'Was machst du normalerweise am Wochenende?', 'Im britischen Englisch heißt es „at the weekend“.', ['on the weekend']),
  bau('en.sb.26', 'en.ending', 3, "It's | been | lovely | talking | to | you.", 'Es war sehr nett, mit dir zu reden.', 'Die typische Abschiedsformel nach einem guten Gespräch.'),
  bau('en.sb.29', 'en.wh', 2, 'What | time | do | you | usually | finish | work?', 'Wann hast du normalerweise Feierabend?', 'W-Frage im Present: „do“ vor dem Subjekt, das Verb bleibt in der Grundform.'),
  bau('en.sb.30', 'en.numbers', 2, 'The tickets | are | fifteen pounds | each.', 'Die Tickets kosten je fünfzehn Pfund.', '„each“ steht am Ende und heißt: pro Stück.'),
  bau('en.sb.31', 'en.yesno', 2, "No, | I | haven't | been | there | before.", 'Nein, ich war noch nie dort.', 'Erfahrungen bis jetzt stehen im Present Perfect.', ['was']),
  bau('en.sb.32', 'en.shop', 2, 'Have | you | got | this | in | a smaller size?', 'Haben Sie das in einer kleineren Größe?', 'Britisch fragt man mit „Have you got …?“ statt „Do you have …?“'),
  bau('en.sb.33', 'en.order', 2, "I'd | like | the soup | to | start, | please.", 'Als Vorspeise hätte ich gern die Suppe.', '„to start“ heißt im Lokal: als Vorspeise.'),
  bau('en.sb.34', 'en.food', 3, "I'm | allergic | to | nuts – | is | that | a problem?", 'Ich bin allergisch gegen Nüsse – ist das ein Problem?', '„allergic to“ – die Präposition gehört fest dazu.', ['against']),
  bau('en.sb.35', 'en.smalltalk', 2, 'Have | you | been | busy | lately?', 'Hast du in letzter Zeit viel zu tun gehabt?', '„lately“ steht am Satzende und verlangt das Present Perfect.'),
  bau('en.sb.36', 'en.followup', 3, 'How | did | it | go | in the end?', 'Wie ist es am Ende gelaufen?', 'In der Vergangenheit steht „did“ vorn, das Verb bleibt in der Grundform.'),
  bau('en.sb.37', 'en.recovery', 3, "Sorry, | I | didn't | quite | catch | that.", 'Sorry, das habe ich nicht ganz verstanden.', '„quite“ steht zwischen „didn’t“ und dem Verb und macht die Aussage weicher.'),
  bau('en.sb.38', 'en.falsefriends', 4, 'Could | you | give | me | a hand | with this?', 'Könntest du mir hiermit helfen?', '„give someone a hand“ heißt helfen – erst die Person, dann „a hand“.'),
]

// ---------- Wortpaare ----------

function paar(nr: number, ziel: string, stufe: Stufe, links: string, rechts: string, beispiel?: string): PaarItem {
  return {
    id: `en.pa.${String(nr).padStart(2, '0')}`,
    spiel: 'en.paare',
    art: 'paar',
    ziel,
    stufe,
    links,
    rechts,
    sprache: 'en-GB',
    ...(beispiel ? { erklaerung: beispiel } : {}),
  }
}

export const PAARE: PaarItem[] = [
  paar(1, 'en.greet', 1, "How's it going?", 'Wie läuft’s?', 'Lockere Begrüßung unter Bekannten.'),
  paar(46, 'en.intro', 1, 'Nice to meet you.', 'Freut mich (beim ersten Treffen).', ''),
  paar(47, 'en.intro', 2, "What's your name again?", 'Wie war noch mal dein Name?', 'Rettet, wenn man den Namen vergessen hat.'),
  paar(2, 'en.reactions', 1, 'Never mind.', 'Macht nichts.', 'Beruhigt, wenn etwas schiefgegangen ist.'),
  paar(3, 'en.yesno', 2, "I'm afraid not.", 'Leider nicht.', 'Höfliches Nein.'),
  paar(4, 'en.reactions', 3, 'Fair enough.', 'Na gut, verstehe.', 'Zeigt: Das Argument nehme ich an.'),
  paar(5, 'en.invite', 2, "It's up to you.", 'Das ist deine Entscheidung.', ''),
  paar(6, 'en.polite', 2, 'Hang on a second.', 'Warte kurz.', ''),
  paar(7, 'en.shop', 2, "I'm just browsing.", 'Ich schaue mich nur um.', 'Antwort im Laden auf „Can I help you?“'),
  paar(8, 'en.reactions', 2, "That's a shame.", 'Wie schade.', ''),
  paar(9, 'en.work', 2, 'Give me a ring.', 'Ruf mich an.', 'Britisch für anrufen.'),
  paar(10, 'en.work', 3, "Let's call it a day.", 'Machen wir Schluss für heute.', ''),
  paar(11, 'en.invite', 3, "I'm not fussed.", 'Mir ist es egal.', 'Britisch, sehr locker.'),
  paar(12, 'en.recovery', 1, 'Could you say that again?', 'Können Sie das wiederholen?', ''),
  paar(13, 'en.money', 3, "It's on me.", 'Ich lade dich ein.', ''),
  paar(14, 'en.work', 3, 'Keep me posted.', 'Halt mich auf dem Laufenden.', ''),
  paar(15, 'en.reactions', 1, 'Sounds good to me.', 'Klingt gut.', ''),
  paar(16, 'en.email', 2, "I'll get back to you.", 'Ich melde mich.', ''),
  paar(17, 'en.wh', 2, "What's it about?", 'Worum geht es?', ''),
  paar(18, 'en.apology', 2, "I'm running late.", 'Ich verspäte mich.', ''),
  paar(19, 'en.ending', 1, 'Take care.', 'Pass auf dich auf.', 'Warmer Abschied.'),
  paar(20, 'en.greet', 2, 'Long time no see.', 'Lange nicht gesehen.', ''),
  paar(21, 'en.apology', 1, 'No worries.', 'Kein Problem.', ''),
  paar(22, 'en.polite', 1, "You're welcome.", 'Gern geschehen.', ''),
  paar(23, 'en.polite', 1, 'Excuse me …', 'Entschuldigung … (jemanden ansprechen)', ''),
  paar(24, 'en.greet', 3, 'Cheers!', 'Danke! / Prost!', 'In Großbritannien oft einfach „danke“.'),
  paar(25, 'en.routine', 4, "I'm knackered.", 'Ich bin total erledigt.', 'Sehr britisch, sehr umgangssprachlich.'),
  paar(26, 'en.reactions', 2, "That's brilliant!", 'Das ist super!', ''),
  paar(27, 'en.invite', 3, 'Shall we?', 'Wollen wir?', 'Kurz vor dem Aufbruch.'),
  paar(28, 'en.invite', 2, 'Do you fancy …?', 'Hast du Lust auf …?', ''),
  paar(29, 'en.food', 3, "It's not my cup of tea.", 'Das ist nicht mein Fall.', ''),
  paar(30, 'en.work', 1, 'Let me know.', 'Sag mir Bescheid.', ''),
  paar(31, 'en.smalltalk', 3, 'How have you been?', 'Wie ist es dir ergangen?', 'Wenn man sich länger nicht gesehen hat.'),
  paar(32, 'en.recovery', 3, "I'm with you.", 'Ich kann dir folgen.', 'Zeigt: Ich verstehe, was du meinst.'),
  paar(33, 'en.work', 4, "I'll sort it out.", 'Ich kümmere mich darum.', ''),
  paar(34, 'en.smalltalk', 3, 'What have you been up to?', 'Was hast du so gemacht?', ''),
  paar(35, 'en.reactions', 4, 'You must be joking!', 'Das ist nicht dein Ernst!', ''),
  paar(36, 'en.apology', 3, 'My fault.', 'Mein Fehler.', ''),
  paar(37, 'en.hotel', 2, 'Could I have a wake-up call?', 'Könnten Sie mich wecken?', ''),
  paar(38, 'en.travel', 2, 'Is this seat taken?', 'Ist dieser Platz frei?', 'Wörtlich: Ist dieser Platz besetzt?'),
  paar(39, 'en.shop', 3, 'Have you got this in a medium?', 'Haben Sie das in M?', ''),
  paar(40, 'en.order', 2, "I'll have the same, please.", 'Ich nehme dasselbe, bitte.', ''),
  paar(41, 'en.ending', 3, 'I should get going.', 'Ich sollte langsam los.', ''),
  paar(42, 'en.followup', 3, 'Tell me more.', 'Erzähl mehr.', ''),
  paar(43, 'en.polite', 4, 'After you.', 'Nach Ihnen.', 'An der Tür oder im Aufzug.'),
  paar(44, 'en.recovery', 4, "Bear with me.", 'Einen Moment Geduld.', ''),
  paar(45, 'en.work', 4, "It's not a problem at all.", 'Das ist überhaupt kein Problem.', ''),
  paar(60, 'en.wh', 1, 'What do you do?', 'Was machst du beruflich?', 'Fragt nach dem Beruf – nicht nach der Beschäftigung gerade.'),
  paar(61, 'en.yesno', 2, 'Not really.', 'Eigentlich nicht.', 'Weiches Nein, das die Tür offen lässt.'),
  paar(62, 'en.numbers', 2, 'half five', 'halb sechs (17:30)', 'Britische Falle: „half five“ ist 5:30, nicht 4:30.'),
  paar(63, 'en.routine', 1, "I'm running late.", 'Ich bin spät dran.', ''),
  paar(64, 'en.routine', 2, 'on my way home', 'auf dem Heimweg', ''),
  paar(65, 'en.hobbys', 2, "I'm not really into football.", 'Fußball ist nicht so mein Ding.', '„to be into something“ = etwas mögen.'),
  paar(66, 'en.hobbys', 3, 'to take up a hobby', 'ein Hobby anfangen', ''),
  paar(67, 'en.shop', 2, 'Are you being served?', 'Werden Sie schon bedient?', 'Standardfrage im Geschäft.'),
  paar(68, 'en.money', 2, 'Do you take card?', 'Kann man mit Karte zahlen?', ''),
  paar(69, 'en.order', 2, 'Eat in or take away?', 'Zum Hieressen oder zum Mitnehmen?', 'Im Café hört man das bei jeder Bestellung.'),
  paar(70, 'en.food', 2, "I'm starving.", 'Ich habe Riesenhunger.', ''),
  paar(71, 'en.food', 3, "It's not to my taste.", 'Das ist nicht mein Geschmack.', 'Höfliche Art, etwas abzulehnen.'),
  paar(72, 'en.travel', 2, 'The train is delayed.', 'Der Zug hat Verspätung.', ''),
  paar(73, 'en.hotel', 2, 'to check in', 'einchecken', 'Gilt für Hotel und Flughafen.'),
  paar(74, 'en.directions', 2, "It's just around the corner.", 'Es ist gleich um die Ecke.', ''),
]
