// Polizei, Feuerwehr und Ärzte. Jede Wache deckt einen Umkreis ab und rückt aus,
// wenn dort etwas passiert. Sie kosten Unterhalt – dafür sinkt die Kriminalität,
// Brände gehen schneller aus, und Kranke werden versorgt.
import type { BuildingDef } from '../catalog'

export const DIENSTE: BuildingDef[] = [
  {
    id: 'polizeiwache',
    name: 'Polizeiwache',
    category: 'dienste',
    emoji: '🚓',
    size: [1, 1],
    coins: 1100,
    materials: 16,
    effects: { jobs: 10, income: -18, police: 7, crime: -6, happiness: 2 },
    needsLevel: 3,
    note: 'Streifenwagen für das Viertel – Reichweite 7',
    look: {
      kind: 'bau',
      height: 1.6,
      wall: '#e6ecf2',
      roof: '#4a5a6e',
      accent: '#1f4f8c',
      floors: 2,
      stil: {
        dach: 'flach',
        fassade: 'putz',
        fenster: 'normal',
        unten: 'tor',
        farben: ['#e6ecf2', '#dfe6ee', '#e8eef0'],
        extras: ['blaulicht', 'schild', 'fahnenmast'],
        schild: '🚓',
        neon: '#2e86de',
      },
    },
  },
  {
    id: 'polizeipraesidium',
    name: 'Polizeipräsidium',
    category: 'dienste',
    emoji: '🚔',
    size: [2, 2],
    coins: 4200,
    materials: 58,
    effects: { jobs: 40, income: -55, police: 13, crime: -14, happiness: 4 },
    needsLevel: 9,
    note: 'Großwache mit Hubschrauber – Reichweite 13',
    look: {
      kind: 'bau',
      height: 2.8,
      wall: '#d9dee6',
      roof: '#4a5a6e',
      accent: '#1f4f8c',
      floors: 4,
      stil: {
        dach: 'flach',
        fassade: 'stein',
        fenster: 'band',
        unten: 'tor',
        farben: ['#d9dee6', '#e0e4ea', '#d4d8de'],
        extras: ['blaulicht', 'heli', 'fahnenmast', 'schild', 'antenne'],
        schild: '🚔',
        neon: '#2e86de',
        koerper: { tiefe: 0.72, breite: 0.9 },
      },
    },
  },
  {
    id: 'feuerwache',
    name: 'Feuerwache',
    category: 'dienste',
    emoji: '🚒',
    size: [2, 1],
    coins: 1300,
    materials: 18,
    effects: { jobs: 12, income: -18, fire: 8, happiness: 2 },
    needsLevel: 3,
    note: 'Rote Tore, Schlauchturm – Reichweite 8',
    look: {
      kind: 'bau',
      height: 1.5,
      wall: '#c0503a',
      roof: '#5a3a30',
      accent: '#d63a2e',
      floors: 2,
      stil: {
        dach: 'flach',
        fassade: 'ziegel',
        fenster: 'normal',
        unten: 'tor',
        farben: ['#c0503a', '#b5654a', '#a85a42'],
        extras: ['schlauchturm', 'sirene', 'schild'],
        schild: '🚒',
        neon: '#ff3b30',
      },
    },
  },
  {
    id: 'hauptfeuerwache',
    name: 'Hauptfeuerwache',
    category: 'dienste',
    emoji: '🧯',
    size: [2, 2],
    coins: 3800,
    materials: 52,
    effects: { jobs: 35, income: -50, fire: 14, happiness: 3 },
    needsLevel: 9,
    note: 'Leiterwagen und Einsatzleitung – Reichweite 14',
    look: {
      kind: 'bau',
      height: 2,
      wall: '#b5654a',
      roof: '#4a3a30',
      accent: '#d63a2e',
      floors: 3,
      stil: {
        dach: 'flach',
        fassade: 'ziegel',
        fenster: 'band',
        unten: 'tor',
        farben: ['#b5654a', '#c0503a', '#a85a42'],
        extras: ['schlauchturm', 'sirene', 'schild', 'fahnenmast'],
        schild: '🧯',
        neon: '#ff3b30',
        koerper: { tiefe: 0.7, breite: 0.9 },
      },
    },
  },
  {
    id: 'arztpraxis',
    name: 'Arztpraxis',
    category: 'dienste',
    emoji: '🩺',
    size: [1, 1],
    coins: 800,
    materials: 11,
    effects: { jobs: 4, income: -6, health: 6, happiness: 2 },
    needsLevel: 2,
    note: 'Hausarzt um die Ecke – Reichweite 6',
    look: {
      kind: 'bau',
      height: 1.4,
      wall: '#f4f4f0',
      roof: '#6d7a86',
      accent: '#d63a2e',
      floors: 2,
      stil: {
        dach: 'walm',
        fassade: 'putz',
        fenster: 'normal',
        unten: 'eingang',
        farben: ['#f4f4f0', '#eef4f4', '#f4eeee'],
        dachfarben: ['#6d7a86', '#8c4a3a'],
        extras: ['kreuz', 'schild'],
        vielleicht: ['garten'],
        schild: '🩺',
        neon: '#ff3b30',
      },
    },
  },
  {
    id: 'krankenhaus',
    name: 'Krankenhaus',
    category: 'dienste',
    emoji: '🏥',
    size: [2, 2],
    coins: 5200,
    materials: 70,
    effects: { jobs: 60, income: -60, health: 14, happiness: 6 },
    needsLevel: 7,
    note: 'Notaufnahme, Rettungswagen, Landeplatz – Reichweite 14',
    look: {
      kind: 'bau',
      height: 3.2,
      wall: '#f4f6f8',
      roof: '#9aa3a8',
      accent: '#d63a2e',
      floors: 5,
      stil: {
        dach: 'flach',
        fassade: 'putz',
        fenster: 'band',
        unten: 'eingang',
        farben: ['#f4f6f8', '#eef2f4', '#f2f4ee'],
        extras: ['kreuz', 'heli', 'blaulicht', 'schild'],
        schild: '🏥',
        neon: '#ff3b30',
        koerper: { tiefe: 0.74, breite: 0.9 },
      },
    },
  },
]
