// Gewerbe – Läden, Gastronomie, Büros, Industrie. Das Schild zeigt, was drin ist;
// Markise, Leuchtschrift und Tische drehen sich mit dem Eingang zur Straße.
import type { BuildingDef } from '../catalog'

const LADENFARBEN = ['#ffe9a8', '#f8d8c0', '#dff0e4', '#e3e6f5', '#f9dfe6', '#fff1d6', '#e6f2f5']
const KLINKER = ['#b5654a', '#a85a42', '#c07a5a', '#9c5a48']
const BETON = ['#c9ccd0', '#d6d3cc', '#bfc4c9', '#d0cdc4']
const GLAS = ['#8fb3c8', '#9ec0c9', '#a9b8c9', '#8aa6b8']

export const GEWERBE: BuildingDef[] = [
  {
    id: 'kiosk',
    name: 'Kiosk',
    category: 'handel',
    emoji: '🗞️',
    size: [1, 1],
    coins: 90,
    materials: 1,
    effects: { income: 6, jobs: 1, happiness: 1 },
    note: 'Zeitung, Kaffee, Klatsch',
    look: {
      kind: 'bau',
      height: 0.7,
      wall: '#f4d35e',
      roof: '#c0392b',
      accent: '#7a2a20',
      floors: 1,
      stil: {
        dach: 'pult',
        fassade: 'putz',
        fenster: 'keine',
        unten: 'laden',
        farben: ['#f4d35e', '#7bc6cc', '#f28482', '#a0c878'],
        extras: ['schild', 'markise'],
        schild: '🗞️',
        koerper: { tiefe: 0.46, breite: 0.6 },
      },
    },
  },
  {
    id: 'baeckerei',
    name: 'Bäckerei',
    category: 'handel',
    emoji: '🥖',
    size: [1, 1],
    coins: 280,
    materials: 4,
    effects: { income: 16, jobs: 3, happiness: 2 },
    note: 'Frühmorgens duftet die ganze Straße',
    look: {
      kind: 'bau',
      height: 1.3,
      wall: '#f6e4c8',
      roof: '#a8563c',
      accent: '#8c5a2c',
      floors: 2,
      stil: {
        dach: 'sattel',
        fassade: 'putz',
        fenster: 'normal',
        unten: 'laden',
        farben: ['#f6e4c8', '#f2dcc0', '#fbeedd', '#efe0c8'],
        dachfarben: ['#a8563c', '#8c4a3a'],
        extras: ['markise', 'schild', 'schornstein'],
        vielleicht: ['tische', 'fahrrad'],
        schild: '🥖',
      },
    },
  },
  {
    id: 'eisdiele',
    name: 'Eisdiele',
    category: 'handel',
    emoji: '🍦',
    size: [1, 1],
    coins: 300,
    materials: 4,
    effects: { income: 17, jobs: 3, happiness: 3 },
    note: 'Bunte Kugeln und Tische in der Sonne',
    look: {
      kind: 'bau',
      height: 1.1,
      wall: '#f9dfe6',
      roof: '#8fd0d8',
      accent: '#d65a8a',
      floors: 1,
      stil: {
        dach: 'flach',
        fassade: 'putz',
        fenster: 'gross',
        unten: 'laden',
        farben: ['#f9dfe6', '#e3f2f5', '#fff1d6', '#e6f5e0'],
        extras: ['markise', 'schild', 'tische'],
        schild: '🍦',
      },
    },
  },
  {
    id: 'imbiss',
    name: 'Döner-Imbiss',
    category: 'handel',
    emoji: '🥙',
    size: [1, 1],
    coins: 240,
    materials: 3,
    effects: { income: 15, jobs: 2, happiness: 2 },
    note: 'Mit alles und scharf',
    look: {
      kind: 'bau',
      height: 1.05,
      wall: '#f2e2c4',
      roof: '#6d7a86',
      accent: '#c0392b',
      floors: 1,
      stil: {
        dach: 'flach',
        fassade: 'putz',
        fenster: 'gross',
        unten: 'laden',
        farben: ['#f2e2c4', '#e8d8b8', '#f6ead6'],
        extras: ['leuchtschrift', 'schild'],
        vielleicht: ['tische', 'muell'],
        schild: '🥙',
        neon: '#ff5f5f',
      },
    },
  },
  {
    id: 'pizzeria',
    name: 'Pizzeria',
    category: 'handel',
    emoji: '🍕',
    size: [1, 1],
    coins: 380,
    materials: 5,
    effects: { income: 22, jobs: 4, happiness: 3 },
    note: 'Holzofen, rot-weiße Markise',
    look: {
      kind: 'bau',
      height: 1.35,
      wall: '#c07a5a',
      roof: '#8c3b2c',
      accent: '#1f7a3a',
      floors: 2,
      stil: {
        dach: 'sattel',
        fassade: 'ziegel',
        fenster: 'normal',
        unten: 'laden',
        farben: KLINKER,
        dachfarben: ['#8c3b2c', '#7a3a2c'],
        extras: ['markise', 'schild', 'schornstein', 'tische'],
        schild: '🍕',
      },
    },
  },
  {
    id: 'friseur',
    name: 'Friseursalon',
    category: 'handel',
    emoji: '💈',
    size: [1, 1],
    coins: 260,
    materials: 3,
    effects: { income: 13, jobs: 2, happiness: 2 },
    note: 'Schnitt, Kaffee, Neuigkeiten',
    look: {
      kind: 'bau',
      height: 1.25,
      wall: '#e3e6f5',
      roof: '#6d7a86',
      accent: '#c0392b',
      floors: 2,
      stil: {
        dach: 'flach',
        fassade: 'putz',
        fenster: 'normal',
        unten: 'laden',
        farben: LADENFARBEN,
        extras: ['schild', 'markise'],
        schild: '💈',
      },
    },
  },
  {
    id: 'apotheke',
    name: 'Apotheke',
    category: 'handel',
    emoji: '💊',
    size: [1, 1],
    coins: 420,
    materials: 5,
    effects: { income: 20, jobs: 3, happiness: 2, health: 3 },
    note: 'Das grüne Kreuz leuchtet die ganze Nacht',
    look: {
      kind: 'bau',
      height: 1.4,
      wall: '#f4f1ea',
      roof: '#5f6f7a',
      accent: '#1f9a4a',
      floors: 2,
      stil: {
        dach: 'flach',
        fassade: 'putz',
        fenster: 'normal',
        unten: 'laden',
        farben: ['#f4f1ea', '#eef4ee', '#f2efe6'],
        extras: ['kreuz', 'schild'],
        schild: '💊',
        neon: '#2ecc71',
      },
    },
  },
  {
    id: 'buchladen',
    name: 'Buchhandlung',
    category: 'handel',
    emoji: '📚',
    size: [1, 1],
    coins: 360,
    materials: 5,
    effects: { income: 14, jobs: 2, happiness: 2, education: 2 },
    note: 'Stapel bis unter die Decke',
    look: {
      kind: 'bau',
      height: 1.5,
      wall: '#d8c3a5',
      roof: '#4f5864',
      accent: '#2c5b66',
      floors: 2,
      stil: {
        dach: 'mansard',
        fassade: 'putz',
        fenster: 'bogen',
        unten: 'laden',
        farben: ['#d8c3a5', '#c8d8d0', '#e0d2bc', '#d8cfe6'],
        dachfarben: ['#4f5864', '#5a6470'],
        extras: ['schild', 'markise'],
        vielleicht: ['efeu', 'fahrrad'],
        schild: '📚',
      },
    },
  },
  {
    id: 'blumenladen',
    name: 'Blumenladen',
    category: 'handel',
    emoji: '💐',
    size: [1, 1],
    coins: 220,
    materials: 3,
    effects: { income: 12, jobs: 2, happiness: 3, environment: 2 },
    note: 'Eimer voller Farben vor der Tür',
    look: {
      kind: 'bau',
      height: 1.1,
      wall: '#e6f2e0',
      roof: '#7a5a4a',
      accent: '#3f8f52',
      floors: 1,
      stil: {
        dach: 'sattel',
        fassade: 'holz',
        fenster: 'gross',
        unten: 'laden',
        farben: ['#e6f2e0', '#f5e6ee', '#fff1d6', '#e3ecf5'],
        dachfarben: ['#7a5a4a', '#6b4a3a'],
        extras: ['schild', 'markise', 'garten'],
        schild: '💐',
      },
    },
  },
  {
    id: 'boutique',
    name: 'Modeboutique',
    category: 'handel',
    emoji: '👗',
    size: [1, 1],
    coins: 520,
    materials: 7,
    effects: { income: 28, jobs: 3, happiness: 2 },
    needsLevel: 3,
    note: 'Große Scheiben, schwarze Markise',
    look: {
      kind: 'bau',
      height: 1.6,
      wall: '#f4efe4',
      roof: '#3a3f46',
      accent: '#1c1c1c',
      floors: 2,
      stil: {
        dach: 'flach',
        fassade: 'stein',
        fenster: 'gross',
        unten: 'laden',
        farben: ['#f4efe4', '#ece6dc', '#e6e1d8', '#f2e6e6'],
        extras: ['schild', 'markise'],
        schild: '👗',
      },
    },
  },
  {
    id: 'werkstatt',
    name: 'Autowerkstatt',
    category: 'handel',
    emoji: '🔧',
    size: [1, 1],
    coins: 480,
    materials: 8,
    effects: { income: 24, jobs: 5, environment: -2 },
    needsLevel: 2,
    note: 'Rolltor, Hebebühne, Ölgeruch',
    look: {
      kind: 'bau',
      height: 1.25,
      wall: '#c9ccd0',
      roof: '#6d7a86',
      accent: '#2c3e50',
      floors: 1,
      stil: {
        dach: 'pult',
        fassade: 'blech',
        fenster: 'klein',
        unten: 'tor',
        farben: ['#c9ccd0', '#b8c4cc', '#d6d3cc', '#c4b8a8'],
        extras: ['schild'],
        vielleicht: ['wracks', 'muell'],
        schild: '🔧',
      },
    },
  },
  {
    id: 'bar',
    name: 'Bar',
    category: 'handel',
    emoji: '🍸',
    size: [1, 1],
    coins: 460,
    materials: 6,
    effects: { income: 26, jobs: 3, happiness: 3, crime: 1 },
    needsLevel: 3,
    note: 'Gedämpftes Licht und Neon im Fenster',
    look: {
      kind: 'bau',
      height: 1.35,
      wall: '#3a3040',
      roof: '#2a2530',
      accent: '#c9a04a',
      floors: 2,
      stil: {
        dach: 'flach',
        fassade: 'ziegel',
        fenster: 'normal',
        unten: 'laden',
        farben: ['#3a3040', '#40353a', '#2f3a40', '#4a3a3a'],
        extras: ['leuchtschrift', 'schild'],
        schild: '🍸',
        neon: '#ff4fd8',
      },
    },
  },
  {
    id: 'tankstelle',
    name: 'Tankstelle',
    category: 'handel',
    emoji: '⛽',
    size: [2, 1],
    coins: 900,
    materials: 13,
    effects: { income: 45, jobs: 5, environment: -3 },
    needsLevel: 3,
    note: 'Säulen unter dem Dach, Shop dahinter',
    look: {
      kind: 'bau',
      height: 1,
      wall: '#f4f4f4',
      roof: '#d63a2e',
      accent: '#d63a2e',
      floors: 1,
      stil: {
        dach: 'flach',
        fassade: 'putz',
        fenster: 'gross',
        unten: 'laden',
        farben: ['#f4f4f4', '#eef2f5'],
        extras: ['zapfsaeulen', 'schild'],
        schild: '⛽',
        neon: '#d63a2e',
        koerper: { tiefe: 0.38, breite: 0.55 },
      },
    },
  },
  {
    id: 'fitness',
    name: 'Fitnessstudio',
    category: 'handel',
    emoji: '🏋️',
    size: [2, 1],
    coins: 900,
    materials: 13,
    effects: { income: 40, jobs: 6, happiness: 4 },
    needsLevel: 4,
    note: 'Laufbänder hinter großen Scheiben',
    look: {
      kind: 'bau',
      height: 1.6,
      wall: '#2c3e50',
      roof: '#4a5562',
      accent: '#e67e22',
      floors: 2,
      stil: {
        dach: 'flach',
        fassade: 'blech',
        fenster: 'band',
        unten: 'eingang',
        farben: ['#2c3e50', '#34495e', '#3d4a5c', '#4a3a5c'],
        extras: ['leuchtschrift', 'schild'],
        schild: '🏋️',
        neon: '#ff9f43',
      },
    },
  },
  {
    id: 'supermarkt',
    name: 'Supermarkt',
    category: 'handel',
    emoji: '🛒',
    size: [2, 2],
    coins: 1600,
    materials: 22,
    effects: { income: 90, jobs: 24, happiness: 3 },
    needsLevel: 4,
    note: 'Großer Laden mit Parkplatz davor',
    look: {
      kind: 'bau',
      height: 1.3,
      wall: '#eef2f5',
      roof: '#9aa3a8',
      accent: '#e74c3c',
      floors: 1,
      stil: {
        dach: 'flach',
        fassade: 'blech',
        fenster: 'band',
        unten: 'laden',
        farben: ['#eef2f5', '#f5f0e6', '#e8f0e8'],
        extras: ['parkplatz', 'leuchtschrift', 'schild'],
        schild: '🛒',
        neon: '#e74c3c',
        koerper: { tiefe: 0.55, breite: 0.9 },
      },
    },
  },
  {
    id: 'geldhaus',
    name: 'Bankfiliale',
    category: 'handel',
    emoji: '🏦',
    size: [1, 1],
    coins: 1200,
    materials: 16,
    effects: { income: 50, jobs: 8, happiness: 1 },
    needsLevel: 5,
    note: 'Säulen, Marmor, Geldautomat',
    look: {
      kind: 'bau',
      height: 1.9,
      wall: '#ece6d8',
      roof: '#5a6470',
      accent: '#1f3a5a',
      floors: 2,
      stil: {
        dach: 'flach',
        fassade: 'stein',
        fenster: 'bogen',
        unten: 'eingang',
        farben: ['#ece6d8', '#e6e0d0', '#f0ebe0'],
        extras: ['saeulen', 'schild', 'fahnenmast'],
        schild: '🏦',
      },
    },
  },
  {
    id: 'kino',
    name: 'Kino',
    category: 'handel',
    emoji: '🎬',
    size: [2, 1],
    coins: 1700,
    materials: 24,
    effects: { income: 85, jobs: 12, happiness: 8 },
    needsLevel: 6,
    note: 'Leuchtschrift, Popcorn, großer Saal',
    look: {
      kind: 'bau',
      height: 1.9,
      wall: '#5a2a3a',
      roof: '#3a2030',
      accent: '#f4d35e',
      floors: 1,
      stil: {
        dach: 'flach',
        fassade: 'putz',
        fenster: 'keine',
        unten: 'eingang',
        farben: ['#5a2a3a', '#2a3a5a', '#3a2a5a', '#5a3a2a'],
        extras: ['leuchtschrift', 'schild', 'markise'],
        schild: '🎬',
        neon: '#f4d35e',
      },
    },
  },
  {
    id: 'club',
    name: 'Nachtclub',
    category: 'handel',
    emoji: '🪩',
    size: [2, 1],
    coins: 1500,
    materials: 20,
    effects: { income: 80, jobs: 12, happiness: 5, crime: 3 },
    needsLevel: 6,
    note: 'Bässe bis zum Morgen',
    look: {
      kind: 'bau',
      height: 1.5,
      wall: '#1f1a2e',
      roof: '#141020',
      accent: '#b04fff',
      floors: 1,
      stil: {
        dach: 'flach',
        fassade: 'blech',
        fenster: 'keine',
        unten: 'eingang',
        farben: ['#1f1a2e', '#2a1a2a', '#1a2a2e'],
        extras: ['leuchtschrift', 'schild', 'graffiti'],
        schild: '🪩',
        neon: '#b04fff',
      },
    },
  },
  {
    id: 'autohaus',
    name: 'Autohaus',
    category: 'handel',
    emoji: '🚘',
    size: [2, 1],
    coins: 1400,
    materials: 20,
    effects: { income: 70, jobs: 10 },
    needsLevel: 6,
    note: 'Glänzende Wagen hinter Glas und auf dem Hof',
    look: {
      kind: 'bau',
      height: 1.4,
      wall: '#9ec0c9',
      roof: '#e6e9ec',
      accent: '#1f3a5a',
      floors: 1,
      stil: {
        dach: 'flach',
        fassade: 'glas',
        fenster: 'gross',
        unten: 'laden',
        farben: GLAS,
        extras: ['parkplatz', 'schild', 'fahnenmast'],
        schild: '🚘',
        koerper: { tiefe: 0.5, breite: 0.85 },
      },
    },
  },
  {
    id: 'lagerhalle',
    name: 'Lagerhalle',
    category: 'handel',
    emoji: '📦',
    size: [2, 1],
    coins: 1100,
    materials: 16,
    effects: { income: 35, jobs: 25, environment: -2 },
    needsLevel: 4,
    note: 'Laderampe, Lkw, Paletten',
    look: {
      kind: 'bau',
      height: 1.5,
      wall: '#b8c4cc',
      roof: '#8e949a',
      accent: '#2c5b8c',
      floors: 1,
      stil: {
        dach: 'pult',
        fassade: 'blech',
        fenster: 'klein',
        unten: 'tor',
        farben: ['#b8c4cc', '#c9ccd0', '#aeb8a8', '#c4b8a8', '#a8b8c8'],
        extras: ['schild'],
        vielleicht: ['graffiti'],
        schild: '📦',
      },
    },
  },
  {
    id: 'buero',
    name: 'Bürohaus',
    category: 'handel',
    emoji: '🏢',
    size: [2, 1],
    coins: 1800,
    materials: 26,
    effects: { income: 60, jobs: 40 },
    needsLevel: 5,
    note: 'Fensterbänder und Kaffeeküchen',
    look: {
      kind: 'bau',
      height: 2.8,
      wall: '#d6d3cc',
      roof: '#8e949a',
      accent: '#34495e',
      floors: 5,
      stil: {
        dach: 'flach',
        fassade: 'putz',
        fenster: 'band',
        unten: 'eingang',
        farben: BETON,
        extras: ['antenne'],
        vielleicht: ['solar'],
      },
    },
  },
  {
    id: 'fabrik',
    name: 'Fabrik',
    category: 'handel',
    emoji: '🏭',
    size: [2, 2],
    coins: 2600,
    materials: 36,
    effects: { income: 110, jobs: 80, environment: -10, happiness: -3 },
    needsLevel: 6,
    note: 'Sheddach, Schlot, viele Arbeitsplätze',
    look: {
      kind: 'bau',
      height: 1.7,
      wall: '#a85a42',
      roof: '#5a5f68',
      accent: '#3a3f46',
      floors: 2,
      stil: {
        dach: 'saege',
        fassade: 'ziegel',
        fenster: 'gross',
        unten: 'tor',
        farben: KLINKER,
        dachfarben: ['#5a5f68', '#4a4f58'],
        extras: ['schlot', 'rauch'],
        vielleicht: ['graffiti'],
      },
    },
  },
  {
    id: 'brauerei',
    name: 'Brauerei',
    category: 'handel',
    emoji: '🍺',
    size: [2, 2],
    coins: 2900,
    materials: 40,
    effects: { income: 130, jobs: 40, happiness: 4, environment: -4 },
    needsLevel: 8,
    note: 'Kupferkessel und ein Biergarten',
    look: {
      kind: 'bau',
      height: 2,
      wall: '#c07a5a',
      roof: '#6b3f30',
      accent: '#b87333',
      floors: 2,
      stil: {
        dach: 'sattel',
        fassade: 'ziegel',
        fenster: 'bogen',
        unten: 'tor',
        farben: KLINKER,
        dachfarben: ['#6b3f30', '#5a3a2c'],
        extras: ['kessel', 'schlot', 'tische', 'schild'],
        schild: '🍺',
        koerper: { tiefe: 0.66, breite: 0.9 },
      },
    },
  },
  {
    id: 'einkaufszentrum',
    name: 'Einkaufszentrum',
    category: 'handel',
    emoji: '🛍️',
    size: [2, 2],
    coins: 4800,
    materials: 64,
    effects: { income: 220, jobs: 70, happiness: 6 },
    needsLevel: 9,
    note: 'Hundert Läden unter einem Glasdach',
    look: {
      kind: 'bau',
      height: 2.2,
      wall: '#eef2f5',
      roof: '#c9d4dc',
      accent: '#8e44ad',
      floors: 2,
      stil: {
        dach: 'flach',
        fassade: 'glas',
        fenster: 'band',
        unten: 'eingang',
        farben: ['#dfe8ee', '#e8eef0', '#e0e6ea'],
        extras: ['leuchtschrift', 'schild', 'parkplatz'],
        schild: '🛍️',
        neon: '#b04fff',
        koerper: { tiefe: 0.62, breite: 0.92 },
      },
    },
  },
  {
    id: 'buroturm',
    name: 'Bürohochhaus',
    category: 'handel',
    emoji: '🏙️',
    size: [2, 2],
    coins: 5200,
    materials: 72,
    effects: { income: 180, jobs: 120 },
    needsLevel: 10,
    note: 'Glas und Stahl, zwölf Etagen voller Schreibtische',
    look: {
      kind: 'bau',
      height: 6.4,
      wall: '#8aa6b8',
      roof: '#5f6f7a',
      accent: '#1f2d3a',
      floors: 12,
      stil: {
        dach: 'flach',
        fassade: 'glas',
        fenster: 'band',
        unten: 'eingang',
        farben: GLAS,
        extras: ['antenne', 'heli'],
        koerper: { tiefe: 0.78, breite: 0.78 },
      },
    },
  },
]
