// Gebäude aus den Lernwelten: Was man in einem Kurs lernt, wird in der Stadt sichtbar.
// Freigeschaltet werden sie über das Wissen im jeweiligen Fach (src/knowledge.ts).
import type { BuildingDef } from '../catalog'

export const LERNWELTEN: BuildingDef[] = [
  // 🇩🇪 Deutsch
  {
    id: 'sprachakademie',
    name: 'Sprachakademie',
    category: 'bildung',
    emoji: '🏫',
    size: [2, 1],
    coins: 2200,
    materials: 30,
    effects: { education: 18, happiness: 7, jobs: 10, income: 30 },
    needsLevel: 4,
    needs: [{ domain: 'deutsch', level: 3 }],
    note: 'Wächst aus dem, was du im Deutschkurs gelernt hast',
    look: {
      kind: 'bau',
      height: 1.9,
      wall: '#efe4cf',
      roof: '#5b4a6e',
      accent: '#a8781c',
      floors: 3,
      stil: {
        dach: 'mansard',
        fassade: 'stein',
        fenster: 'bogen',
        unten: 'eingang',
        farben: ['#efe4cf', '#e8dcc4', '#f2e9d6'],
        dachfarben: ['#5b4a6e', '#4f5864'],
        extras: ['saeulen', 'fahnenmast', 'schild'],
        vielleicht: ['efeu', 'fahrrad'],
        schild: '📚',
      },
    },
  },
  {
    id: 'grosse_sprachakademie',
    name: 'Große Sprachakademie',
    category: 'bildung',
    emoji: '🏛️',
    size: [2, 2],
    coins: 7400,
    materials: 110,
    effects: { education: 55, happiness: 16, jobs: 34, income: 120 },
    needsLevel: 10,
    needs: [{ domain: 'deutsch', level: 8 }],
    note: 'Das Wahrzeichen für alle, die Deutsch meisterhaft beherrschen',
    look: {
      kind: 'bau',
      height: 2.6,
      wall: '#f3ead6',
      roof: '#3f5a52',
      accent: '#a8781c',
      floors: 4,
      stil: {
        dach: 'walm',
        fassade: 'stein',
        fenster: 'bogen',
        unten: 'eingang',
        farben: ['#f3ead6', '#efe2c8'],
        dachfarben: ['#3f5a52', '#4f5864'],
        extras: ['saeulen', 'fahnenmast', 'schild', 'gaube'],
        vielleicht: ['efeu'],
        schild: '🖋️',
        koerper: { tiefe: 0.7, breite: 0.86 },
      },
    },
  },
  // 🇬🇧 Englisch
  {
    id: 'internationale_schule',
    name: 'Internationale Schule',
    category: 'bildung',
    emoji: '🌐',
    size: [2, 1],
    coins: 2400,
    materials: 32,
    effects: { education: 20, happiness: 8, jobs: 12, income: 36 },
    needsLevel: 4,
    needs: [{ domain: 'englisch', level: 3 }],
    note: 'Hier lernen Kinder aus aller Welt zusammen',
    look: {
      kind: 'bau',
      height: 1.8,
      wall: '#eef6f6',
      roof: '#0f9d9a',
      accent: '#ff6b5a',
      floors: 3,
      stil: {
        dach: 'flach',
        fassade: 'putz',
        fenster: 'band',
        unten: 'eingang',
        farben: ['#eef6f6', '#e4f2f1', '#f3faf9'],
        dachfarben: ['#0f9d9a', '#12807e'],
        extras: ['fahnenmast', 'schild', 'solar'],
        vielleicht: ['fahrrad', 'garten'],
        schild: '🌐',
      },
    },
  },
  {
    id: 'welthaus',
    name: 'Welthaus',
    category: 'bildung',
    emoji: '🗼',
    size: [2, 2],
    coins: 7800,
    materials: 115,
    effects: { education: 58, happiness: 18, jobs: 38, income: 130 },
    needsLevel: 10,
    needs: [{ domain: 'englisch', level: 8 }],
    note: 'Treffpunkt für alle, die die Welt verstehen wollen',
    look: {
      kind: 'bau',
      height: 3.2,
      wall: '#e8f4f4',
      roof: '#0e6f6d',
      accent: '#ff6b5a',
      floors: 6,
      stil: {
        dach: 'flach',
        fassade: 'glas',
        fenster: 'band',
        unten: 'eingang',
        farben: ['#e8f4f4', '#dff0f0'],
        dachfarben: ['#0e6f6d'],
        extras: ['fahnenmast', 'schild', 'antenne', 'dachterrasse'],
        schild: '🗼',
        koerper: { tiefe: 0.72, breite: 0.88 },
      },
    },
  },
]
