// Gebäude aus den Lernwelten: Was man in einem Kurs lernt, wird in der Stadt sichtbar.
// Freigeschaltet werden sie über das Wissen im jeweiligen Fach (src/knowledge.ts).
import type { BuildingDef } from '../catalog'

export const LERNWELTEN: BuildingDef[] = [
  // 🇩🇪 Deutsch
  {
    id: 'sprachakademie',
    name: 'Sprachakademie',
    category: 'bildung',
    emoji: '🏫',
    size: [2, 1],
    coins: 2200,
    materials: 30,
    effects: { education: 18, happiness: 7, jobs: 10, income: 30 },
    needsLevel: 4,
    needs: [{ domain: 'deutsch', level: 3 }],
    note: 'Wächst aus dem, was du im Deutschkurs gelernt hast',
    look: {
      kind: 'bau',
      height: 1.9,
      wall: '#efe4cf',
      roof: '#5b4a6e',
      accent: '#a8781c',
      floors: 3,
      stil: {
        dach: 'mansard',
        fassade: 'stein',
        fenster: 'bogen',
        unten: 'eingang',
        farben: ['#efe4cf', '#e8dcc4', '#f2e9d6'],
        dachfarben: ['#5b4a6e', '#4f5864'],
        extras: ['saeulen', 'fahnenmast', 'schild'],
        vielleicht: ['efeu', 'fahrrad'],
        schild: '📚',
      },
    },
  },
  {
    id: 'grosse_sprachakademie',
    name: 'Große Sprachakademie',
    category: 'bildung',
    emoji: '🏛️',
    size: [2, 2],
    coins: 7400,
    materials: 110,
    effects: { education: 55, happiness: 16, jobs: 34, income: 120 },
    needsLevel: 10,
    needs: [{ domain: 'deutsch', level: 8 }],
    note: 'Das Wahrzeichen für alle, die Deutsch meisterhaft beherrschen',
    look: {
      kind: 'bau',
      height: 2.6,
      wall: '#f3ead6',
      roof: '#3f5a52',
      accent: '#a8781c',
      floors: 4,
      stil: {
        dach: 'walm',
        fassade: 'stein',
        fenster: 'bogen',
        unten: 'eingang',
        farben: ['#f3ead6', '#efe2c8'],
        dachfarben: ['#3f5a52', '#4f5864'],
        extras: ['saeulen', 'fahnenmast', 'schild', 'gaube'],
        vielleicht: ['efeu'],
        schild: '🖋️',
        koerper: { tiefe: 0.7, breite: 0.86 },
      },
    },
  },
  // 🇬🇧 Englisch
  {
    id: 'internationale_schule',
    name: 'Internationale Schule',
    category: 'bildung',
    emoji: '🌐',
    size: [2, 1],
    coins: 2400,
    materials: 32,
    effects: { education: 20, happiness: 8, jobs: 12, income: 36 },
    needsLevel: 4,
    needs: [{ domain: 'englisch', level: 3 }],
    note: 'Hier lernen Kinder aus aller Welt zusammen',
    look: {
      kind: 'bau',
      height: 1.8,
      wall: '#eef6f6',
      roof: '#0f9d9a',
      accent: '#ff6b5a',
      floors: 3,
      stil: {
        dach: 'flach',
        fassade: 'putz',
        fenster: 'band',
        unten: 'eingang',
        farben: ['#eef6f6', '#e4f2f1', '#f3faf9'],
        dachfarben: ['#0f9d9a', '#12807e'],
        extras: ['fahnenmast', 'schild', 'solar'],
        vielleicht: ['fahrrad', 'garten'],
        schild: '🌐',
      },
    },
  },
  {
    id: 'welthaus',
    name: 'Welthaus',
    category: 'bildung',
    emoji: '🗼',
    size: [2, 2],
    coins: 7800,
    materials: 115,
    effects: { education: 58, happiness: 18, jobs: 38, income: 130 },
    needsLevel: 10,
    needs: [{ domain: 'englisch', level: 8 }],
    note: 'Treffpunkt für alle, die die Welt verstehen wollen',
    look: {
      kind: 'bau',
      height: 3.2,
      wall: '#e8f4f4',
      roof: '#0e6f6d',
      accent: '#ff6b5a',
      floors: 6,
      stil: {
        dach: 'flach',
        fassade: 'glas',
        fenster: 'band',
        unten: 'eingang',
        farben: ['#e8f4f4', '#dff0f0'],
        dachfarben: ['#0e6f6d'],
        extras: ['fahnenmast', 'schild', 'antenne', 'dachterrasse'],
        schild: '🗼',
        koerper: { tiefe: 0.72, breite: 0.88 },
      },
    },
  },
  // 💻 IT
  {
    id: 'rechenzentrum',
    name: 'Rechenzentrum',
    category: 'handel',
    emoji: '🖥️',
    size: [2, 1],
    coins: 3200,
    materials: 46,
    effects: { education: 10, jobs: 22, income: 140, happiness: 2 },
    needsLevel: 5,
    needs: [{ domain: 'technik', level: 3 }],
    note: 'Summt leise und hält die halbe Stadt am Laufen',
    look: {
      kind: 'bau',
      height: 1.5,
      wall: '#e6ecf5',
      roof: '#2a7fd6',
      accent: '#16a36a',
      floors: 2,
      stil: {
        dach: 'flach',
        fassade: 'putz',
        fenster: 'band',
        unten: 'tor',
        farben: ['#e6ecf5', '#dde6f2'],
        dachfarben: ['#2a7fd6', '#1d5fa3'],
        extras: ['antenne', 'solar', 'schild'],
        vielleicht: ['parkplatz'],
        schild: '🖥️',
      },
    },
  },
  {
    id: 'techcampus',
    name: 'Tech-Campus',
    category: 'bildung',
    emoji: '🚀',
    size: [2, 2],
    coins: 8600,
    materials: 124,
    effects: { education: 50, jobs: 48, income: 240, happiness: 14 },
    needsLevel: 11,
    needs: [{ domain: 'technik', level: 8 }],
    note: 'Wo aus Ideen Firmen werden',
    look: {
      kind: 'bau',
      height: 2.8,
      wall: '#eaf1fb',
      roof: '#1d5fa3',
      accent: '#16a36a',
      floors: 5,
      stil: {
        dach: 'flach',
        fassade: 'glas',
        fenster: 'band',
        unten: 'eingang',
        farben: ['#eaf1fb', '#e1ebf8'],
        dachfarben: ['#1d5fa3'],
        extras: ['solar', 'antenne', 'schild', 'dachterrasse'],
        vielleicht: ['fahrrad', 'garten'],
        schild: '🚀',
        koerper: { tiefe: 0.72, breite: 0.86 },
      },
    },
  },
  // 🏦 Banking
  {
    id: 'sparkasse',
    name: 'Bürgerbank',
    category: 'handel',
    emoji: '🏦',
    size: [1, 1],
    coins: 2600,
    materials: 34,
    effects: { happiness: 6, jobs: 14, income: 95 },
    needsLevel: 4,
    needs: [{ domain: 'finanzen', level: 3 }],
    note: 'Wo die Leute ihr Geld verstehen, wächst der Handel',
    look: {
      kind: 'bau',
      height: 1.7,
      wall: '#f2f6f3',
      roof: '#0f6b50',
      accent: '#0e2a47',
      floors: 2,
      stil: {
        dach: 'flach',
        fassade: 'stein',
        fenster: 'gross',
        unten: 'eingang',
        farben: ['#f2f6f3', '#e8efe9'],
        dachfarben: ['#0f6b50', '#0e2a47'],
        extras: ['saeulen', 'schild', 'leuchtschrift'],
        vielleicht: ['briefkasten'],
        schild: '🏦',
      },
    },
  },
  {
    id: 'finanzzentrum',
    name: 'Finanzzentrum',
    category: 'handel',
    emoji: '🏙️',
    size: [2, 2],
    coins: 9200,
    materials: 130,
    effects: { happiness: 10, jobs: 60, income: 320 },
    needsLevel: 11,
    needs: [{ domain: 'finanzen', level: 8 }],
    note: 'Der Turm, in dem die Zahlen der ganzen Stadt zusammenlaufen',
    look: {
      kind: 'bau',
      height: 3.6,
      wall: '#e9f1ee',
      roof: '#0b3b2e',
      accent: '#0f6b50',
      floors: 8,
      stil: {
        dach: 'flach',
        fassade: 'glas',
        fenster: 'band',
        unten: 'eingang',
        farben: ['#e9f1ee', '#dfeae6'],
        dachfarben: ['#0b3b2e'],
        extras: ['antenne', 'schild', 'dachterrasse'],
        schild: '📈',
        koerper: { tiefe: 0.7, breite: 0.82 },
      },
    },
  },
  // 🇫🇷 Französisch
  {
    id: 'sprachcafe',
    name: 'Sprachcafé',
    category: 'bildung',
    emoji: '☕',
    size: [1, 1],
    coins: 1800,
    materials: 24,
    effects: { education: 12, happiness: 12, jobs: 8, income: 40 },
    needsLevel: 3,
    needs: [{ domain: 'franzoesisch', level: 3 }],
    note: 'Hier wird nur in der Fremdsprache bestellt – und geredet',
    look: {
      kind: 'bau',
      height: 1.3,
      wall: '#fdf3e6',
      roof: '#1f3a68',
      accent: '#d6456b',
      floors: 2,
      stil: {
        dach: 'mansard',
        fassade: 'putz',
        fenster: 'bogen',
        unten: 'laden',
        farben: ['#fdf3e6', '#f8e7d6', '#fff8ef'],
        dachfarben: ['#1f3a68', '#2a4a7c'],
        extras: ['markise', 'schild'],
        vielleicht: ['efeu', 'fahrrad', 'tische'],
        schild: '☕',
      },
    },
  },
  {
    id: 'kulturpalast',
    name: 'Kulturpalast',
    category: 'bildung',
    emoji: '🎭',
    size: [2, 2],
    coins: 7600,
    materials: 112,
    effects: { education: 46, happiness: 30, jobs: 30, income: 110 },
    needsLevel: 10,
    needs: [{ domain: 'franzoesisch', level: 8 }],
    note: 'Theater, Lesungen, Chansons – die Stadt wird ein bisschen französisch',
    look: {
      kind: 'bau',
      height: 2.4,
      wall: '#fbf1e2',
      roof: '#24406f',
      accent: '#d6456b',
      floors: 3,
      stil: {
        dach: 'mansard',
        fassade: 'stein',
        fenster: 'bogen',
        unten: 'eingang',
        farben: ['#fbf1e2', '#f4e6d2'],
        dachfarben: ['#24406f', '#1b3054'],
        extras: ['saeulen', 'schild', 'fahnenmast', 'gaube'],
        vielleicht: ['efeu'],
        schild: '🎭',
        koerper: { tiefe: 0.68, breite: 0.84 },
      },
    },
  },
]
