// Neue Bauten: Wohnen, Gewerbe und Deko. Jedes Stück hat einen Zweck in der Stadt,
// auch wenn es schief, rund oder auf dem Kopf steht.
import type { BuildingDef, Dachform, Effects, Extra, Fassade, Fensterart, Unten } from '../catalog'

interface Bau {
  id: string
  name: string
  emoji: string
  category: 'wohnen' | 'handel' | 'schmuck' | 'natur'
  size?: [number, number]
  coins: number
  materials: number
  effects: Effects
  needsLevel?: number
  note: string
  hoehe: number
  dach: Dachform
  fassade?: Fassade
  fenster?: Fensterart
  unten?: Unten
  farben: string[]
  dachfarben?: string[]
  extras?: Extra[]
  vielleicht?: Extra[]
  schild?: string
  neon?: string
  koerper?: { tiefe: number; breite: number }
  floors?: number
}

function bau(e: Bau): BuildingDef {
  return {
    id: e.id,
    name: e.name,
    category: e.category,
    emoji: e.emoji,
    size: e.size ?? [1, 1],
    coins: e.coins,
    materials: e.materials,
    effects: e.effects,
    needsLevel: e.needsLevel,
    note: e.note,
    look: {
      kind: 'bau',
      height: e.hoehe,
      wall: e.farben[0],
      roof: e.dachfarben?.[0] ?? '#6b4a3a',
      accent: '#3a322c',
      floors: e.floors ?? Math.max(1, Math.round(e.hoehe)),
      stil: {
        dach: e.dach,
        fassade: e.fassade,
        fenster: e.fenster,
        unten: e.unten,
        farben: e.farben,
        dachfarben: e.dachfarben,
        extras: e.extras,
        vielleicht: e.vielleicht,
        schild: e.schild,
        neon: e.neon,
        koerper: e.koerper,
      },
    },
  }
}

interface Schmuck {
  id: string
  name: string
  emoji: string
  category?: 'schmuck' | 'natur'
  coins: number
  materials?: number
  effects: Effects
  needsLevel?: number
  note: string
  kind: BuildingDef['look']['kind']
  height: number
  wall: string
  roof: string
  accent: string
  size?: [number, number]
}

function schmuck(e: Schmuck): BuildingDef {
  return {
    id: e.id,
    name: e.name,
    category: e.category ?? 'schmuck',
    emoji: e.emoji,
    size: e.size ?? [1, 1],
    coins: e.coins,
    materials: e.materials ?? 0,
    effects: e.effects,
    needsLevel: e.needsLevel,
    note: e.note,
    look: { kind: e.kind, height: e.height, wall: e.wall, roof: e.roof, accent: e.accent },
  }
}

const HOLZ = ['#c4a574', '#d7c4a0', '#a8875c', '#e6d3b0']
const PUTZ = ['#f4ead8', '#efe2cc', '#f7f1e4', '#e7d7c0']
const KLINKER = ['#b5654a', '#a85a42', '#c07a5a', '#8d4e3c']
const BETON = ['#c9ccd0', '#d6d3cc', '#bfc4c9', '#aeb4b8']
const GLAS = ['#8fb3c8', '#9ec0c9', '#a9b8c9', '#b7d0dc']
const DACHROT = ['#a8563c', '#8c4a3a', '#b45a42']
const DACHDUNKEL = ['#3f4652', '#4b5560', '#3a3f4a']

const WOHNEN_NEU: BuildingDef[] = [
  bau({
    id: 'zirkuswagen',
    name: 'Zirkuswagen',
    emoji: '🎪',
    category: 'wohnen',
    coins: 70,
    materials: 1,
    effects: { capacity: 3, happiness: 1, klasse: 'arm' },
    note: 'Bunter Wagen, in dem jemand wirklich wohnt',
    hoehe: 0.6,
    dach: 'flach',
    fassade: 'holz',
    fenster: 'klein',
    unten: 'tuer',
    farben: ['#c0392b', '#f4d35e', '#2e86c1', '#27ae60'],
    extras: ['schild'],
    schild: '🎪',
    koerper: { tiefe: 0.42, breite: 0.86 },
  }),
  bau({
    id: 'jurte',
    name: 'Jurte',
    emoji: '⛺',
    category: 'wohnen',
    coins: 85,
    materials: 1,
    effects: { capacity: 4, happiness: 2, klasse: 'arm' },
    note: 'Rundes Filzzelt, schnell ein Zuhause',
    hoehe: 0.7,
    dach: 'zelt',
    fassade: 'holz',
    fenster: 'klein',
    unten: 'tuer',
    farben: HOLZ,
    dachfarben: ['#8c6239', '#6e4c2c'],
    extras: ['schild'],
    schild: '⛺',
    koerper: { tiefe: 0.72, breite: 0.72 },
  }),
  bau({
    id: 'iglu',
    name: 'Iglu',
    emoji: '🧊',
    category: 'wohnen',
    coins: 90,
    materials: 1,
    effects: { capacity: 3, happiness: 1, environment: 1, klasse: 'arm' },
    note: 'Kuppel aus Schneeblöcken, kühl und ruhig',
    hoehe: 0.65,
    dach: 'zelt',
    fassade: 'stein',
    fenster: 'keine',
    unten: 'tuer',
    farben: ['#eef5f8', '#d5e6ee', '#f7fbfd'],
    dachfarben: ['#dfeaf0', '#c5d8e4'],
    koerper: { tiefe: 0.7, breite: 0.7 },
  }),
  bau({
    id: 'erdhoehle',
    name: 'Erdhöhle',
    emoji: '🕳️',
    category: 'wohnen',
    coins: 140,
    materials: 2,
    effects: { capacity: 5, happiness: 1, environment: 2, klasse: 'arm' },
    note: 'Halb im Hang, warm im Winter, still im Sommer',
    hoehe: 0.55,
    dach: 'flach',
    fassade: 'stein',
    fenster: 'klein',
    unten: 'tuer',
    farben: ['#8d7b66', '#a08b72', '#6f6256'],
    extras: ['garten', 'efeu'],
    koerper: { tiefe: 0.5, breite: 0.8 },
  }),
  bau({
    id: 'hausboot',
    name: 'Hausboot',
    emoji: '🚢',
    category: 'wohnen',
    coins: 260,
    materials: 3,
    effects: { capacity: 4, happiness: 3, environment: 1, klasse: 'mittel' },
    note: 'Wohnt auf dem Wasser, der Steg ist die Haustür',
    hoehe: 0.8,
    dach: 'pult',
    fassade: 'holz',
    fenster: 'normal',
    unten: 'tuer',
    farben: ['#3d6f8c', '#c45c4a', '#e6d3b0', '#2f6b5a'],
    dachfarben: ['#f4f1ea', '#d9d3c6'],
    extras: ['schild'],
    vielleicht: ['fahrrad'],
    schild: '⚓',
    koerper: { tiefe: 0.46, breite: 0.88 },
  }),
  bau({
    id: 'baumhaus',
    name: 'Baumhaus',
    emoji: '🌳',
    category: 'wohnen',
    coins: 220,
    materials: 3,
    effects: { capacity: 3, happiness: 4, environment: 2, klasse: 'mittel' },
    note: 'Eine Stube in der Krone, die Leiter ist der Aufgang',
    hoehe: 1.4,
    dach: 'sattel',
    fassade: 'holz',
    fenster: 'klein',
    unten: 'tuer',
    farben: HOLZ,
    dachfarben: DACHROT,
    extras: ['garten'],
    koerper: { tiefe: 0.48, breite: 0.55 },
  }),
  bau({
    id: 'stelzenhaus',
    name: 'Stelzenhaus',
    emoji: '🪵',
    category: 'wohnen',
    coins: 310,
    materials: 4,
    effects: { capacity: 5, happiness: 2, klasse: 'mittel' },
    note: 'Steht auf Pfählen, darunter bleibt der Boden frei',
    hoehe: 1.15,
    dach: 'pult',
    fassade: 'holz',
    fenster: 'normal',
    unten: 'tuer',
    farben: ['#d7b07a', '#c49a5a', '#e6c99a'],
    dachfarben: ['#5a6b52', '#3f4f3c'],
    extras: ['balkone'],
    koerper: { tiefe: 0.55, breite: 0.7 },
  }),
  bau({
    id: 'tinyhaus',
    name: 'Tiny House',
    emoji: '🛻',
    category: 'wohnen',
    coins: 180,
    materials: 2,
    effects: { capacity: 2, happiness: 2, environment: 1, klasse: 'mittel' },
    note: 'Ein Zimmer auf Rädern, alles hat seinen Haken',
    hoehe: 0.75,
    dach: 'pult',
    fassade: 'holz',
    fenster: 'gross',
    unten: 'tuer',
    farben: ['#f7f1e4', '#2f4f4f', '#c45c4a', '#e9c46a'],
    dachfarben: DACHDUNKEL,
    extras: ['solar'],
    vielleicht: ['fahrrad'],
    koerper: { tiefe: 0.4, breite: 0.78 },
  }),
  bau({
    id: 'reetkate',
    name: 'Reetkate',
    emoji: '🌾',
    category: 'wohnen',
    coins: 340,
    materials: 4,
    effects: { capacity: 6, happiness: 3, klasse: 'mittel' },
    note: 'Dickes Reetdach, hält Regen und Lärm draußen',
    hoehe: 1.2,
    dach: 'walm',
    fassade: 'ziegel',
    fenster: 'klein',
    unten: 'tuer',
    farben: ['#e7d3b0', '#f0e2c8'],
    dachfarben: ['#8c7a48', '#6e6238'],
    extras: ['schornstein', 'fensterlaeden'],
    vielleicht: ['garten'],
  }),
  bau({
    id: 'blockhuette',
    name: 'Blockhütte',
    emoji: '🏕️',
    category: 'wohnen',
    coins: 240,
    materials: 3,
    effects: { capacity: 5, happiness: 2, environment: 1, klasse: 'mittel' },
    note: 'Gestapelte Balken, ein Ofen, wenig Schnickschnack',
    hoehe: 1,
    dach: 'sattel',
    fassade: 'holz',
    fenster: 'klein',
    unten: 'tuer',
    farben: ['#8c5a3a', '#a56b42', '#6e4630'],
    dachfarben: ['#4a4038', '#3a322c'],
    extras: ['schornstein'],
    vielleicht: ['garten'],
  }),
  bau({
    id: 'muehlenhaus',
    name: 'Mühlenhaus',
    emoji: '🌬️',
    category: 'wohnen',
    coins: 480,
    materials: 6,
    effects: { capacity: 8, happiness: 2, klasse: 'mittel' },
    note: 'Die Flügel stehen still, drinnen wohnen Leute',
    hoehe: 1.6,
    dach: 'zelt',
    fassade: 'putz',
    fenster: 'klein',
    unten: 'tuer',
    farben: PUTZ,
    dachfarben: DACHDUNKEL,
    extras: ['schild', 'schornstein'],
    schild: '🌬️',
  }),
  bau({
    id: 'leuchtturmwache',
    name: 'Leuchtturmwärterhaus',
    emoji: '🗼',
    category: 'wohnen',
    coins: 520,
    materials: 7,
    effects: { capacity: 4, happiness: 3, klasse: 'mittel' },
    note: 'Unten die Wohnung, oben das Licht für die Schiffe',
    hoehe: 2.2,
    dach: 'zelt',
    fassade: 'putz',
    fenster: 'band',
    unten: 'tuer',
    farben: ['#f7f4ee', '#e7eef2'],
    dachfarben: ['#c0392b', '#8c2a22'],
    extras: ['fahnenmast'],
    neon: '#ffe9a8',
    koerper: { tiefe: 0.42, breite: 0.42 },
    floors: 4,
  }),
  bau({
    id: 'bahnwaerterhaus',
    name: 'Bahnwärterhaus',
    emoji: '🚥',
    category: 'wohnen',
    coins: 200,
    materials: 3,
    effects: { capacity: 4, happiness: 1, klasse: 'mittel' },
    note: 'Kleines Haus an der Strecke, der Wärter schläft neben der Schranke',
    hoehe: 0.9,
    dach: 'sattel',
    fassade: 'ziegel',
    fenster: 'klein',
    unten: 'tuer',
    farben: KLINKER,
    dachfarben: DACHROT,
    extras: ['schild'],
    schild: '🚂',
    koerper: { tiefe: 0.55, breite: 0.6 },
  }),
  bau({
    id: 'schreberlaube',
    name: 'Schreberlaube',
    emoji: '🌻',
    category: 'wohnen',
    coins: 110,
    materials: 1,
    effects: { capacity: 2, happiness: 2, environment: 2, klasse: 'arm' },
    note: 'Gartenhaus mit Kanne und Liegestuhl, manchmal auch zum Schlafen',
    hoehe: 0.7,
    dach: 'sattel',
    fassade: 'holz',
    fenster: 'klein',
    unten: 'tuer',
    farben: ['#6f8c55', '#c45c4a', '#e6d3b0', '#3d6f8c'],
    dachfarben: ['#5a4030'],
    extras: ['garten'],
    vielleicht: ['briefkasten'],
    koerper: { tiefe: 0.45, breite: 0.55 },
  }),
  bau({
    id: 'hinterhofhaus',
    name: 'Hinterhofhaus',
    emoji: '🚪',
    category: 'wohnen',
    coins: 280,
    materials: 4,
    effects: { capacity: 8, happiness: -1, klasse: 'arm' },
    note: 'Zweite Reihe, eng, dafür günstig und mitten in der Stadt',
    hoehe: 1.5,
    dach: 'flach',
    fassade: 'putz',
    fenster: 'normal',
    unten: 'tuer',
    farben: ['#cfc6b4', '#b7b0a2', '#d9d0c2'],
    extras: ['muell', 'balkone'],
    vielleicht: ['graffiti', 'satellit'],
  }),
  bau({
    id: 'lueckenbau',
    name: 'Lückenbebauung',
    emoji: '🏘️',
    category: 'wohnen',
    coins: 460,
    materials: 6,
    effects: { capacity: 12, happiness: 1, klasse: 'mittel' },
    note: 'Füllt eine schmale Lücke zwischen zwei Häusern',
    hoehe: 1.8,
    dach: 'sattel',
    fassade: 'putz',
    fenster: 'normal',
    unten: 'eingang',
    farben: PUTZ,
    dachfarben: DACHROT,
    extras: ['fensterlaeden'],
    koerper: { tiefe: 0.7, breite: 0.55 },
    floors: 3,
  }),
  bau({
    id: 'passivhaus',
    name: 'Passivhaus',
    emoji: '🔋',
    category: 'wohnen',
    coins: 640,
    materials: 8,
    effects: { capacity: 6, happiness: 3, environment: 3, klasse: 'mittel' },
    note: 'Dichte Hülle, Südverglasung, heizt sich fast von allein',
    hoehe: 1.2,
    dach: 'pult',
    fassade: 'holz',
    fenster: 'gross',
    unten: 'tuer',
    farben: ['#f7f4ee', '#dfe8e2'],
    dachfarben: DACHDUNKEL,
    extras: ['solar', 'garten'],
  }),
  bau({
    id: 'lehmhof',
    name: 'Lehmhof',
    emoji: '🏺',
    category: 'wohnen',
    coins: 390,
    materials: 5,
    effects: { capacity: 8, happiness: 2, environment: 2, klasse: 'mittel' },
    note: 'Dicke Lehmwände, im Hof ein Baum',
    hoehe: 1.1,
    dach: 'flach',
    fassade: 'putz',
    fenster: 'klein',
    unten: 'tuer',
    farben: ['#c4a574', '#d2b48c', '#b08968'],
    dachfarben: ['#a08060'],
    extras: ['garten', 'schornstein'],
  }),
  bau({
    id: 'kubushaus',
    name: 'Kubushaus',
    emoji: '⬜',
    category: 'wohnen',
    coins: 560,
    materials: 7,
    effects: { capacity: 10, happiness: 1, klasse: 'mittel' },
    note: 'Drei gestapelte Würfel, jede Wohnung hat eine Ecke',
    hoehe: 1.7,
    dach: 'flach',
    fassade: 'putz',
    fenster: 'gross',
    unten: 'eingang',
    farben: ['#f7f4ee', '#2f3e46', '#e07a5f'],
    extras: ['balkone'],
    floors: 3,
  }),
  bau({
    id: 'pilzhaus',
    name: 'Pilzhaus',
    emoji: '🍄',
    category: 'wohnen',
    coins: 300,
    materials: 4,
    needsLevel: 2,
    effects: { capacity: 4, happiness: 4, klasse: 'mittel' },
    note: 'Sieht aus wie ein Pilz, ist aber eine Wohnung mit Keller',
    hoehe: 1.1,
    dach: 'zelt',
    fassade: 'putz',
    fenster: 'klein',
    unten: 'tuer',
    farben: ['#f4e1c1', '#f7f1e4'],
    dachfarben: ['#c0392b', '#e07a5f', '#8e44ad'],
    extras: ['schild'],
    schild: '🍄',
    koerper: { tiefe: 0.62, breite: 0.62 },
  }),
  bau({
    id: 'schneckenhaus',
    name: 'Schneckenhaus',
    emoji: '🐌',
    category: 'wohnen',
    coins: 280,
    materials: 4,
    needsLevel: 2,
    effects: { capacity: 3, happiness: 4, klasse: 'mittel' },
    note: 'Spirale auf einer Etage, wenig Fläche, viel Ruhe',
    hoehe: 0.9,
    dach: 'zelt',
    fassade: 'putz',
    fenster: 'klein',
    unten: 'tuer',
    farben: ['#f3e6d0', '#e7d3b8'],
    dachfarben: ['#c4a574', '#a8875c'],
    koerper: { tiefe: 0.7, breite: 0.7 },
  }),
  bau({
    id: 'hausimhaus',
    name: 'Haus im Haus',
    emoji: '🪆',
    category: 'wohnen',
    coins: 720,
    materials: 9,
    needsLevel: 3,
    effects: { capacity: 9, happiness: 2, klasse: 'mittel' },
    note: 'Eine kleine Hütte steckt in einer größeren, zwei Wohnungen übereinander gedacht',
    hoehe: 1.8,
    dach: 'sattel',
    fassade: 'fachwerk',
    fenster: 'normal',
    unten: 'tuer',
    farben: PUTZ,
    dachfarben: DACHROT,
    extras: ['gaube', 'schornstein'],
    floors: 2,
  }),
  bau({
    id: 'turmwohnung',
    name: 'Turmwohnung',
    emoji: '🏯',
    category: 'wohnen',
    coins: 680,
    materials: 9,
    needsLevel: 3,
    effects: { capacity: 14, happiness: 1, klasse: 'mittel' },
    note: 'Sehr schmal, vier Etagen, eine Treppe für alle',
    hoehe: 2.4,
    dach: 'zelt',
    fassade: 'ziegel',
    fenster: 'klein',
    unten: 'eingang',
    farben: KLINKER,
    dachfarben: DACHDUNKEL,
    extras: ['balkone'],
    koerper: { tiefe: 0.48, breite: 0.48 },
    floors: 4,
  }),
  bau({
    id: 'spiegelhaus',
    name: 'Spiegelhaus',
    emoji: '🪞',
    category: 'wohnen',
    coins: 1600,
    materials: 16,
    needsLevel: 5,
    effects: { capacity: 6, happiness: 8, klasse: 'reich' },
    note: 'Fassade aus Spiegeln, die Straße sieht sich selbst',
    hoehe: 1.5,
    dach: 'flach',
    fassade: 'glas',
    fenster: 'gross',
    unten: 'tuer',
    farben: GLAS,
    extras: ['garten'],
    neon: '#d7eef8',
  }),
  bau({
    id: 'wasserturmloft',
    name: 'Wasserturm-Loft',
    emoji: '💧',
    category: 'wohnen',
    coins: 2100,
    materials: 22,
    needsLevel: 5,
    effects: { capacity: 8, happiness: 7, klasse: 'reich' },
    note: 'Der alte Behälter ist eine Wohnung mit Rundumblick',
    hoehe: 2.3,
    dach: 'flach',
    fassade: 'ziegel',
    fenster: 'band',
    unten: 'eingang',
    farben: KLINKER,
    dachfarben: ['#6a7380'],
    extras: ['dachterrasse', 'antenne'],
    koerper: { tiefe: 0.55, breite: 0.55 },
    floors: 4,
  }),
  bau({
    id: 'glaskuppelhaus',
    name: 'Glaskuppelhaus',
    emoji: '🫧',
    category: 'wohnen',
    coins: 2800,
    materials: 26,
    needsLevel: 7,
    effects: { capacity: 6, happiness: 9, environment: 2, klasse: 'reich' },
    note: 'Wohnt unter einer Kuppel, drinnen wächst ein Garten',
    hoehe: 1.4,
    dach: 'zelt',
    fassade: 'glas',
    fenster: 'gross',
    unten: 'tuer',
    farben: GLAS,
    dachfarben: ['#c5dde8', '#d7eef5'],
    extras: ['gewaechshaus', 'garten'],
  }),
  bau({
    id: 'raketenwohnung',
    name: 'Raketenwohnung',
    emoji: '🚀',
    category: 'wohnen',
    coins: 2400,
    materials: 24,
    needsLevel: 6,
    effects: { capacity: 5, happiness: 8, klasse: 'reich' },
    note: 'Eine ausgemusterte Stufe, senkrecht, mit Bullaugen',
    hoehe: 2.5,
    dach: 'zelt',
    fassade: 'blech',
    fenster: 'klein',
    unten: 'tuer',
    farben: ['#e8eef2', '#d0d7de'],
    dachfarben: ['#c0392b'],
    extras: ['antenne'],
    koerper: { tiefe: 0.4, breite: 0.4 },
    floors: 4,
  }),
  bau({
    id: 'ufohaus',
    name: 'UFO-Haus',
    emoji: '🛸',
    category: 'wohnen',
    coins: 4600,
    materials: 36,
    needsLevel: 6,
    effects: { capacity: 4, happiness: 14, klasse: 'reich' },
    note: 'Fliegende Untertasse auf einem Stiel, bewohnt und an die Straße angeschlossen',
    hoehe: 1.6,
    dach: 'flach',
    fassade: 'blech',
    fenster: 'band',
    unten: 'tuer',
    farben: ['#d7dde3', '#c5ced6'],
    extras: ['antenne', 'leuchtschrift'],
    neon: '#7d7fff',
    schild: '🛸',
    koerper: { tiefe: 0.7, breite: 0.7 },
  }),
  bau({
    id: 'gutshof',
    name: 'Gutshof',
    emoji: '🐴',
    category: 'wohnen',
    size: [2, 2],
    coins: 3600,
    materials: 32,
    needsLevel: 6,
    effects: { capacity: 16, happiness: 6, environment: 1, klasse: 'reich' },
    note: 'Herrenhaus mit Hof, hier wohnt die Familie und das Personal',
    hoehe: 1.6,
    dach: 'walm',
    fassade: 'putz',
    fenster: 'bogen',
    unten: 'eingang',
    farben: ['#f7f1e4', '#efe4d0'],
    dachfarben: DACHROT,
    extras: ['saeulen', 'garten', 'schornstein'],
    vielleicht: ['fahnenmast'],
  }),
  bau({
    id: 'jagdschloss',
    name: 'Jagdschloss',
    emoji: '🦌',
    category: 'wohnen',
    size: [2, 2],
    coins: 7200,
    materials: 58,
    needsLevel: 8,
    effects: { capacity: 10, happiness: 12, klasse: 'reich' },
    note: 'Kleines Schloss am Waldrand, Trophäen und Gästezimmer',
    hoehe: 1.9,
    dach: 'mansard',
    fassade: 'stein',
    fenster: 'bogen',
    unten: 'eingang',
    farben: ['#e7dcc8', '#d9cbb4'],
    dachfarben: ['#3f4652', '#5a4030'],
    extras: ['saeulen', 'fahnenmast', 'schornstein'],
  }),
]

const GEWERBE_NEU: BuildingDef[] = [
  bau({
    id: 'doener',
    name: 'Dönerladen',
    emoji: '🥙',
    category: 'handel',
    coins: 240,
    materials: 3,
    effects: { income: 8, jobs: 3, happiness: 2 },
    note: 'Spät offen, die Straße riecht nach Grill',
    hoehe: 0.9,
    dach: 'flach',
    fassade: 'putz',
    fenster: 'keine',
    unten: 'laden',
    farben: ['#f4d35e', '#e07a5f', '#f7f1e4'],
    extras: ['leuchtschrift', 'schild'],
    schild: '🥙',
    neon: '#ffd23f',
  }),
  bau({
    id: 'kaffeeroester',
    name: 'Kaffeerösterei',
    emoji: '☕',
    category: 'handel',
    coins: 420,
    materials: 5,
    effects: { income: 11, jobs: 4, happiness: 2 },
    note: 'Röstet Bohnen und verkauft sie über die Theke',
    hoehe: 1.2,
    dach: 'sattel',
    fassade: 'ziegel',
    fenster: 'bogen',
    unten: 'laden',
    farben: KLINKER,
    dachfarben: DACHDUNKEL,
    extras: ['schornstein', 'schild', 'markise'],
    schild: '☕',
  }),
  bau({
    id: 'kaeserei',
    name: 'Käserei',
    emoji: '🧀',
    category: 'handel',
    coins: 480,
    materials: 6,
    effects: { income: 12, jobs: 5, happiness: 1 },
    note: 'Reift Laibe im Keller und verkauft sie vorn',
    hoehe: 1.2,
    dach: 'sattel',
    fassade: 'putz',
    fenster: 'klein',
    unten: 'laden',
    farben: ['#f7f1e4', '#f4e1c1'],
    dachfarben: DACHROT,
    extras: ['schild', 'schornstein'],
    schild: '🧀',
  }),
  bau({
    id: 'schokomanufaktur',
    name: 'Schokoladenmanufaktur',
    emoji: '🍫',
    category: 'handel',
    coins: 640,
    materials: 7,
    effects: { income: 14, jobs: 6, happiness: 3 },
    note: 'Kleine Tafelproduktion, der Laden duftet die Gasse voll',
    hoehe: 1.3,
    dach: 'mansard',
    fassade: 'putz',
    fenster: 'bogen',
    unten: 'laden',
    farben: ['#f3e0d0', '#e7cbb8'],
    dachfarben: ['#5a3a2c'],
    extras: ['markise', 'schild', 'schornstein'],
    schild: '🍫',
  }),
  bau({
    id: 'gummibaerenwerk',
    name: 'Gummibärenwerk',
    emoji: '🧸',
    category: 'handel',
    coins: 980,
    materials: 12,
    needsLevel: 3,
    effects: { income: 20, jobs: 10, happiness: 3, environment: -1 },
    note: 'Kocht Gelatine und formt Bären, die Stadt isst mit',
    hoehe: 1.5,
    dach: 'saege',
    fassade: 'ziegel',
    fenster: 'band',
    unten: 'tor',
    farben: ['#f4d35e', '#e07a5f', '#7bc6cc'],
    dachfarben: DACHDUNKEL,
    extras: ['schlot', 'schild'],
    schild: '🧸',
    size: [2, 1],
  }),
  bau({
    id: 'imkerei',
    name: 'Imkerei',
    emoji: '🐝',
    category: 'handel',
    coins: 260,
    materials: 3,
    effects: { income: 7, jobs: 2, happiness: 2, environment: 3 },
    note: 'Kästen voller Völker, Honig für die Nachbarschaft',
    hoehe: 0.7,
    dach: 'pult',
    fassade: 'holz',
    fenster: 'keine',
    unten: 'tor',
    farben: ['#e9c46a', '#f4d35e'],
    dachfarben: ['#c4a574'],
    extras: ['schild', 'garten'],
    schild: '🐝',
    koerper: { tiefe: 0.55, breite: 0.7 },
  }),
  bau({
    id: 'pilzzucht',
    name: 'Pilzzucht',
    emoji: '🍄',
    category: 'handel',
    coins: 340,
    materials: 4,
    effects: { income: 9, jobs: 3, environment: 1 },
    note: 'Dunkle Regale, Austernpilze für die Küchen der Stadt',
    hoehe: 0.9,
    dach: 'flach',
    fassade: 'holz',
    fenster: 'dunkel',
    unten: 'tor',
    farben: ['#6f6256', '#8d7b66'],
    extras: ['schild'],
    schild: '🍄',
  }),
  bau({
    id: 'algenfarm',
    name: 'Algenfarm',
    emoji: '🟢',
    category: 'handel',
    coins: 520,
    materials: 6,
    needsLevel: 2,
    effects: { income: 11, jobs: 4, environment: 2 },
    note: 'Becken voller Grünalge, Futter und Farbstoff',
    hoehe: 0.8,
    dach: 'flach',
    fassade: 'glas',
    fenster: 'keine',
    unten: 'tor',
    farben: ['#7dcea0', '#58d68d', '#1e8449'],
    extras: ['gewaechshaus', 'schild'],
    schild: '🟢',
    neon: '#2ecc71',
  }),
  bau({
    id: 'etagenfarm',
    name: 'Etagenfarm',
    emoji: '🥬',
    category: 'handel',
    coins: 1100,
    materials: 14,
    needsLevel: 4,
    effects: { income: 18, jobs: 8, environment: 3, happiness: 1 },
    note: 'Salat in Regalen unter Lampen, erntet mitten in der Stadt',
    hoehe: 2,
    dach: 'flach',
    fassade: 'glas',
    fenster: 'band',
    unten: 'tor',
    farben: GLAS,
    extras: ['gewaechshaus', 'solar'],
    neon: '#8dffb0',
    floors: 3,
    size: [1, 1],
  }),
  bau({
    id: 'huehnerhof',
    name: 'Hühnerhof',
    emoji: '🐔',
    category: 'handel',
    coins: 300,
    materials: 3,
    effects: { income: 8, jobs: 2, happiness: 1, environment: -1 },
    note: 'Eier und Gegacker, der Stall steht hinten',
    hoehe: 0.75,
    dach: 'sattel',
    fassade: 'holz',
    fenster: 'keine',
    unten: 'tor',
    farben: ['#c45c4a', '#e6d3b0'],
    dachfarben: DACHROT,
    extras: ['garten', 'schild'],
    schild: '🐔',
  }),
  bau({
    id: 'ziegenhof',
    name: 'Ziegenhof',
    emoji: '🐐',
    category: 'handel',
    coins: 380,
    materials: 4,
    effects: { income: 9, jobs: 3, happiness: 2, environment: 1 },
    note: 'Milch und Käse, die Ziegen halten das Grün kurz',
    hoehe: 1,
    dach: 'sattel',
    fassade: 'holz',
    fenster: 'klein',
    unten: 'tor',
    farben: HOLZ,
    dachfarben: ['#6e6238'],
    extras: ['garten', 'schild'],
    schild: '🐐',
  }),
  bau({
    id: 'reitstall',
    name: 'Reitstall',
    emoji: '🐴',
    category: 'handel',
    size: [2, 1],
    coins: 860,
    materials: 10,
    needsLevel: 3,
    effects: { income: 14, jobs: 5, happiness: 4, environment: 1 },
    note: 'Boxen, Reitplatz und Unterricht am Nachmittag',
    hoehe: 1.2,
    dach: 'sattel',
    fassade: 'holz',
    fenster: 'keine',
    unten: 'tor',
    farben: ['#8c5a3a', '#a56b42'],
    dachfarben: DACHROT,
    extras: ['schild', 'garten'],
    schild: '🐴',
  }),
  bau({
    id: 'tierarzt',
    name: 'Tierarzt',
    emoji: '🐾',
    category: 'handel',
    coins: 540,
    materials: 6,
    effects: { income: 12, jobs: 4, happiness: 2 },
    note: 'Praxis für Hund, Katze und das Huhn von nebenan',
    hoehe: 1.1,
    dach: 'walm',
    fassade: 'putz',
    fenster: 'normal',
    unten: 'eingang',
    farben: ['#e7f0e4', '#f7f1e4'],
    dachfarben: ['#3d6f8c'],
    extras: ['kreuz', 'schild'],
    schild: '🐾',
  }),
  bau({
    id: 'tierheim',
    name: 'Tierheim',
    emoji: '🐕',
    category: 'handel',
    size: [2, 1],
    coins: 720,
    materials: 8,
    needsLevel: 2,
    effects: { income: 4, jobs: 5, happiness: 4, environment: 1 },
    note: 'Nimmt herrenlose Tiere auf und vermittelt sie weiter',
    hoehe: 1,
    dach: 'sattel',
    fassade: 'putz',
    fenster: 'normal',
    unten: 'eingang',
    farben: ['#f7e6c4', '#e7f0e4'],
    dachfarben: DACHROT,
    extras: ['garten', 'schild'],
    schild: '🐕',
  }),
  bau({
    id: 'katzencafe',
    name: 'Katzencafé',
    emoji: '🐱',
    category: 'handel',
    coins: 460,
    materials: 5,
    effects: { income: 11, jobs: 3, happiness: 4 },
    note: 'Kaffee trinken, Katzen zuschauen, die Katzen wohnen hier',
    hoehe: 1.1,
    dach: 'sattel',
    fassade: 'putz',
    fenster: 'gross',
    unten: 'laden',
    farben: ['#f9dfe6', '#f7f1e4', '#e7d3ee'],
    dachfarben: ['#8e6a8c'],
    extras: ['markise', 'tische', 'schild'],
    schild: '🐱',
  }),
  bau({
    id: 'tattoostudio',
    name: 'Tattoostudio',
    emoji: '🖊️',
    category: 'handel',
    coins: 380,
    materials: 4,
    effects: { income: 10, jobs: 2, happiness: 1 },
    note: 'Nadel und Farbe, Termine auf Wochen im Voraus',
    hoehe: 1,
    dach: 'flach',
    fassade: 'putz',
    fenster: 'dunkel',
    unten: 'laden',
    farben: ['#2c3e50', '#1f2a36'],
    extras: ['leuchtschrift', 'graffiti', 'schild'],
    schild: '🖊️',
    neon: '#e056fd',
  }),
  bau({
    id: 'schneiderei',
    name: 'Schneiderei',
    emoji: '🧵',
    category: 'handel',
    coins: 320,
    materials: 4,
    effects: { income: 9, jobs: 3, happiness: 1 },
    note: 'Ändert Hosen und näht, was es so nicht gibt',
    hoehe: 1.1,
    dach: 'sattel',
    fassade: 'putz',
    fenster: 'normal',
    unten: 'laden',
    farben: ['#f7f1e4', '#e7d3ee'],
    dachfarben: DACHROT,
    extras: ['schild', 'markise'],
    schild: '🧵',
  }),
  bau({
    id: 'uhrmacher',
    name: 'Uhrmacher',
    emoji: '⌚',
    category: 'handel',
    coins: 400,
    materials: 4,
    effects: { income: 10, jobs: 2, happiness: 1 },
    note: 'Richtet Zahnräder, die Stadt kommt pünktlich',
    hoehe: 1,
    dach: 'sattel',
    fassade: 'fachwerk',
    fenster: 'klein',
    unten: 'laden',
    farben: PUTZ,
    dachfarben: DACHDUNKEL,
    extras: ['schild'],
    schild: '⌚',
    koerper: { tiefe: 0.55, breite: 0.6 },
  }),
  bau({
    id: 'toepferei',
    name: 'Töpferei',
    emoji: '🏺',
    category: 'handel',
    coins: 300,
    materials: 4,
    effects: { income: 8, jobs: 2, happiness: 2 },
    note: 'Dreht Schüsseln und brennt sie im Ofen hinterm Haus',
    hoehe: 1,
    dach: 'sattel',
    fassade: 'ziegel',
    fenster: 'bogen',
    unten: 'laden',
    farben: ['#c4a574', '#a8875c'],
    dachfarben: DACHROT,
    extras: ['schornstein', 'schild'],
    schild: '🏺',
  }),
  bau({
    id: 'glasblaeserei',
    name: 'Glasbläserei',
    emoji: '🔥',
    category: 'handel',
    coins: 560,
    materials: 7,
    needsLevel: 2,
    effects: { income: 13, jobs: 4, happiness: 2, environment: -1 },
    note: 'Ofen und Pfeife, daraus werden Kugeln und Karaffen',
    hoehe: 1.2,
    dach: 'pult',
    fassade: 'ziegel',
    fenster: 'gross',
    unten: 'tor',
    farben: KLINKER,
    dachfarben: DACHDUNKEL,
    extras: ['schlot', 'rauch', 'schild'],
    schild: '🔥',
  }),
  bau({
    id: 'schmiede',
    name: 'Schmiede',
    emoji: '🔨',
    category: 'handel',
    coins: 440,
    materials: 6,
    effects: { income: 11, jobs: 3, happiness: 1 },
    note: 'Amboss und Esse, Beschläge, Gitter, hin und wieder ein Messer',
    hoehe: 1.1,
    dach: 'sattel',
    fassade: 'stein',
    fenster: 'klein',
    unten: 'tor',
    farben: ['#6f6256', '#4a4038'],
    dachfarben: DACHDUNKEL,
    extras: ['schornstein', 'rauch', 'schild'],
    schild: '🔨',
  }),
  bau({
    id: 'saegewerk',
    name: 'Sägewerk',
    emoji: '🪵',
    category: 'handel',
    size: [2, 1],
    coins: 920,
    materials: 8,
    needsLevel: 3,
    effects: { income: 16, jobs: 8, environment: -2, ziegel: 3 },
    note: 'Schneidet Stämme zu Balken, die Baustellen holen sie ab',
    hoehe: 1.3,
    dach: 'pult',
    fassade: 'holz',
    fenster: 'keine',
    unten: 'tor',
    farben: ['#a56b42', '#8c5a3a'],
    dachfarben: ['#5a4030'],
    extras: ['schild', 'parkplatz'],
    schild: '🪵',
  }),
  bau({
    id: 'recyclinghof',
    name: 'Recyclinghof',
    emoji: '♻️',
    category: 'handel',
    size: [2, 1],
    coins: 780,
    materials: 6,
    needsLevel: 2,
    effects: { income: 8, jobs: 6, environment: 4, ziegel: 4 },
    note: 'Sortiert, was die Stadt wegwirft, und macht wieder Baustoff daraus',
    hoehe: 0.9,
    dach: 'flach',
    fassade: 'blech',
    fenster: 'keine',
    unten: 'tor',
    farben: ['#3d9b8f', '#2e86c1', '#f4d35e'],
    extras: ['muell', 'schild', 'parkplatz'],
    schild: '♻️',
  }),
  bau({
    id: 'klaerwerk',
    name: 'Klärwerk',
    emoji: '🚰',
    category: 'handel',
    size: [2, 2],
    coins: 1600,
    materials: 18,
    needsLevel: 4,
    effects: { income: 8, jobs: 8, environment: 6, happiness: -2 },
    note: 'Reinigt das Abwasser. Es riecht, dafür bleibt der Rest der Stadt sauber',
    hoehe: 1.1,
    dach: 'flach',
    fassade: 'platte',
    fenster: 'band',
    unten: 'tor',
    farben: BETON,
    extras: ['kessel', 'schlot', 'gitter'],
  }),
  bau({
    id: 'biogasanlage',
    name: 'Biogasanlage',
    emoji: '🫧',
    category: 'handel',
    size: [2, 1],
    coins: 1200,
    materials: 14,
    needsLevel: 4,
    effects: { income: 14, jobs: 5, environment: 2, ziegel: 2 },
    note: 'Vergärt Abfall zu Gas und verkauft die Wärme',
    hoehe: 1.3,
    dach: 'zelt',
    fassade: 'blech',
    fenster: 'keine',
    unten: 'tor',
    farben: ['#7dcea0', '#58d68d'],
    extras: ['kessel', 'schlot'],
    koerper: { tiefe: 0.7, breite: 0.8 },
  }),
  bau({
    id: 'windrad',
    name: 'Windrad',
    emoji: '🌀',
    category: 'handel',
    coins: 1400,
    materials: 16,
    needsLevel: 3,
    effects: { income: 12, jobs: 1, environment: 4 },
    note: 'Verkauft Strom, solange es zieht',
    hoehe: 2.6,
    dach: 'flach',
    fassade: 'blech',
    fenster: 'keine',
    unten: 'tuer',
    farben: ['#f7f4ee', '#d7dde3'],
    extras: ['antenne'],
    koerper: { tiefe: 0.28, breite: 0.28 },
    floors: 1,
  }),
  bau({
    id: 'solarfeld',
    name: 'Solarfeld',
    emoji: '☀️',
    category: 'handel',
    size: [2, 1],
    coins: 1100,
    materials: 10,
    needsLevel: 3,
    effects: { income: 11, jobs: 2, environment: 5 },
    note: 'Reihen von Modulen, der Strom geht ins Netz',
    hoehe: 0.35,
    dach: 'pult',
    fassade: 'blech',
    fenster: 'keine',
    unten: 'tor',
    farben: ['#1f3a5f', '#16324f'],
    dachfarben: ['#2e86c1', '#1a5276'],
    extras: ['solar'],
    koerper: { tiefe: 0.8, breite: 0.9 },
  }),
  bau({
    id: 'drohnenhalle',
    name: 'Drohnenhalle',
    emoji: '📦',
    category: 'handel',
    coins: 880,
    materials: 10,
    needsLevel: 4,
    effects: { income: 15, jobs: 6, happiness: 1, environment: -1 },
    note: 'Startet Pakete über die Dächer, wenn die Straße voll ist',
    hoehe: 1.2,
    dach: 'flach',
    fassade: 'blech',
    fenster: 'band',
    unten: 'tor',
    farben: BETON,
    extras: ['heli', 'antenne', 'schild'],
    schild: '📦',
  }),
  bau({
    id: 'tonstudio',
    name: 'Tonstudio',
    emoji: '🎙️',
    category: 'handel',
    coins: 620,
    materials: 7,
    effects: { income: 12, jobs: 3, happiness: 2, education: 1 },
    note: 'Gedämmte Räume, hier entstehen die Lieder der Stadt',
    hoehe: 1.1,
    dach: 'flach',
    fassade: 'putz',
    fenster: 'dunkel',
    unten: 'eingang',
    farben: ['#2c3e50', '#3d4f63'],
    extras: ['leuchtschrift', 'schild'],
    schild: '🎙️',
    neon: '#ff6b6b',
  }),
  bau({
    id: 'escaperoom',
    name: 'Escape Room',
    emoji: '🔐',
    category: 'handel',
    coins: 540,
    materials: 6,
    needsLevel: 2,
    effects: { income: 13, jobs: 3, happiness: 3 },
    note: 'Gruppen sperren sich eine Stunde ein und zahlen dafür',
    hoehe: 1.2,
    dach: 'flach',
    fassade: 'putz',
    fenster: 'dunkel',
    unten: 'eingang',
    farben: ['#2c3e50', '#6c3483'],
    extras: ['leuchtschrift', 'schild', 'gitter'],
    schild: '🔐',
    neon: '#f4d35e',
  }),
  bau({
    id: 'kletterhalle',
    name: 'Kletterhalle',
    emoji: '🧗',
    category: 'handel',
    size: [2, 1],
    coins: 980,
    materials: 12,
    needsLevel: 3,
    effects: { income: 14, jobs: 5, happiness: 5 },
    note: 'Hohe Wände mit Griffen, nach der Arbeit statt aufs Sofa',
    hoehe: 2.2,
    dach: 'flach',
    fassade: 'platte',
    fenster: 'band',
    unten: 'eingang',
    farben: ['#dfe6ea', '#f4d35e'],
    extras: ['schild'],
    schild: '🧗',
    floors: 2,
  }),
  bau({
    id: 'schwimmbad',
    name: 'Schwimmbad',
    emoji: '🏊',
    category: 'handel',
    size: [2, 2],
    coins: 1800,
    materials: 20,
    needsLevel: 4,
    effects: { income: 16, jobs: 8, happiness: 8 },
    note: 'Bahnenschwimmen und Planschen, die Stadt bleibt in Bewegung',
    hoehe: 1.2,
    dach: 'flach',
    fassade: 'putz',
    fenster: 'band',
    unten: 'eingang',
    farben: ['#5dade2', '#d6eaf8', '#f7f4ee'],
    extras: ['schild', 'fahnenmast'],
    schild: '🏊',
  }),
  bau({
    id: 'riesenrad',
    name: 'Riesenrad',
    emoji: '🎡',
    category: 'handel',
    size: [2, 2],
    coins: 2400,
    materials: 26,
    needsLevel: 5,
    effects: { income: 22, jobs: 8, happiness: 10 },
    note: 'Dreht sich am Abend, wer oben sitzt, sieht die ganze Stadt',
    hoehe: 2.8,
    dach: 'flach',
    fassade: 'blech',
    fenster: 'keine',
    unten: 'eingang',
    farben: ['#f4d35e', '#e07a5f', '#5dade2'],
    extras: ['leuchtschrift', 'fahnenmast'],
    neon: '#ffd23f',
    schild: '🎡',
  }),
  bau({
    id: 'kuriositaeten',
    name: 'Kuriositätenkabinett',
    emoji: '🧿',
    category: 'handel',
    coins: 700,
    materials: 8,
    needsLevel: 4,
    effects: { income: 12, jobs: 3, happiness: 5, education: 4 },
    note: 'Sammelt, was nirgends sonst hinpasst, und zeigt es gegen Eintritt',
    hoehe: 1.4,
    dach: 'mansard',
    fassade: 'putz',
    fenster: 'bogen',
    unten: 'eingang',
    farben: ['#3d2c4a', '#f7f1e4'],
    dachfarben: ['#2c3e50'],
    extras: ['saeulen', 'schild'],
    schild: '🧿',
  }),
  bau({
    id: 'detektei',
    name: 'Detektei',
    emoji: '🕵️',
    category: 'handel',
    coins: 480,
    materials: 5,
    effects: { income: 9, jobs: 2, crime: -3 },
    note: 'Findet, was verloren ging, und dämpft die krummen Touren im Viertel',
    hoehe: 1.1,
    dach: 'flach',
    fassade: 'ziegel',
    fenster: 'dunkel',
    unten: 'eingang',
    farben: ['#4a4038', '#2c3e50'],
    extras: ['schild', 'antenne'],
    schild: '🕵️',
  }),
  bau({
    id: 'bestatter',
    name: 'Bestatter',
    emoji: '🕯️',
    category: 'handel',
    coins: 520,
    materials: 6,
    effects: { income: 10, jobs: 3, happiness: 1 },
    note: 'Letzter Dienst: Abschied, Sarg und ein stilles Zimmer',
    hoehe: 1.2,
    dach: 'walm',
    fassade: 'stein',
    fenster: 'bogen',
    unten: 'eingang',
    farben: ['#2c3e50', '#3d4f63'],
    dachfarben: ['#1c2833'],
    extras: ['saeulen', 'schild'],
    schild: '🕯️',
  }),
  bau({
    id: 'geisterbahn',
    name: 'Geisterbahn',
    emoji: '👻',
    category: 'handel',
    size: [2, 1],
    coins: 860,
    materials: 9,
    needsLevel: 3,
    effects: { income: 16, jobs: 5, happiness: 6 },
    note: 'Jahrmarktsbude mit Schienen, die Leute schreien und zahlen',
    hoehe: 1.4,
    dach: 'sattel',
    fassade: 'holz',
    fenster: 'dunkel',
    unten: 'tor',
    farben: ['#2c3e50', '#6c3483', '#c0392b'],
    dachfarben: ['#1c2833'],
    extras: ['leuchtschrift', 'schild'],
    schild: '👻',
    neon: '#9b59b6',
  }),
  bau({
    id: 'hausaufkopf',
    name: 'Haus auf dem Kopf',
    emoji: '🙃',
    category: 'handel',
    coins: 740,
    materials: 8,
    needsLevel: 3,
    effects: { income: 15, jobs: 4, happiness: 7 },
    note: 'Touristenattraktion: Das Dach ist der Boden, der Eingang hängt oben',
    hoehe: 1.3,
    dach: 'sattel',
    fassade: 'putz',
    fenster: 'normal',
    unten: 'eingang',
    farben: ['#f7f1e4', '#e07a5f'],
    dachfarben: DACHROT,
    extras: ['schild', 'fahnenmast'],
    schild: '🙃',
  }),
  bau({
    id: 'ufoimbiss',
    name: 'UFO-Imbiss',
    emoji: '👽',
    category: 'handel',
    coins: 360,
    materials: 4,
    effects: { income: 9, jobs: 2, happiness: 3 },
    note: 'Fliegende Untertasse mit Fritteuse, nachts leuchtet die Luke',
    hoehe: 0.8,
    dach: 'flach',
    fassade: 'blech',
    fenster: 'band',
    unten: 'laden',
    farben: ['#d7dde3', '#aab4c0'],
    extras: ['leuchtschrift', 'schild'],
    schild: '👽',
    neon: '#7d7fff',
    koerper: { tiefe: 0.6, breite: 0.7 },
  }),
  bau({
    id: 'gewerbehof',
    name: 'Gewerbehof',
    emoji: '🏭',
    category: 'handel',
    size: [2, 2],
    coins: 1600,
    materials: 18,
    needsLevel: 3,
    effects: { income: 22, jobs: 16, happiness: 1 },
    note: 'Mehrere kleine Werkstätten um einen Hof, eine Adresse für viele Betriebe',
    hoehe: 1.4,
    dach: 'saege',
    fassade: 'ziegel',
    fenster: 'band',
    unten: 'tor',
    farben: KLINKER,
    dachfarben: DACHDUNKEL,
    extras: ['schild', 'parkplatz', 'schornstein'],
    schild: '🏭',
    floors: 2,
  }),
  bau({
    id: 'industriepark',
    name: 'Industriepark',
    emoji: '🏗️',
    category: 'handel',
    size: [2, 2],
    coins: 3200,
    materials: 36,
    needsLevel: 6,
    effects: { income: 28, jobs: 22, environment: -5, ziegel: 5 },
    note: 'Hallen, Rampen und ein Pförtner. Liefert Baustoff und Arbeitsplätze',
    hoehe: 1.5,
    dach: 'flach',
    fassade: 'blech',
    fenster: 'band',
    unten: 'tor',
    farben: ['#8d9aa3', '#b0b8bf', '#6f7c85'],
    extras: ['schlot', 'rauch', 'parkplatz', 'gitter'],
    floors: 1,
  }),
  bau({
    id: 'postamt',
    name: 'Postamt',
    emoji: '📮',
    category: 'handel',
    coins: 460,
    materials: 6,
    effects: { income: 8, jobs: 5, happiness: 1 },
    note: 'Briefe, Pakete, Schalter. Ohne das findet nichts den Empfänger',
    hoehe: 1.3,
    dach: 'walm',
    fassade: 'putz',
    fenster: 'bogen',
    unten: 'eingang',
    farben: ['#f7f1e4', '#f4d35e'],
    dachfarben: ['#c0392b'],
    extras: ['fahnenmast', 'schild', 'briefkasten'],
    schild: '📮',
  }),
  bau({
    id: 'feuerwerkslager',
    name: 'Feuerwerkslager',
    emoji: '🎆',
    category: 'handel',
    coins: 640,
    materials: 8,
    needsLevel: 4,
    effects: { income: 13, jobs: 3, happiness: 2, environment: -2 },
    note: 'Lagert Raketen fürs Stadtfest, abseits und hinter Gittern',
    hoehe: 0.9,
    dach: 'flach',
    fassade: 'blech',
    fenster: 'keine',
    unten: 'tor',
    farben: ['#c0392b', '#f4d35e'],
    extras: ['gitter', 'schild', 'stacheldraht'],
    schild: '🎆',
  }),
  bau({
    id: 'modellbahnwerk',
    name: 'Modellbahnwerkstatt',
    emoji: '🚆',
    category: 'handel',
    coins: 420,
    materials: 5,
    needsLevel: 2,
    effects: { income: 9, jobs: 2, happiness: 3, education: 1 },
    note: 'Baut Landschaften im Maßstab, verkauft Gleise und Lokomotiven',
    hoehe: 1,
    dach: 'sattel',
    fassade: 'putz',
    fenster: 'gross',
    unten: 'laden',
    farben: ['#d6eaf8', '#f7f1e4'],
    dachfarben: ['#2e86c1'],
    extras: ['schild', 'markise'],
    schild: '🚆',
  }),
  bau({
    id: 'aquariumlokal',
    name: 'Aquarium-Restaurant',
    emoji: '🐠',
    category: 'handel',
    size: [2, 1],
    coins: 1200,
    materials: 14,
    needsLevel: 4,
    effects: { income: 18, jobs: 8, happiness: 5 },
    note: 'Essen zwischen Scheiben, die Fische schauen zu',
    hoehe: 1.4,
    dach: 'flach',
    fassade: 'glas',
    fenster: 'gross',
    unten: 'laden',
    farben: ['#1a5276', '#5dade2'],
    extras: ['tische', 'leuchtschrift', 'schild'],
    schild: '🐠',
    neon: '#5dade2',
  }),
  bau({
    id: 'seifenkoch',
    name: 'Seifenmanufaktur',
    emoji: '🧼',
    category: 'handel',
    coins: 340,
    materials: 4,
    effects: { income: 9, jobs: 3, happiness: 1 },
    note: 'Kocht Fett und Lauge zu Stücken, die nach Kräutern riechen',
    hoehe: 1,
    dach: 'sattel',
    fassade: 'putz',
    fenster: 'normal',
    unten: 'laden',
    farben: ['#f9e4ec', '#e8f6ef', '#f7f1e4'],
    dachfarben: ['#8e6a8c'],
    extras: ['schild', 'schornstein'],
    schild: '🧼',
  }),
  bau({
    id: 'zahnarztpraxis',
    name: 'Zahnarzt',
    emoji: '🦷',
    category: 'handel',
    coins: 700,
    materials: 8,
    needsLevel: 2,
    effects: { income: 14, jobs: 4, happiness: 1 },
    note: 'Bohrt, flickt und sorgt dafür, dass die Stadt kauen kann',
    hoehe: 1.2,
    dach: 'flach',
    fassade: 'putz',
    fenster: 'band',
    unten: 'eingang',
    farben: ['#f7f4ee', '#d6eaf8'],
    extras: ['kreuz', 'schild'],
    schild: '🦷',
  }),
]

const DEKO_NEU: BuildingDef[] = [
  schmuck({ id: 'palme', name: 'Palme', emoji: '🌴', category: 'natur', coins: 40, effects: { happiness: 1, environment: 2 }, note: 'Steht in einem Kübel und macht den Platz zum Süden', kind: 'baum', height: 1.1, wall: '#8c5a3a', roof: '#2f9e5c', accent: '#1e6b3a' }),
  schmuck({ id: 'kaktusgross', name: 'Kaktus', emoji: '🌵', category: 'natur', coins: 30, effects: { environment: 1, happiness: 1 }, note: 'Braucht fast kein Wasser und sticht, wer zu nah tritt', kind: 'baum', height: 0.7, wall: '#6f8c55', roof: '#3f8f52', accent: '#2f6b3f' }),
  schmuck({ id: 'kirschbaum', name: 'Kirschbaum', emoji: '🌸', category: 'natur', coins: 45, effects: { happiness: 2, environment: 2 }, note: 'Blüht eine Woche rosa und wirft danach Kirschen', kind: 'baum', height: 1, wall: '#6b4a2f', roof: '#f5b7c5', accent: '#e85d8a' }),
  schmuck({ id: 'tanne', name: 'Tanne', emoji: '🌲', category: 'natur', coins: 35, effects: { environment: 3 }, note: 'Immergrün, auch wenn der Rest kahl ist', kind: 'baum', height: 1.2, wall: '#5a4030', roof: '#1e6b3a', accent: '#145232' }),
  schmuck({ id: 'trauerweide', name: 'Trauerweide', emoji: '🌿', category: 'natur', coins: 50, effects: { happiness: 2, environment: 2 }, note: 'Hängende Zweige, gut am Wasser', kind: 'baum', height: 1.1, wall: '#6b4a2f', roof: '#7dcea0', accent: '#27ae60' }),
  schmuck({ id: 'obstbaum', name: 'Obstbaum', emoji: '🍎', category: 'natur', coins: 40, effects: { happiness: 2, environment: 2 }, note: 'Äpfel für die, die darunter wohnen', kind: 'baum', height: 0.9, wall: '#6b4a2f', roof: '#e07a5f', accent: '#c0392b' }),
  schmuck({ id: 'bambushain', name: 'Bambushain', emoji: '🎋', category: 'natur', coins: 55, effects: { environment: 3, happiness: 1 }, note: 'Dichte Halme, Sichtschutz und Rascheln', kind: 'hecke', height: 0.8, wall: '#2f6b3f', roof: '#7dcea0', accent: '#1e8449' }),
  schmuck({ id: 'lavendelhecke', name: 'Lavendelhecke', emoji: '💜', category: 'natur', coins: 40, effects: { happiness: 2, environment: 2 }, note: 'Duftet und hält die Beete in der Reihe', kind: 'hecke', height: 0.35, wall: '#6c3483', roof: '#bb8fce', accent: '#5b2c6f' }),
  schmuck({ id: 'rosenbogen', name: 'Rosenbogen', emoji: '🌹', category: 'schmuck', coins: 70, materials: 1, effects: { happiness: 3, environment: 1 }, note: 'Ein Tor aus Rosen, der Weg geht darunter durch', kind: 'hecke', height: 0.7, wall: '#8c5a3a', roof: '#c0392b', accent: '#f5b7c5' }),
  schmuck({ id: 'sonnenblumen', name: 'Sonnenblumen', emoji: '🌻', category: 'natur', coins: 25, effects: { happiness: 2, environment: 1 }, note: 'Drehen sich zum Licht und machen den Rand gelb', kind: 'blumen', height: 0.4, wall: '#5aa85f', roof: '#f4d35e', accent: '#e07a5f' }),
  schmuck({ id: 'hochbeet', name: 'Hochbeet', emoji: '🥕', category: 'natur', coins: 55, materials: 1, effects: { happiness: 1, environment: 2 }, note: 'Salat und Kräuter auf Tischhöhe, ohne sich zu bücken', kind: 'blumen', height: 0.25, wall: '#8c5a3a', roof: '#27ae60', accent: '#e07a5f' }),
  schmuck({ id: 'tulpenbeet', name: 'Tulpenbeet', emoji: '🌷', category: 'natur', coins: 30, effects: { happiness: 2, environment: 1 }, note: 'Ein Rechteck voller Kelche, im Frühling kaum zu übersehen', kind: 'blumen', height: 0.15, wall: '#5aa85f', roof: '#e85d8a', accent: '#f4d35e' }),
  schmuck({ id: 'gartenzwerg', name: 'Riesenzwerg', emoji: '🧙', category: 'schmuck', coins: 90, materials: 1, effects: { happiness: 3 }, note: 'Viel zu groß für ein Beet, steht Wache vor dem Grundstück', kind: 'statue', height: 0.8, wall: '#c0392b', roof: '#f4d35e', accent: '#27ae60' }),
  schmuck({ id: 'flamingofigur', name: 'Flamingo', emoji: '🦩', category: 'schmuck', coins: 60, effects: { happiness: 2 }, note: 'Plastikvogel auf einem Bein, reiner Schmuck', kind: 'statue', height: 0.6, wall: '#f5b7c5', roof: '#e85d8a', accent: '#f7f4ee' }),
  schmuck({ id: 'moaistatue', name: 'Moai', emoji: '🗿', category: 'schmuck', coins: 220, materials: 3, needsLevel: 3, effects: { happiness: 4 }, note: 'Steinkopf, schaut über den Platz und sagt nichts', kind: 'statue', height: 1.1, wall: '#8d7b66', roof: '#6f6256', accent: '#4a4038' }),
  schmuck({ id: 'einhornstatue', name: 'Einhorn', emoji: '🦄', category: 'schmuck', coins: 180, materials: 2, effects: { happiness: 4 }, note: 'Wunschfigur mitten auf dem Platz, die Kinder bestehen darauf', kind: 'statue', height: 0.9, wall: '#f7f4ee', roof: '#f5b7c5', accent: '#f4d35e' }),
  schmuck({ id: 'astronaut', name: 'Astronaut', emoji: '🧑‍🚀', category: 'schmuck', coins: 260, materials: 3, needsLevel: 4, effects: { happiness: 3, education: 1 }, note: 'Erinnert daran, dass die Stadt auch nach oben schaut', kind: 'statue', height: 1, wall: '#f7f4ee', roof: '#5dade2', accent: '#1a5276' }),
  schmuck({ id: 'walgerippe', name: 'Walskelett', emoji: '🐋', category: 'schmuck', coins: 340, materials: 4, needsLevel: 4, effects: { happiness: 5, education: 2 }, note: 'Begehbares Gerippe, ein Denkmal für etwas sehr Großes', kind: 'statue', height: 1.2, wall: '#f7f4ee', roof: '#d5d8dc', accent: '#aeb6bf' }),
  schmuck({ id: 'riesenapfel', name: 'Riesenapfel', emoji: '🍎', category: 'schmuck', coins: 150, materials: 2, effects: { happiness: 3 }, note: 'Begehbare Frucht, Markenzeichen fürs Viertel daneben', kind: 'statue', height: 0.9, wall: '#c0392b', roof: '#27ae60', accent: '#f4d35e' }),
  schmuck({ id: 'drachenskulptur', name: 'Drachen', emoji: '🐉', category: 'schmuck', coins: 280, materials: 3, needsLevel: 3, effects: { happiness: 4 }, note: 'Steinernes Tier auf dem Platz, die Stadt hat ein Maskottchen', kind: 'statue', height: 1, wall: '#1e8449', roof: '#145232', accent: '#f4d35e' }),
  schmuck({ id: 'roboterdenkmal', name: 'Roboterdenkmal', emoji: '🤖', category: 'schmuck', coins: 240, materials: 3, needsLevel: 3, effects: { happiness: 2, education: 1 }, note: 'Blechfigur, erinnert an die Werkstätten, die sie gebaut haben', kind: 'statue', height: 1.1, wall: '#aeb6bf', roof: '#5d6d7e', accent: '#e74c3c' }),
  schmuck({ id: 'obelisk', name: 'Obelisk', emoji: '🗽', category: 'schmuck', coins: 200, materials: 3, needsLevel: 2, effects: { happiness: 3 }, note: 'Nadel aus Stein, markiert die Mitte eines Platzes', kind: 'statue', height: 1.4, wall: '#d5d8dc', roof: '#f4d35e', accent: '#aeb6bf' }),
  schmuck({ id: 'sonnenuhr', name: 'Sonnenuhr', emoji: '☀️', category: 'schmuck', coins: 80, materials: 1, effects: { happiness: 1, education: 1 }, note: 'Zeigt die Stunde, solange die Sonne scheint', kind: 'statue', height: 0.45, wall: '#d5d8dc', roof: '#f4d35e', accent: '#7f8c8d' }),
  schmuck({ id: 'vogelscheuche', name: 'Vogelscheuche', emoji: '🧙', category: 'schmuck', coins: 35, effects: { happiness: 1, environment: 1 }, note: 'Hält die Vögel von den Beeten, sieht dabei selbst etwas verloren aus', kind: 'fahne', height: 1, wall: '#8c5a3a', roof: '#c0392b', accent: '#f4d35e' }),
  schmuck({ id: 'wegweiser', name: 'Wegweiser', emoji: '🧭', category: 'schmuck', coins: 50, materials: 1, effects: { happiness: 1 }, note: 'Pfeile zu Hafen, Markt und Rathaus', kind: 'fahne', height: 1, wall: '#4a4038', roof: '#f7f1e4', accent: '#c0392b' }),
  schmuck({ id: 'feuerstelle', name: 'Feuerstelle', emoji: '🔥', category: 'schmuck', coins: 70, materials: 1, effects: { happiness: 3 }, note: 'Schale fürs Abendfeuer, die Nachbarn kommen von allein', kind: 'laterne', height: 0.35, wall: '#4a4038', roof: '#e07a5f', accent: '#f4d35e' }),
  schmuck({ id: 'bushaltestelle', name: 'Bushaltestelle', emoji: '🚏', category: 'schmuck', coins: 90, materials: 1, effects: { happiness: 2 }, note: 'Dach und Bank, hier wartet die Stadt auf die nächste Fahrt', kind: 'bank', height: 0.45, wall: '#3d6f8c', roof: '#f7f4ee', accent: '#f4d35e' }),
  schmuck({ id: 'strandkorb', name: 'Strandkorb', emoji: '🏖️', category: 'schmuck', coins: 65, effects: { happiness: 2 }, note: 'Sitzkorb mit Verdeck, auch ohne Meer', kind: 'bank', height: 0.4, wall: '#c45c4a', roof: '#f4d35e', accent: '#f7f4ee' }),
  schmuck({ id: 'schaukel', name: 'Schaukel', emoji: '🛝', category: 'schmuck', coins: 55, materials: 1, effects: { happiness: 3 }, note: 'Zwei Seile und ein Brett, für die kurze Pause', kind: 'bank', height: 0.5, wall: '#8c5a3a', roof: '#c0392b', accent: '#f4d35e' }),
  schmuck({ id: 'insektenhotel', name: 'Insektenhotel', emoji: '🪲', category: 'natur', coins: 40, effects: { environment: 3, happiness: 1 }, note: 'Röhren und Holz für Wildbienen', kind: 'statue', height: 0.45, wall: '#c4a574', roof: '#8c5a3a', accent: '#6f8c55' }),
  schmuck({ id: 'steinpyramide', name: 'Steinpyramide', emoji: '🔺', category: 'schmuck', coins: 50, effects: { happiness: 1, environment: 1 }, note: 'Aufgeschichtete Steine, ein kleines Mal am Wegrand', kind: 'felsen', height: 0.45, wall: '#8d7b66', roof: '#a89880', accent: '#6f6256' }),
  schmuck({ id: 'zengarten', name: 'Zengarten', emoji: '🪨', category: 'natur', coins: 120, materials: 1, effects: { happiness: 4, environment: 2 }, note: 'Kies, drei Steine, eine geharkte Spur', kind: 'flach', height: 0.08, wall: '#d5d0c6', roof: '#c8c2b4', accent: '#8d7b66' }),
  schmuck({ id: 'seerosenteich', name: 'Seerosenteich', emoji: '🪷', category: 'natur', coins: 160, materials: 1, size: [1, 1], effects: { happiness: 4, environment: 4 }, note: 'Kleines Wasser mit Blättern, die Frösche kommen später', kind: 'wasser', height: 0.08, wall: '#1a5276', roof: '#5dade2', accent: '#f5b7c5' }),
  schmuck({ id: 'sprudel', name: 'Sprudel', emoji: '💦', category: 'schmuck', coins: 140, materials: 2, effects: { happiness: 4 }, note: 'Kleiner Strahl in einer Schale, zum Zuhören', kind: 'brunnen', height: 0.3, wall: '#d5d8dc', roof: '#5dade2', accent: '#aed6f1' }),
  schmuck({ id: 'ufoskulptur', name: 'UFO-Skulptur', emoji: '🛸', category: 'schmuck', coins: 200, materials: 2, needsLevel: 3, effects: { happiness: 3 }, note: 'Hängt über einem Mast und leuchtet abends', kind: 'statue', height: 1.1, wall: '#d7dde3', roof: '#7d7fff', accent: '#f7f4ee' }),
  schmuck({ id: 'riesenstuhl', name: 'Riesenstuhl', emoji: '🪑', category: 'schmuck', coins: 160, materials: 2, effects: { happiness: 3 }, note: 'Ein Stuhl für Riesen, zum Draufklettern und Fotografieren', kind: 'statue', height: 1, wall: '#c0392b', roof: '#f4d35e', accent: '#8c5a3a' }),
  schmuck({ id: 'windspielmast', name: 'Windspiel', emoji: '🎐', category: 'schmuck', coins: 45, effects: { happiness: 2 }, note: 'Klingelt, wenn der Wind durch die Gasse geht', kind: 'fahne', height: 0.9, wall: '#d7dde3', roof: '#5dade2', accent: '#f4d35e' }),
  schmuck({ id: 'gargoyle', name: 'Wasserspeier', emoji: '👹', category: 'schmuck', coins: 110, materials: 1, needsLevel: 2, effects: { happiness: 2 }, note: 'Fratze an der Ecke, leitet das Regenwasser vom Dach', kind: 'statue', height: 0.6, wall: '#5d6d7e', roof: '#2c3e50', accent: '#7f8c8d' }),
  bau({
    id: 'telefonzelle',
    name: 'Telefonzelle',
    emoji: '☎️',
    category: 'schmuck',
    coins: 80,
    materials: 1,
    effects: { happiness: 1 },
    note: 'Roter Kasten, falls das Handy keinen Empfang hat',
    hoehe: 0.85,
    dach: 'flach',
    fassade: 'glas',
    fenster: 'gross',
    unten: 'tuer',
    farben: ['#c0392b'],
    dachfarben: ['#8c2a22'],
    extras: ['schild'],
    schild: '☎️',
    koerper: { tiefe: 0.32, breite: 0.32 },
    floors: 1,
  }),
  bau({
    id: 'litfass',
    name: 'Litfaßsäule',
    emoji: '📰',
    category: 'schmuck',
    coins: 70,
    materials: 1,
    effects: { happiness: 1 },
    note: 'Runde Säule für Plakate, die Stadt klebt hier ihre Termine hin',
    hoehe: 1.1,
    dach: 'flach',
    fassade: 'putz',
    fenster: 'keine',
    unten: 'tuer',
    farben: ['#f4d35e', '#e07a5f', '#5dade2', '#f7f1e4'],
    extras: ['schild'],
    schild: '📰',
    koerper: { tiefe: 0.28, breite: 0.28 },
    floors: 1,
  }),
]

export const NEUBAU: BuildingDef[] = [...WOHNEN_NEU, ...GEWERBE_NEU, ...DEKO_NEU]
