// Die Unterwelt. Diese Orte bringen Schwarzgeld – unversteuert, schnell verdient –
// und ziehen die Kriminalität im Viertel nach oben. Wo Bildung fehlt und Armut
// herrscht, entstehen sie auch ohne dein Zutun. Die Polizei hebt sie aus, wenn
// eine Wache in Reichweite ist.
import type { BuildingDef } from '../catalog'

export const UNTERWELT: BuildingDef[] = [
  {
    id: 'gangtreff',
    name: 'Gang-Treffpunkt',
    category: 'unterwelt',
    emoji: '🕶️',
    size: [1, 1],
    coins: 350,
    materials: 4,
    effects: { black: 30, crime: 12, happiness: -4 },
    needsLevel: 2,
    note: 'Graffiti, Gitter, laute Musik',
    look: {
      kind: 'bau',
      height: 1.1,
      wall: '#6b6660',
      roof: '#3a3a3a',
      accent: '#c0392b',
      floors: 1,
      stil: {
        dach: 'flach',
        fassade: 'ziegel',
        fenster: 'dunkel',
        unten: 'tuer',
        farben: ['#6b6660', '#5a5f66', '#7a6a5a', '#665a66'],
        extras: ['graffiti', 'gitter', 'muell'],
        koerper: { tiefe: 0.7, breite: 0.8 },
      },
    },
  },
  {
    id: 'growhaus',
    name: 'Grow-Haus',
    category: 'unterwelt',
    emoji: '🪴',
    size: [1, 1],
    coins: 450,
    materials: 6,
    effects: { black: 40, crime: 6, happiness: -1 },
    needsLevel: 2,
    note: 'Sieht aus wie ein Haus – bis auf das lila Licht',
    look: {
      kind: 'bau',
      height: 1.3,
      wall: '#d8cdb8',
      roof: '#5a4a44',
      accent: '#3a2e2a',
      floors: 2,
      stil: {
        dach: 'sattel',
        fassade: 'putz',
        fenster: 'dunkel',
        unten: 'tuer',
        farben: ['#d8cdb8', '#c9bfa9', '#d0c8c0', '#c8cfc4'],
        dachfarben: ['#5a4a44', '#4b4f58'],
        // Das lila Leuchten kommt aus den verklebten Fenstern: fenster 'dunkel' plus neon
        extras: ['gitter'],
        neon: '#c44fff',
      },
    },
  },
  {
    id: 'hanfplantage',
    name: 'Hanfplantage',
    category: 'unterwelt',
    emoji: '🌿',
    size: [2, 1],
    coins: 700,
    materials: 9,
    effects: { black: 60, crime: 8, happiness: -2, environment: 2, jobs: 2 },
    needsLevel: 2,
    note: 'Fängt als Gewächshaus an – und wächst über 20 Stufen zur Grow-Fabrik',
    // Zwanzig Stufen: Das Schwarzgeld vervielfacht sich, die Anlage wird zum Turm,
    // und mit ihr wächst die Kriminalität im Viertel.
    upgrades: Array.from({ length: 20 }, (_, i) => {
      const s = i + 1
      return {
        coins: Math.round(700 * Math.pow(1.5, s)),
        materials: Math.round(9 * Math.pow(1.22, s)),
        effects: {
          black: Math.round(60 * Math.pow(1.42, s)),
          crime: 8 + s * 2,
          happiness: -2 - Math.floor(s / 3),
          environment: 2,
          jobs: 2 + s * 2,
        },
      }
    }),
    look: {
      kind: 'bau',
      height: 1,
      wall: '#cfe8d0',
      roof: '#bfe0c0',
      accent: '#3f8f52',
      floors: 1,
      stufenHoehe: 0.24,
      stil: {
        dach: 'sattel',
        fassade: 'glas',
        fenster: 'keine',
        unten: 'tuer',
        farben: ['#cfe8d0', '#c4e0c8', '#d4ecd8'],
        dachfarben: ['#bfe0c0'],
        extras: ['gewaechshaus', 'stacheldraht'],
        neon: '#c44fff',
        koerper: { tiefe: 0.8, breite: 0.92 },
      },
    },
  },
  {
    id: 'waschsalon',
    name: 'Waschsalon',
    category: 'unterwelt',
    emoji: '🧺',
    size: [1, 1],
    coins: 800,
    materials: 10,
    effects: { black: 55, income: 8, crime: 6 },
    needsLevel: 3,
    note: 'Wäscht vor allem Geld',
    look: {
      kind: 'bau',
      height: 1.3,
      wall: '#e3f2f5',
      roof: '#6d7a86',
      accent: '#2e86c1',
      floors: 2,
      stil: {
        dach: 'flach',
        fassade: 'putz',
        fenster: 'normal',
        unten: 'laden',
        farben: ['#e3f2f5', '#f5f0e6', '#e6f5e0'],
        extras: ['schild', 'leuchtschrift'],
        schild: '🧺',
        neon: '#48dbfb',
      },
    },
  },
  {
    id: 'spielhalle',
    name: 'Illegale Spielhalle',
    category: 'unterwelt',
    emoji: '🎰',
    size: [1, 1],
    coins: 900,
    materials: 12,
    effects: { black: 70, crime: 9, happiness: -3 },
    needsLevel: 3,
    note: 'Neon, Gitter, Automaten bis zum Morgen',
    look: {
      kind: 'bau',
      height: 1.4,
      wall: '#2a1f3a',
      roof: '#1a1428',
      accent: '#f4d35e',
      floors: 2,
      stil: {
        dach: 'flach',
        fassade: 'blech',
        fenster: 'dunkel',
        unten: 'eingang',
        farben: ['#2a1f3a', '#3a1f2a', '#1f2a3a'],
        extras: ['leuchtschrift', 'gitter', 'schild'],
        schild: '🎰',
        neon: '#ff4fd8',
      },
    },
  },
  {
    id: 'drogenlabor',
    name: 'Drogenlabor',
    category: 'unterwelt',
    emoji: '🧪',
    size: [1, 1],
    coins: 600,
    materials: 8,
    effects: { black: 90, crime: 14, happiness: -5, environment: -4 },
    needsLevel: 4,
    note: 'Ein Wohnwagen mit verklebten Fenstern und seltsamem Rauch',
    look: {
      kind: 'bau',
      height: 0.6,
      wall: '#d8cfb8',
      roof: '#bfb8a4',
      accent: '#5a6168',
      floors: 1,
      stil: {
        dach: 'flach',
        fassade: 'blech',
        fenster: 'dunkel',
        unten: 'tuer',
        farben: ['#d8cfb8', '#cfd4c4', '#d4c4b0'],
        extras: ['rauch', 'muell', 'stacheldraht'],
        neon: '#9dff8b',
        koerper: { tiefe: 0.46, breite: 0.84 },
      },
    },
  },
  {
    id: 'hehlerei',
    name: 'Schrottplatz & Hehlerei',
    category: 'unterwelt',
    emoji: '🚗',
    size: [2, 2],
    coins: 1100,
    materials: 14,
    effects: { black: 85, crime: 10, environment: -6, happiness: -3 },
    needsLevel: 4,
    note: 'Autowracks, Werkstatt, keine Fragen',
    look: {
      kind: 'bau',
      height: 1.2,
      wall: '#8a8f94',
      roof: '#5a5f64',
      accent: '#c0392b',
      floors: 1,
      stil: {
        dach: 'pult',
        fassade: 'blech',
        fenster: 'klein',
        unten: 'tor',
        farben: ['#8a8f94', '#7a7f84', '#8f8a7a'],
        extras: ['wracks', 'stacheldraht', 'graffiti'],
        koerper: { tiefe: 0.4, breite: 0.6 },
      },
    },
  },
  {
    id: 'rotlichtbar',
    name: 'Rotlicht-Bar',
    category: 'unterwelt',
    emoji: '🍸',
    size: [1, 1],
    coins: 700,
    materials: 8,
    effects: { black: 50, income: 10, jobs: 4, crime: 5, happiness: -3 },
    needsLevel: 3,
    note: 'Rote Laternen, laute Musik, kein Ausweis nötig',
    look: {
      kind: 'bau',
      height: 1.2,
      wall: '#4a2030',
      roof: '#2a141c',
      accent: '#ff4060',
      floors: 2,
      stil: {
        dach: 'flach',
        fassade: 'ziegel',
        fenster: 'dunkel',
        unten: 'eingang',
        farben: ['#4a2030', '#3a1c2c', '#52243a'],
        dachfarben: ['#2a141c'],
        extras: ['leuchtschrift', 'schild'],
        vielleicht: ['graffiti', 'muell'],
        schild: '🍸',
        neon: '#ff4060',
      },
    },
  },
  {
    id: 'stripclub',
    name: 'Stripclub',
    category: 'unterwelt',
    emoji: '💃',
    size: [1, 1],
    coins: 1200,
    materials: 14,
    effects: { black: 95, income: 12, jobs: 6, crime: 7, happiness: -4 },
    needsLevel: 4,
    note: 'Neon und Bass bis fünf Uhr morgens – die Nachbarn schlafen schlecht',
    look: {
      kind: 'bau',
      height: 1.4,
      wall: '#3a1b4a',
      roof: '#22102c',
      accent: '#ff3fa8',
      floors: 2,
      stil: {
        dach: 'flach',
        fassade: 'putz',
        fenster: 'dunkel',
        unten: 'eingang',
        farben: ['#3a1b4a', '#2a1a3a', '#40203a'],
        dachfarben: ['#22102c'],
        extras: ['leuchtschrift', 'schild', 'markise'],
        vielleicht: ['parkplatz', 'graffiti'],
        schild: '💃',
        neon: '#ff3fa8',
      },
    },
  },
  {
    id: 'wettbuero',
    name: 'Illegales Wettbüro',
    category: 'unterwelt',
    emoji: '🎲',
    size: [1, 1],
    coins: 1000,
    materials: 12,
    effects: { black: 80, jobs: 3, crime: 8, happiness: -3 },
    needsLevel: 4,
    note: 'Wetten ohne Lizenz, Quoten ohne Gewissen',
    look: {
      kind: 'bau',
      height: 1.1,
      wall: '#1f4a3a',
      roof: '#12302a',
      accent: '#5dff8a',
      floors: 1,
      stil: {
        dach: 'pult',
        fassade: 'putz',
        fenster: 'dunkel',
        unten: 'laden',
        farben: ['#1f4a3a', '#25503f', '#1c4038'],
        dachfarben: ['#12302a'],
        extras: ['schild', 'leuchtschrift', 'gitter'],
        vielleicht: ['muell'],
        schild: '🎲',
        neon: '#5dff8a',
      },
    },
  },
  {
    id: 'bordell',
    name: 'Puff',
    category: 'unterwelt',
    emoji: '💋',
    size: [1, 1],
    coins: 1600,
    materials: 18,
    effects: { black: 130, jobs: 8, crime: 9, happiness: -6 },
    needsLevel: 5,
    note: 'Rotes Licht im Fenster, keine Klingelschilder. Familien ziehen weg.',
    look: {
      kind: 'bau',
      height: 1.6,
      wall: '#5a1a22',
      roof: '#2e0d12',
      accent: '#ff2d55',
      floors: 3,
      stil: {
        dach: 'mansard',
        fassade: 'ziegel',
        fenster: 'dunkel',
        unten: 'tuer',
        farben: ['#5a1a22', '#4a1c2a', '#602030'],
        dachfarben: ['#2e0d12', '#3a1a20'],
        extras: ['leuchtschrift', 'fensterlaeden'],
        vielleicht: ['balkone', 'efeu'],
        schild: '💋',
        neon: '#ff2d55',
      },
    },
  },
  {
    id: 'schwarzmarkt',
    name: 'Schwarzmarkt',
    category: 'unterwelt',
    emoji: '🏴',
    size: [2, 1],
    coins: 2600,
    materials: 30,
    effects: { black: 210, jobs: 12, crime: 12, happiness: -5, environment: -2 },
    needsLevel: 6,
    note: 'Zelte, Kisten, Bargeld – alles, was es nicht geben dürfte',
    look: {
      kind: 'bau',
      height: 0.9,
      wall: '#4a4d52',
      roof: '#2c2e33',
      accent: '#ff9d3f',
      floors: 1,
      stil: {
        dach: 'saege',
        fassade: 'blech',
        fenster: 'klein',
        unten: 'tor',
        farben: ['#4a4d52', '#5a5048', '#3f4a52'],
        dachfarben: ['#2c2e33', '#3a3530'],
        extras: ['stacheldraht', 'muell', 'graffiti', 'parkplatz'],
        neon: '#ff9d3f',
        koerper: { tiefe: 0.75, breite: 0.9 },
      },
    },
  },
  {
    id: 'casino',
    name: 'Casino',
    category: 'unterwelt',
    emoji: '🃏',
    size: [2, 2],
    coins: 4500,
    materials: 55,
    effects: { black: 320, income: 60, jobs: 40, crime: 10, happiness: -2 },
    needsLevel: 7,
    note: 'Roulette, Poker, Champagner – und Geldströme, die niemand nachrechnet',
    look: {
      kind: 'bau',
      height: 1.9,
      wall: '#f1e3c2',
      roof: '#b8942f',
      accent: '#ffcc33',
      floors: 2,
      stil: {
        dach: 'flach',
        fassade: 'stein',
        fenster: 'gross',
        unten: 'eingang',
        farben: ['#f1e3c2', '#f4ead6', '#ecd9b0'],
        dachfarben: ['#b8942f', '#a5842a'],
        extras: ['leuchtschrift', 'saeulen', 'schild', 'parkplatz'],
        vielleicht: ['fahnenmast', 'dachterrasse'],
        schild: '🃏',
        neon: '#ffcc33',
        koerper: { tiefe: 0.7, breite: 0.9 },
      },
    },
  },
  {
    id: 'schmuggellager',
    name: 'Schmugglerlager',
    category: 'unterwelt',
    emoji: '📦',
    size: [2, 1],
    coins: 1300,
    materials: 16,
    effects: { black: 100, crime: 11, happiness: -2 },
    needsLevel: 5,
    note: 'Keiner weiß, was in den Kisten ist',
    look: {
      kind: 'bau',
      height: 1.5,
      wall: '#7a8a8a',
      roof: '#4a5050',
      accent: '#3a3f46',
      floors: 1,
      stil: {
        dach: 'pult',
        fassade: 'blech',
        fenster: 'dunkel',
        unten: 'tor',
        farben: ['#7a8a8a', '#8a7a6a', '#6a7a8a'],
        extras: ['gitter', 'graffiti', 'stacheldraht'],
      },
    },
  },
]
