// Die Unterwelt. Diese Orte bringen Schwarzgeld – unversteuert, schnell verdient –
// und ziehen die Kriminalität im Viertel nach oben. Wo Bildung fehlt und Armut
// herrscht, entstehen sie auch ohne dein Zutun. Die Polizei hebt sie aus, wenn
// eine Wache in Reichweite ist.
import type { BuildingDef } from '../catalog'

export const UNTERWELT: BuildingDef[] = [
  {
    id: 'gangtreff',
    name: 'Gang-Treffpunkt',
    category: 'unterwelt',
    emoji: '🕶️',
    size: [1, 1],
    coins: 350,
    materials: 4,
    effects: { black: 30, crime: 12, happiness: -4 },
    needsLevel: 2,
    note: 'Graffiti, Gitter, laute Musik',
    look: {
      kind: 'bau',
      height: 1.1,
      wall: '#6b6660',
      roof: '#3a3a3a',
      accent: '#c0392b',
      floors: 1,
      stil: {
        dach: 'flach',
        fassade: 'ziegel',
        fenster: 'dunkel',
        unten: 'tuer',
        farben: ['#6b6660', '#5a5f66', '#7a6a5a', '#665a66'],
        extras: ['graffiti', 'gitter', 'muell'],
        koerper: { tiefe: 0.7, breite: 0.8 },
      },
    },
  },
  {
    id: 'growhaus',
    name: 'Grow-Haus',
    category: 'unterwelt',
    emoji: '🪴',
    size: [1, 1],
    coins: 450,
    materials: 6,
    effects: { black: 40, crime: 6, happiness: -1 },
    needsLevel: 2,
    note: 'Sieht aus wie ein Haus – bis auf das lila Licht',
    look: {
      kind: 'bau',
      height: 1.3,
      wall: '#d8cdb8',
      roof: '#5a4a44',
      accent: '#3a2e2a',
      floors: 2,
      stil: {
        dach: 'sattel',
        fassade: 'putz',
        fenster: 'dunkel',
        unten: 'tuer',
        farben: ['#d8cdb8', '#c9bfa9', '#d0c8c0', '#c8cfc4'],
        dachfarben: ['#5a4a44', '#4b4f58'],
        // Das lila Leuchten kommt aus den verklebten Fenstern: fenster 'dunkel' plus neon
        extras: ['gitter'],
        neon: '#c44fff',
      },
    },
  },
  {
    id: 'hanfplantage',
    name: 'Hanfplantage',
    category: 'unterwelt',
    emoji: '🌿',
    size: [2, 1],
    coins: 700,
    materials: 9,
    effects: { black: 60, crime: 8, happiness: -2, environment: 2 },
    needsLevel: 2,
    note: 'Gewächshaus mit Growlicht und Stacheldraht',
    look: {
      kind: 'bau',
      height: 1,
      wall: '#cfe8d0',
      roof: '#bfe0c0',
      accent: '#3f8f52',
      floors: 1,
      stil: {
        dach: 'sattel',
        fassade: 'glas',
        fenster: 'keine',
        unten: 'tuer',
        farben: ['#cfe8d0', '#c4e0c8', '#d4ecd8'],
        dachfarben: ['#bfe0c0'],
        extras: ['gewaechshaus', 'stacheldraht'],
        neon: '#c44fff',
        koerper: { tiefe: 0.8, breite: 0.92 },
      },
    },
  },
  {
    id: 'waschsalon',
    name: 'Waschsalon',
    category: 'unterwelt',
    emoji: '🧺',
    size: [1, 1],
    coins: 800,
    materials: 10,
    effects: { black: 55, income: 8, crime: 6 },
    needsLevel: 3,
    note: 'Wäscht vor allem Geld',
    look: {
      kind: 'bau',
      height: 1.3,
      wall: '#e3f2f5',
      roof: '#6d7a86',
      accent: '#2e86c1',
      floors: 2,
      stil: {
        dach: 'flach',
        fassade: 'putz',
        fenster: 'normal',
        unten: 'laden',
        farben: ['#e3f2f5', '#f5f0e6', '#e6f5e0'],
        extras: ['schild', 'leuchtschrift'],
        schild: '🧺',
        neon: '#48dbfb',
      },
    },
  },
  {
    id: 'spielhalle',
    name: 'Illegale Spielhalle',
    category: 'unterwelt',
    emoji: '🎰',
    size: [1, 1],
    coins: 900,
    materials: 12,
    effects: { black: 70, crime: 9, happiness: -3 },
    needsLevel: 3,
    note: 'Neon, Gitter, Automaten bis zum Morgen',
    look: {
      kind: 'bau',
      height: 1.4,
      wall: '#2a1f3a',
      roof: '#1a1428',
      accent: '#f4d35e',
      floors: 2,
      stil: {
        dach: 'flach',
        fassade: 'blech',
        fenster: 'dunkel',
        unten: 'eingang',
        farben: ['#2a1f3a', '#3a1f2a', '#1f2a3a'],
        extras: ['leuchtschrift', 'gitter', 'schild'],
        schild: '🎰',
        neon: '#ff4fd8',
      },
    },
  },
  {
    id: 'drogenlabor',
    name: 'Drogenlabor',
    category: 'unterwelt',
    emoji: '🧪',
    size: [1, 1],
    coins: 600,
    materials: 8,
    effects: { black: 90, crime: 14, happiness: -5, environment: -4 },
    needsLevel: 4,
    note: 'Ein Wohnwagen mit verklebten Fenstern und seltsamem Rauch',
    look: {
      kind: 'bau',
      height: 0.6,
      wall: '#d8cfb8',
      roof: '#bfb8a4',
      accent: '#5a6168',
      floors: 1,
      stil: {
        dach: 'flach',
        fassade: 'blech',
        fenster: 'dunkel',
        unten: 'tuer',
        farben: ['#d8cfb8', '#cfd4c4', '#d4c4b0'],
        extras: ['rauch', 'muell', 'stacheldraht'],
        neon: '#9dff8b',
        koerper: { tiefe: 0.46, breite: 0.84 },
      },
    },
  },
  {
    id: 'hehlerei',
    name: 'Schrottplatz & Hehlerei',
    category: 'unterwelt',
    emoji: '🚗',
    size: [2, 2],
    coins: 1100,
    materials: 14,
    effects: { black: 85, crime: 10, environment: -6, happiness: -3 },
    needsLevel: 4,
    note: 'Autowracks, Werkstatt, keine Fragen',
    look: {
      kind: 'bau',
      height: 1.2,
      wall: '#8a8f94',
      roof: '#5a5f64',
      accent: '#c0392b',
      floors: 1,
      stil: {
        dach: 'pult',
        fassade: 'blech',
        fenster: 'klein',
        unten: 'tor',
        farben: ['#8a8f94', '#7a7f84', '#8f8a7a'],
        extras: ['wracks', 'stacheldraht', 'graffiti'],
        koerper: { tiefe: 0.4, breite: 0.6 },
      },
    },
  },
  {
    id: 'schmuggellager',
    name: 'Schmugglerlager',
    category: 'unterwelt',
    emoji: '📦',
    size: [2, 1],
    coins: 1300,
    materials: 16,
    effects: { black: 100, crime: 11, happiness: -2 },
    needsLevel: 5,
    note: 'Keiner weiß, was in den Kisten ist',
    look: {
      kind: 'bau',
      height: 1.5,
      wall: '#7a8a8a',
      roof: '#4a5050',
      accent: '#3a3f46',
      floors: 1,
      stil: {
        dach: 'pult',
        fassade: 'blech',
        fenster: 'dunkel',
        unten: 'tor',
        farben: ['#7a8a8a', '#8a7a6a', '#6a7a8a'],
        extras: ['gitter', 'graffiti', 'stacheldraht'],
      },
    },
  },
]
