// Wohnhäuser – vom Wohnwagen bis zum Anwesen. Jede Art hat eine Farbpalette und
// Zugaben, die nur manche Häuser haben: So sieht kaum ein Haus aus wie das andere.
import type { BuildingDef } from '../catalog'

/** Gedeckte, abgewohnte Töne für einfache Viertel */
const ABGEWOHNT = ['#b9ad9a', '#a9a08f', '#c4b59c', '#9fa3a0', '#b3a58e', '#a8998a']
/** Pastell der Nachkriegs- und Sozialbauten */
const PASTELL = ['#f2cfa6', '#bcdbe3', '#e9e1a9', '#d9c3e3', '#c8e0bf', '#f0c4c0', '#e6d6bd']
/** Freundliche Hausfarben */
const HAUSFARBEN = ['#f3e2c7', '#fbf0dc', '#e8d5b5', '#f6e4d8', '#e3ecd9', '#dfe8ee', '#f5e9c9', '#efd9d0']
/** Weiß und Creme der besseren Adressen */
const EDEL = ['#fbf8f1', '#f4efe4', '#efe9dd', '#f7f1e6', '#eceff1']
/** Schwedenrot, Ocker, Taubenblau, Salbei */
const HOLZFARBEN = ['#a8382c', '#c89a38', '#3f6f8c', '#6f8c55', '#8c5a3a', '#e0d7c4']
/** Gründerzeit-Fassaden */
const GRUENDERZEIT = ['#e8d8b8', '#d9c7a8', '#f0e2c8', '#c8d8d0', '#e0c8c0', '#d8cfe6', '#f2d9b8']

const ZIEGELROT = ['#c8553d', '#a8563c', '#b9503f', '#9c4a3a']
const SCHIEFER = ['#4f5864', '#5a6470', '#454c57']
const DUNKELDACH = ['#3f4652', '#5a4a44', '#4b5a52', '#3a3f4a']

export const WOHNEN: BuildingDef[] = [
  // ---------- Arm ----------
  {
    id: 'wohnwagen',
    name: 'Wohnwagen',
    category: 'wohnen',
    emoji: '🚐',
    size: [1, 1],
    coins: 60,
    materials: 1,
    effects: { capacity: 3, happiness: -2, klasse: 'arm' },
    note: 'Billig und eng – für den Anfang',
    look: {
      kind: 'bau',
      height: 0.55,
      wall: '#e8e2d0',
      roof: '#cfc8b4',
      accent: '#6b7a86',
      floors: 1,
      stil: {
        dach: 'flach',
        fassade: 'blech',
        fenster: 'klein',
        unten: 'tuer',
        farben: ['#e8e2d0', '#d9e4e8', '#e6d3b3', '#cfd8c4', '#e8d0c8'],
        extras: ['muell'],
        vielleicht: ['graffiti', 'satellit'],
        koerper: { tiefe: 0.46, breite: 0.84 },
      },
    },
  },
  {
    id: 'containerhaus',
    name: 'Containerwohnung',
    category: 'wohnen',
    emoji: '📦',
    size: [1, 1],
    coins: 95,
    materials: 2,
    effects: { capacity: 4, happiness: -1, klasse: 'arm' },
    note: 'Gestapelte Container, bunt und praktisch',
    look: {
      kind: 'bau',
      height: 1.25,
      wall: '#c0392b',
      roof: '#7f8c8d',
      accent: '#2c3e50',
      floors: 2,
      stil: {
        dach: 'flach',
        fassade: 'blech',
        fenster: 'klein',
        unten: 'tuer',
        farben: ['#c0392b', '#2e86c1', '#27ae60', '#e39c2a', '#7f8c8d', '#8e44ad'],
        vielleicht: ['graffiti', 'fahrrad'],
        koerper: { tiefe: 0.6, breite: 0.7 },
      },
    },
  },
  {
    id: 'sozialbau',
    name: 'Sozialwohnungen',
    category: 'wohnen',
    emoji: '🏢',
    size: [2, 1],
    coins: 560,
    materials: 9,
    effects: { capacity: 30, happiness: -1, klasse: 'arm' },
    needsLevel: 2,
    note: 'Günstiger Wohnraum für viele',
    look: {
      kind: 'bau',
      height: 2.1,
      wall: '#f2cfa6',
      roof: '#9aa3a8',
      accent: '#5d6b80',
      floors: 3,
      stil: {
        dach: 'flach',
        fassade: 'putz',
        fenster: 'normal',
        unten: 'eingang',
        farben: PASTELL,
        extras: ['balkone'],
        vielleicht: ['satellit', 'graffiti', 'muell', 'fahrrad'],
      },
    },
  },
  {
    id: 'mietskaserne',
    name: 'Mietskaserne',
    category: 'wohnen',
    emoji: '🏚️',
    size: [2, 1],
    coins: 640,
    materials: 10,
    effects: { capacity: 34, happiness: -2, klasse: 'arm' },
    needsLevel: 2,
    note: 'Altes Mietshaus, eng und abgewohnt',
    look: {
      kind: 'bau',
      height: 2.5,
      wall: '#b9a58f',
      roof: '#6d5a4c',
      accent: '#4a3a30',
      floors: 4,
      stil: {
        dach: 'sattel',
        fassade: 'ziegel',
        fenster: 'normal',
        unten: 'eingang',
        farben: ABGEWOHNT,
        dachfarben: ['#6d5a4c', '#5d4e44', '#7a5f4c'],
        extras: ['schornstein'],
        vielleicht: ['graffiti', 'satellit', 'muell'],
      },
    },
  },
  {
    id: 'plattenbau',
    name: 'Plattenbau',
    category: 'wohnen',
    emoji: '🏢',
    size: [2, 2],
    coins: 980,
    materials: 16,
    effects: { capacity: 64, happiness: -4, klasse: 'arm', jobs: 2 },
    needsLevel: 3,
    note: 'Fertigteile, sechs Etagen, viel Platz',
    look: {
      kind: 'bau',
      height: 3.4,
      wall: '#d8d3c8',
      roof: '#8e949a',
      accent: '#5a6168',
      floors: 6,
      stil: {
        dach: 'flach',
        fassade: 'platte',
        fenster: 'normal',
        unten: 'eingang',
        farben: ['#d8d3c8', '#cfd6d9', '#e3d7c2', '#c9cfc2', '#dccbb8', '#d6c8d8', '#c8d6e0'],
        extras: ['balkone', 'antenne'],
        vielleicht: ['graffiti', 'satellit', 'muell'],
      },
    },
  },

  // ---------- Mitte ----------
  {
    id: 'bungalow',
    name: 'Bungalow',
    category: 'wohnen',
    emoji: '🏠',
    size: [1, 1],
    coins: 250,
    materials: 4,
    effects: { capacity: 5, happiness: 3, klasse: 'mittel' },
    note: 'Flach, hell, mit Garten',
    look: {
      kind: 'bau',
      height: 0.8,
      wall: '#f3e2c7',
      roof: '#8c4a3a',
      accent: '#5a3a2c',
      floors: 1,
      stil: {
        dach: 'walm',
        fassade: 'putz',
        fenster: 'gross',
        unten: 'tuer',
        farben: HAUSFARBEN,
        dachfarben: [...ZIEGELROT, ...DUNKELDACH],
        extras: ['garten'],
        vielleicht: ['solar', 'briefkasten', 'fahrrad'],
        koerper: { tiefe: 0.62, breite: 0.78 },
      },
    },
  },
  {
    id: 'holzhaus',
    name: 'Holzhaus',
    category: 'wohnen',
    emoji: '🛖',
    size: [1, 1],
    coins: 300,
    materials: 5,
    effects: { capacity: 6, happiness: 4, klasse: 'mittel' },
    note: 'Schwedenrot, Ocker oder Blau – mit weißen Kanten',
    look: {
      kind: 'bau',
      height: 1.15,
      wall: '#a8382c',
      roof: '#3f4652',
      accent: '#f4f1ea',
      floors: 1,
      stil: {
        dach: 'sattel',
        fassade: 'holz',
        fenster: 'normal',
        unten: 'tuer',
        farben: HOLZFARBEN,
        dachfarben: DUNKELDACH,
        extras: ['schornstein', 'fensterlaeden'],
        vielleicht: ['garten', 'briefkasten'],
        koerper: { tiefe: 0.7, breite: 0.72 },
      },
    },
  },
  {
    id: 'fachwerkhaus',
    name: 'Fachwerkhaus',
    category: 'wohnen',
    emoji: '🏡',
    size: [1, 1],
    coins: 390,
    materials: 6,
    effects: { capacity: 8, happiness: 4, klasse: 'mittel' },
    needsLevel: 2,
    note: 'Dunkles Gebälk, helle Felder, steiles Dach',
    look: {
      kind: 'bau',
      height: 1.45,
      wall: '#f4ecd8',
      roof: '#8c3b2c',
      accent: '#4a2e22',
      floors: 2,
      stil: {
        dach: 'sattel',
        fassade: 'fachwerk',
        fenster: 'klein',
        unten: 'tuer',
        farben: ['#f4ecd8', '#efe3c8', '#f7efe2', '#f0e6d2', '#f6e8d6'],
        dachfarben: ['#8c3b2c', '#6b4a3a', '#9c4a3a', '#7a3f30'],
        extras: ['schornstein', 'fensterlaeden'],
        vielleicht: ['efeu', 'garten', 'briefkasten'],
      },
    },
  },
  {
    id: 'doppelhaus',
    name: 'Doppelhaus',
    category: 'wohnen',
    emoji: '🏘️',
    size: [2, 1],
    coins: 470,
    materials: 7,
    effects: { capacity: 14, happiness: 2, klasse: 'mittel' },
    note: 'Zwei Familien, ein Dach',
    look: {
      kind: 'bau',
      height: 1.35,
      wall: '#efd9bd',
      roof: '#a8563c',
      accent: '#7c3f2c',
      floors: 2,
      stil: {
        dach: 'sattel',
        fassade: 'putz',
        fenster: 'normal',
        unten: 'tuer',
        farben: HAUSFARBEN,
        dachfarben: [...ZIEGELROT, ...SCHIEFER],
        extras: ['schornstein'],
        vielleicht: ['solar', 'garten', 'fensterlaeden', 'fahrrad', 'briefkasten'],
      },
    },
  },
  {
    id: 'landhaus',
    name: 'Landhaus',
    category: 'wohnen',
    emoji: '🏡',
    size: [2, 1],
    coins: 640,
    materials: 9,
    effects: { capacity: 10, happiness: 6, klasse: 'mittel' },
    needsLevel: 3,
    note: 'Naturstein, Walmdach, großer Garten',
    look: {
      kind: 'bau',
      height: 1.3,
      wall: '#d9cdb8',
      roof: '#7a4a3a',
      accent: '#4f3a2c',
      floors: 2,
      stil: {
        dach: 'walm',
        fassade: 'stein',
        fenster: 'normal',
        unten: 'tuer',
        farben: ['#d9cdb8', '#cfc4ad', '#e3d8c3', '#c9bfa9'],
        dachfarben: [...ZIEGELROT, '#6b4a3a'],
        extras: ['garten', 'schornstein'],
        vielleicht: ['efeu', 'fensterlaeden', 'solar'],
        koerper: { tiefe: 0.64, breite: 0.86 },
      },
    },
  },
  {
    id: 'altbau',
    name: 'Altbau',
    category: 'wohnen',
    emoji: '🏛️',
    size: [1, 1],
    coins: 720,
    materials: 11,
    effects: { capacity: 20, happiness: 3, klasse: 'mittel' },
    needsLevel: 4,
    note: 'Gründerzeit: hohe Decken, Stuck, Mansarddach',
    look: {
      kind: 'bau',
      height: 2.7,
      wall: '#e8d8b8',
      roof: '#4f5864',
      accent: '#6d5a4a',
      floors: 4,
      stil: {
        dach: 'mansard',
        fassade: 'stein',
        fenster: 'bogen',
        unten: 'eingang',
        farben: GRUENDERZEIT,
        dachfarben: SCHIEFER,
        extras: ['balkone', 'gaube'],
        vielleicht: ['efeu', 'schornstein', 'fahrrad'],
      },
    },
  },
  {
    id: 'genossenschaft',
    name: 'Genossenschaftsbau',
    category: 'wohnen',
    emoji: '🏘️',
    size: [2, 2],
    coins: 1300,
    materials: 20,
    effects: { capacity: 52, happiness: 1, klasse: 'mittel' },
    needsLevel: 4,
    note: 'Klinker, Walmdach, Balkone zum Hof',
    look: {
      kind: 'bau',
      height: 2.5,
      wall: '#b5654a',
      roof: '#6b3f30',
      accent: '#4a2e24',
      floors: 4,
      stil: {
        dach: 'walm',
        fassade: 'ziegel',
        fenster: 'normal',
        unten: 'eingang',
        farben: ['#b5654a', '#a85a42', '#c07a5a', '#9c5a48', '#b88a6a'],
        dachfarben: ['#6b3f30', '#5a3a2c', '#4f5864'],
        extras: ['balkone'],
        vielleicht: ['solar', 'fahrrad', 'satellit'],
      },
    },
  },
  {
    id: 'studentenwohnheim',
    name: 'Studentenwohnheim',
    category: 'wohnen',
    emoji: '🎒',
    size: [2, 1],
    coins: 780,
    materials: 12,
    effects: { capacity: 36, happiness: 2, education: 2, klasse: 'mittel' },
    needsLevel: 5,
    note: 'Viele kleine Zimmer, noch mehr Fahrräder',
    look: {
      kind: 'bau',
      height: 2.2,
      wall: '#f4d35e',
      roof: '#6d7a86',
      accent: '#34495e',
      floors: 4,
      stil: {
        dach: 'flach',
        fassade: 'putz',
        fenster: 'band',
        unten: 'eingang',
        farben: ['#f4d35e', '#ee964b', '#7bc6cc', '#a0c878', '#f28482', '#b8a9e0'],
        extras: ['fahrrad'],
        vielleicht: ['graffiti', 'solar'],
      },
    },
  },
  {
    id: 'seniorenresidenz',
    name: 'Seniorenresidenz',
    category: 'wohnen',
    emoji: '👵',
    size: [2, 2],
    coins: 1500,
    materials: 22,
    effects: { capacity: 40, happiness: 5, jobs: 8, klasse: 'mittel' },
    needsLevel: 6,
    note: 'Ruhig, gepflegt, mit Garten und Balkonen',
    look: {
      kind: 'bau',
      height: 2.1,
      wall: '#f1e6d2',
      roof: '#8c5a4a',
      accent: '#5a3a2c',
      floors: 3,
      stil: {
        dach: 'walm',
        fassade: 'putz',
        fenster: 'normal',
        unten: 'eingang',
        farben: ['#f1e6d2', '#e8efe4', '#f4e8e0', '#e6ecf0'],
        dachfarben: ZIEGELROT,
        extras: ['balkone', 'garten'],
        vielleicht: ['solar', 'efeu'],
        koerper: { tiefe: 0.7, breite: 0.9 },
      },
    },
  },

  // ---------- Wohlhabend ----------
  {
    id: 'stadtvilla',
    name: 'Stadtvilla',
    category: 'wohnen',
    emoji: '🏰',
    size: [1, 1],
    coins: 1250,
    materials: 16,
    effects: { capacity: 6, happiness: 6, klasse: 'reich' },
    needsLevel: 5,
    note: 'Zeltdach, Rundbögen, gepflegter Garten',
    look: {
      kind: 'bau',
      height: 1.8,
      wall: '#fbf8f1',
      roof: '#4f5864',
      accent: '#8c7a5a',
      floors: 2,
      stil: {
        dach: 'zelt',
        fassade: 'putz',
        fenster: 'bogen',
        unten: 'tuer',
        farben: [...EDEL, '#f2e3c6', '#e8dccb'],
        dachfarben: [...SCHIEFER, '#8c4a3a'],
        extras: ['garten', 'gaube'],
        vielleicht: ['efeu', 'fensterlaeden', 'briefkasten'],
        koerper: { tiefe: 0.66, breite: 0.74 },
      },
    },
  },
  {
    id: 'loft',
    name: 'Loft',
    category: 'wohnen',
    emoji: '🏭',
    size: [2, 1],
    coins: 2100,
    materials: 26,
    effects: { capacity: 16, happiness: 8, klasse: 'reich' },
    needsLevel: 7,
    note: 'Alte Fabrik, große Fenster, Dachterrasse',
    look: {
      kind: 'bau',
      height: 1.9,
      wall: '#a85a42',
      roof: '#4a4f58',
      accent: '#2c3036',
      floors: 3,
      stil: {
        dach: 'saege',
        fassade: 'ziegel',
        fenster: 'gross',
        unten: 'eingang',
        farben: ['#a85a42', '#9c5a48', '#b86a4a', '#8c4f3c'],
        dachfarben: ['#4a4f58', '#3c4048'],
        extras: ['dachterrasse'],
        vielleicht: ['efeu', 'fahrrad', 'solar'],
      },
    },
  },
  {
    id: 'penthouse',
    name: 'Penthouse-Haus',
    category: 'wohnen',
    emoji: '🌆',
    size: [1, 1],
    coins: 2600,
    materials: 30,
    effects: { capacity: 12, happiness: 7, klasse: 'reich' },
    needsLevel: 9,
    note: 'Glas bis oben, Terrasse über der Stadt',
    look: {
      kind: 'bau',
      height: 3.6,
      wall: '#8fb3c8',
      roof: '#5f6f7a',
      accent: '#2c3e50',
      floors: 6,
      stil: {
        dach: 'flach',
        fassade: 'glas',
        fenster: 'gross',
        unten: 'eingang',
        farben: ['#8fb3c8', '#9ec0c9', '#a9b8c9', '#8aa6b8', '#b0c4cc'],
        extras: ['dachterrasse', 'balkone'],
        vielleicht: ['antenne', 'solar'],
      },
    },
  },
  {
    id: 'moderne_villa',
    name: 'Moderne Villa',
    category: 'wohnen',
    emoji: '🏝️',
    size: [2, 2],
    coins: 3300,
    materials: 36,
    effects: { capacity: 8, happiness: 12, klasse: 'reich' },
    needsLevel: 8,
    note: 'Weißer Kubus, Glasfront, Pool im Garten',
    look: {
      kind: 'bau',
      height: 1.5,
      wall: '#f7f7f2',
      roof: '#d6d9dc',
      accent: '#3a3f46',
      floors: 2,
      stil: {
        dach: 'flach',
        fassade: 'putz',
        fenster: 'gross',
        unten: 'tuer',
        farben: ['#f7f7f2', '#e9e6df', '#dfe4e6', '#f1ebe1', '#e6e1d8'],
        extras: ['pool', 'garten', 'dachterrasse'],
        vielleicht: ['solar'],
        koerper: { tiefe: 0.52, breite: 0.78 },
      },
    },
  },

  // ---------- Superreich ----------
  {
    id: 'anwesen',
    name: 'Anwesen',
    category: 'wohnen',
    emoji: '🏰',
    size: [2, 2],
    coins: 9000,
    materials: 90,
    effects: { capacity: 4, happiness: 15, klasse: 'superreich' },
    needsLevel: 12,
    note: 'Säulen, Park, Pool – hier wohnen Milliardäre',
    look: {
      kind: 'bau',
      height: 2.1,
      wall: '#f4efe4',
      roof: '#4f5864',
      accent: '#b8962e',
      floors: 2,
      stil: {
        dach: 'walm',
        fassade: 'stein',
        fenster: 'bogen',
        unten: 'eingang',
        farben: ['#f4efe4', '#efe6d4', '#f7f1e6', '#e9dfcf'],
        dachfarben: SCHIEFER,
        extras: ['pool', 'garten', 'saeulen', 'schornstein'],
        vielleicht: ['efeu', 'fahnenmast'],
        koerper: { tiefe: 0.56, breite: 0.82 },
      },
    },
  },
  {
    id: 'glasvilla',
    name: 'Glasvilla',
    category: 'wohnen',
    emoji: '💎',
    size: [2, 2],
    coins: 14000,
    materials: 120,
    effects: { capacity: 4, happiness: 18, klasse: 'superreich' },
    needsLevel: 15,
    note: 'Ganz aus Glas, mit Pool und Landeplatz',
    look: {
      kind: 'bau',
      height: 1.7,
      wall: '#9cc4d4',
      roof: '#dfe6ea',
      accent: '#1f2d3a',
      floors: 2,
      stil: {
        dach: 'flach',
        fassade: 'glas',
        fenster: 'gross',
        unten: 'tuer',
        farben: ['#9cc4d4', '#a6c8cf', '#b4ccd8', '#94bccc'],
        extras: ['pool', 'heli', 'garten'],
        koerper: { tiefe: 0.5, breite: 0.8 },
      },
    },
  },
  {
    id: 'luxusturm',
    name: 'Luxus-Wohnturm',
    category: 'wohnen',
    emoji: '🏙️',
    size: [2, 2],
    coins: 16000,
    materials: 150,
    effects: { capacity: 16, happiness: 10, jobs: 10, klasse: 'superreich' },
    needsLevel: 16,
    note: 'Zwölf Etagen Glas, oben der Hubschrauber',
    look: {
      kind: 'bau',
      height: 7,
      wall: '#7fa6bd',
      roof: '#4f5d68',
      accent: '#1f2d3a',
      floors: 12,
      stil: {
        dach: 'flach',
        fassade: 'glas',
        fenster: 'gross',
        unten: 'eingang',
        farben: ['#7fa6bd', '#8fb0c0', '#6f98b0', '#9ab4c4', '#86a0b8'],
        extras: ['heli', 'balkone', 'antenne'],
        koerper: { tiefe: 0.72, breite: 0.72 },
      },
    },
  },
]
