// 🇫🇷 Französisch – die Sprache, die man hören muss, um sie zu können.
// Deshalb steht hier der Klang im Mittelpunkt: Aussprache, Liaison, Nasale – und Gespräche,
// in denen man sich traut. Geschrieben wird Französisch anders, als es klingt; genau das übt
// dieser Kurs von der ersten Minute an.
import type { KursDef } from '../../typen'

export const FRANZOESISCH: KursDef = {
  id: 'franzoesisch',
  titel: 'Französisch',
  emoji: '🇫🇷',
  claim: 'Hören, trauen, sprechen.',
  domain: 'franzoesisch',
  wissen: 'Französisch-Wissen',
  sprache: 'fr-FR',
  thema: 'kurs-franzoesisch',
  module: [
    { id: 'fr.m1', titel: 'Bonjour!', emoji: '👋', text: 'Begrüßen, sich vorstellen, höflich sein' },
    { id: 'fr.m2', titel: 'Klang und Schrift', emoji: '👄', text: 'Stumme Endungen, Nasale und die Liaison' },
    { id: 'fr.m3', titel: 'Zahlen und Zeit', emoji: '🕒', text: 'Zahlen, Uhrzeit, Tage und Termine' },
    { id: 'fr.m4', titel: 'Im Café', emoji: '☕', text: 'Bestellen, bezahlen, sich wohlfühlen' },
    { id: 'fr.m5', titel: 'Einkaufen', emoji: '🥖', text: 'Bäckerei, Markt, Mengen und Preise' },
    { id: 'fr.m6', titel: 'Unterwegs', emoji: '🚄', text: 'Bahn, Weg fragen, Hotel' },
    { id: 'fr.m7', titel: 'Alltag', emoji: '🏠', text: 'Tagesablauf, Wetter, Freizeit' },
    { id: 'fr.m8', titel: 'Menschen und Meinungen', emoji: '💭', text: 'Beschreiben, mögen, vorschlagen' },
    { id: 'fr.m9', titel: 'Höflich bleiben', emoji: '🎩', text: 'Tu oder vous, bitten, entschuldigen' },
    { id: 'fr.m10', titel: 'Feinheiten', emoji: '🏅', text: 'Falsche Freunde und typische Stolperstellen' },
  ],
  ziele: [
    { id: 'fr.greet', titel: 'Begrüßen und verabschieden', modul: 'fr.m1' },
    { id: 'fr.intro', titel: 'Sich vorstellen', modul: 'fr.m1' },
    { id: 'fr.hoeflich', titel: 'Bitte und danke', modul: 'fr.m1' },
    { id: 'fr.stumm', titel: 'Stumme Endungen', modul: 'fr.m2' },
    { id: 'fr.nasal', titel: 'Nasale Laute', modul: 'fr.m2' },
    { id: 'fr.liaison', titel: 'Liaison', modul: 'fr.m2' },
    { id: 'fr.zahlen', titel: 'Zahlen', modul: 'fr.m3' },
    { id: 'fr.uhrzeit', titel: 'Uhrzeit und Tage', modul: 'fr.m3' },
    { id: 'fr.cafe', titel: 'Bestellen', modul: 'fr.m4' },
    { id: 'fr.zahlenbitte', titel: 'Bezahlen', modul: 'fr.m4' },
    { id: 'fr.laden', titel: 'Im Laden', modul: 'fr.m5' },
    { id: 'fr.mengen', titel: 'Mengen und Preise', modul: 'fr.m5' },
    { id: 'fr.bahn', titel: 'Bahn und Ticket', modul: 'fr.m6' },
    { id: 'fr.weg', titel: 'Nach dem Weg fragen', modul: 'fr.m6' },
    { id: 'fr.hotel', titel: 'Im Hotel', modul: 'fr.m6' },
    { id: 'fr.tag', titel: 'Tagesablauf', modul: 'fr.m7' },
    { id: 'fr.wetter', titel: 'Wetter und Small Talk', modul: 'fr.m7' },
    { id: 'fr.freizeit', titel: 'Freizeit', modul: 'fr.m7' },
    { id: 'fr.beschreiben', titel: 'Beschreiben', modul: 'fr.m8' },
    { id: 'fr.meinung', titel: 'Meinung sagen', modul: 'fr.m8' },
    { id: 'fr.vorschlag', titel: 'Vorschlagen und verabreden', modul: 'fr.m8' },
    { id: 'fr.tuvous', titel: 'Tu oder vous', modul: 'fr.m9' },
    { id: 'fr.bitten', titel: 'Höflich bitten', modul: 'fr.m9' },
    { id: 'fr.entschuldigen', titel: 'Entschuldigen', modul: 'fr.m9' },
    { id: 'fr.fauxamis', titel: 'Falsche Freunde', modul: 'fr.m10' },
    { id: 'fr.fallen', titel: 'Typische Stolperstellen', modul: 'fr.m10' },
  ],
  spiele: [
    {
      id: 'fr.aussprache',
      mechanik: 'aussprache',
      name: 'Wie klingt das?',
      emoji: '👄',
      kurz: 'Geschrieben ist nicht gesprochen.',
      anleitung: 'Wähle, wie das Wort wirklich klingt. Danach siehst du die Lautschrift und hörst es.',
      tempo: 'genau',
      runden: 4,
      bitte: {
        wer: [
          { name: 'Chloé', emoji: '👧', rolle: 'Austauschschülerin' },
          { name: 'Marc', emoji: '🧑‍🍳', rolle: 'Bäcker' },
        ],
        saetze: [
          'Ich soll morgen französische Namen vorlesen – übst du die Aussprache mit mir?',
          'Auf der Karte stehen Wörter, die ich nicht aussprechen kann. Hilfst du?',
        ],
      },
    },
    {
      id: 'fr.vorstellung',
      mechanik: 'dialog',
      name: 'Erste Begegnung',
      emoji: '🤝',
      kurz: 'Sich trauen, den Anfang zu machen.',
      anleitung: 'Antworte so, wie man es in Frankreich wirklich sagt. Dein Gegenüber reagiert darauf.',
      tempo: 'kontext',
      runden: 1,
      lang: true,
      bitte: {
        wer: [{ name: 'Chloé', emoji: '👧', rolle: 'Austauschschülerin' }],
        saetze: ['Morgen kommt meine Gastfamilie an. Üben wir das Vorstellen auf Französisch?'],
      },
    },
    {
      id: 'fr.cafe',
      mechanik: 'dialog',
      name: 'Im Café',
      emoji: '☕',
      kurz: 'Bestellen, ohne zu zeigen.',
      anleitung: 'Du hast ein Ziel: bestellen und bezahlen. Bring das Gespräch höflich dorthin.',
      tempo: 'kontext',
      runden: 1,
      lang: true,
      ab: 2,
      bitte: {
        wer: [{ name: 'Marc', emoji: '🧑‍🍳', rolle: 'Bäcker' }],
        saetze: ['Ich fahre nach Lyon und will dort im Café bestellen können. Üben wir?'],
      },
    },
    {
      id: 'fr.reise',
      mechanik: 'dialog',
      name: 'Unterwegs',
      emoji: '🚄',
      kurz: 'Bahnhof, Hotel, Wegsuche.',
      anleitung: 'Frag nach, bis du weißt, was du wissen musst – höflich und auf Französisch.',
      tempo: 'kontext',
      runden: 1,
      lang: true,
      ab: 3,
      bitte: {
        wer: [{ name: 'Yasmine', emoji: '🧳', rolle: 'Reisende' }],
        saetze: ['Ich muss in Paris umsteigen und habe Angst, etwas falsch zu verstehen. Übst du mit mir?'],
      },
    },
    {
      id: 'fr.antwort',
      mechanik: 'wahl',
      name: 'Was sagt man?',
      emoji: '🗣️',
      kurz: 'Die passende Antwort.',
      anleitung: 'Alle Antworten sind verständlich – aber nur eine passt wirklich in die Situation.',
      tempo: 'kontext',
      runden: 4,
    },
    {
      id: 'fr.hoeren',
      mechanik: 'hoeren',
      name: 'Hören',
      emoji: '👂',
      kurz: 'Verstehen, was gesagt wird.',
      anleitung: 'Höre den Satz – auch langsam – und wähle, was gemeint ist.',
      tempo: 'genau',
      runden: 4,
    },
    {
      id: 'fr.genre',
      mechanik: 'sortieren',
      name: 'Le oder la?',
      emoji: '⚖️',
      kurz: 'Das Geschlecht der Wörter.',
      anleitung: 'Schiebe jedes Wort in sein Fach. Endungen verraten oft, wohin es gehört.',
      tempo: 'schnell',
      runden: 6,
      faecher: [
        { name: 'le', emoji: '🔵' },
        { name: 'la', emoji: '🔴' },
      ],
    },
    {
      id: 'fr.satzbau',
      mechanik: 'bau',
      name: 'Satzbau',
      emoji: '🧱',
      kurz: 'Aus Bausteinen wird ein Satz.',
      anleitung: 'Tippe die Bausteine in der richtigen Reihenfolge an.',
      tempo: 'denken',
      runden: 3,
    },
    {
      id: 'fr.paare',
      mechanik: 'paare',
      name: 'Wortpaare',
      emoji: '🔗',
      kurz: 'Wendung und Bedeutung.',
      anleitung: 'Verbinde jede Wendung mit ihrer Bedeutung: erst links antippen, dann rechts.',
      tempo: 'schnell',
      runden: 5,
      spalten: ['Français', 'Deutsch'],
    },
    {
      id: 'fr.duell',
      mechanik: 'duell',
      name: 'Welcher Satz stimmt?',
      emoji: '🥖',
      kurz: 'Zwei Sätze, einer ist schief.',
      anleitung: 'Beide Sätze sehen französisch aus. Nur einer sagt, was du meinst.',
      tempo: 'schnell',
      runden: 5,
    },
  ],
  laden: () => import('./inhalt').then((m) => m.INHALT),
}
