// 🏦 Banking – der Kurs für alle, die wissen wollen, was mit ihrem Geld passiert.
// Kein Produktkatalog, sondern Handwerk: am Schalter auszahlen, einen Haushalt durchrechnen,
// einen Beleg prüfen, einen Kunden beraten. Alle Fälle sind erfunden.
import type { KursDef } from '../../typen'

export const BANK: KursDef = {
  id: 'bank',
  titel: 'Banking',
  emoji: '🏦',
  claim: 'Verstehen, was mit dem Geld passiert.',
  domain: 'finanzen',
  wissen: 'Finanz-Wissen',
  thema: 'kurs-bank',
  hinweis: 'Alle Namen, Fälle und Konditionen in diesem Kurs sind erfunden. Es geht um das Prinzip – keine Anlage- oder Finanzberatung.',
  module: [
    { id: 'bank.m1', titel: 'Grundlagen', emoji: '🧾', text: 'Konto, Zahlungsverkehr und die wichtigsten Begriffe' },
    { id: 'bank.m2', titel: 'Am Schalter', emoji: '💶', text: 'Auszahlen, einzahlen, verfügbarer Betrag' },
    { id: 'bank.m3', titel: 'Zinsen', emoji: '📈', text: 'Zinsen, Zinseszins und was ein Prozentpunkt ausmacht' },
    { id: 'bank.m4', titel: 'Sparen und Anlegen', emoji: '🪙', text: 'Sparformen, Risiko und Streuung' },
    { id: 'bank.m5', titel: 'Kredit', emoji: '📊', text: 'Haushaltsrechnung, Rate, Tragfähigkeit' },
    { id: 'bank.m6', titel: 'Karten und Konten', emoji: '💳', text: 'Girokonto, Karten, Dispo und Gebühren' },
    { id: 'bank.m7', titel: 'Sicherheit', emoji: '🛡️', text: 'Betrugsmaschen erkennen und richtig reagieren' },
    { id: 'bank.m8', titel: 'Beratung', emoji: '🤝', text: 'Zuhören, prüfen, passend empfehlen' },
  ],
  ziele: [
    { id: 'bank.konto', titel: 'Konto und Zahlungsverkehr', modul: 'bank.m1' },
    { id: 'bank.begriffe', titel: 'Bankbegriffe', modul: 'bank.m1' },
    { id: 'bank.beleg', titel: 'Belege prüfen', modul: 'bank.m1' },
    { id: 'bank.auszahlung', titel: 'Auszahlen', modul: 'bank.m2' },
    { id: 'bank.einzahlung', titel: 'Einzahlen und zählen', modul: 'bank.m2' },
    { id: 'bank.verfuegbar', titel: 'Verfügbarer Betrag', modul: 'bank.m2' },
    { id: 'bank.zins', titel: 'Zinsen rechnen', modul: 'bank.m3' },
    { id: 'bank.zinseszins', titel: 'Zinseszins', modul: 'bank.m3' },
    { id: 'bank.effektiv', titel: 'Effektivzins verstehen', modul: 'bank.m3' },
    { id: 'bank.sparen', titel: 'Sparformen', modul: 'bank.m4' },
    { id: 'bank.risiko', titel: 'Risiko und Streuung', modul: 'bank.m4' },
    { id: 'bank.inflation', titel: 'Inflation', modul: 'bank.m4' },
    { id: 'bank.haushalt', titel: 'Haushaltsrechnung', modul: 'bank.m5' },
    { id: 'bank.rate', titel: 'Rate und Laufzeit', modul: 'bank.m5' },
    { id: 'bank.tragfaehig', titel: 'Tragfähigkeit beurteilen', modul: 'bank.m5' },
    { id: 'bank.giro', titel: 'Girokonto und Karten', modul: 'bank.m6' },
    { id: 'bank.dispo', titel: 'Dispo und Überziehung', modul: 'bank.m6' },
    { id: 'bank.gebuehren', titel: 'Gebühren', modul: 'bank.m6' },
    { id: 'bank.betrug', titel: 'Betrugsmaschen', modul: 'bank.m7' },
    { id: 'bank.daten', titel: 'Daten und PIN', modul: 'bank.m7' },
    { id: 'bank.reaktion', titel: 'Richtig reagieren', modul: 'bank.m7' },
    { id: 'bank.gespraech', titel: 'Beratungsgespräch', modul: 'bank.m8' },
    { id: 'bank.bedarf', titel: 'Bedarf erkennen', modul: 'bank.m8' },
  ],
  spiele: [
    {
      id: 'bank.kunde',
      mechanik: 'fall',
      name: 'Kundenfall',
      emoji: '🤝',
      kurz: 'Zuhören, prüfen, entscheiden.',
      anleitung: 'Prüfe, was du wissen musst – dann entscheide. Wer ohne die wichtigen Befunde rät, liegt schnell daneben.',
      tempo: 'kontext',
      runden: 2,
      lang: true,
      bitte: {
        wer: [
          { name: 'Frau Adam', emoji: '👩‍💼', rolle: 'Filialleiterin' },
          { name: 'Ben', emoji: '🧑‍💼', rolle: 'Azubi' },
        ],
        saetze: [
          'Gleich kommt ein Kunde mit einer kniffligen Frage – übst du den Fall mit mir?',
          'Ich habe morgen Prüfung und muss Kundenfälle können. Hilfst du?',
        ],
      },
    },
    {
      id: 'bank.schalter',
      mechanik: 'kasse',
      name: 'Am Schalter',
      emoji: '💶',
      kurz: 'Geld zählen, ohne sich zu vertun.',
      anleitung: 'Zahle genau aus oder zähle nach – Kundenwünsche gelten auch für die Stückelung.',
      tempo: 'genau',
      runden: 3,
    },
    {
      id: 'bank.kredit',
      mechanik: 'kredit',
      name: 'Kreditfall',
      emoji: '📊',
      kurz: 'Trägt der Haushalt die Rate?',
      anleitung: 'Rechne die Rate aus und beurteile, ob der Haushalt sie wirklich trägt.',
      tempo: 'denken',
      runden: 2,
      lang: true,
      ab: 2,
    },
    {
      id: 'bank.rechner',
      mechanik: 'rechnen',
      name: 'Kopfrechnen',
      emoji: '🧮',
      kurz: 'Zinsen, Raten, Renditen.',
      anleitung: 'Rechne den Betrag aus und tippe ihn ein. Danach siehst du den Rechenweg.',
      tempo: 'denken',
      runden: 3,
    },
    {
      id: 'bank.beleg',
      mechanik: 'dokument',
      name: 'Beleg prüfen',
      emoji: '🧾',
      kurz: 'Ein Fehler versteckt sich.',
      anleitung: 'Irgendwo im Beleg stimmt etwas nicht. Tippe die Zeile an und sag, was dort stehen müsste.',
      tempo: 'genau',
      runden: 1,
    },
    {
      id: 'bank.wissen',
      mechanik: 'wahl',
      name: 'Bankwissen',
      emoji: '🎯',
      kurz: 'Der richtige Begriff.',
      anleitung: 'Eine Frage, vier Antworten. Nur eine stimmt genau.',
      tempo: 'schnell',
      runden: 4,
    },
    {
      id: 'bank.duell',
      mechanik: 'duell',
      name: 'Stimmt das?',
      emoji: '⚖️',
      kurz: 'Zwei Aussagen, eine stimmt.',
      anleitung: 'Beide Sätze klingen plausibel. Nur einer ist richtig.',
      tempo: 'schnell',
      runden: 5,
    },
    {
      id: 'bank.paare',
      mechanik: 'paare',
      name: 'Fachbegriffe',
      emoji: '🔗',
      kurz: 'Begriff und Bedeutung.',
      anleitung: 'Verbinde jeden Begriff mit seiner Bedeutung: erst links antippen, dann rechts.',
      tempo: 'schnell',
      runden: 5,
      spalten: ['Begriff', 'Bedeutung'],
    },
    {
      id: 'bank.masche',
      mechanik: 'sortieren',
      name: 'Echt oder Masche?',
      emoji: '🛡️',
      kurz: 'Nachricht einsortieren.',
      anleitung: 'Echte Bankkommunikation oder Betrugsversuch? Schiebe jede Nachricht in ihr Fach.',
      tempo: 'schnell',
      runden: 5,
      faecher: [
        { name: 'Echt', emoji: '✅' },
        { name: 'Masche', emoji: '🚨' },
      ],
    },
  ],
  laden: () => import('./inhalt').then((m) => m.INHALT),
}
