export interface NeuMotiv {
  id: string
  name: string
  gruppe: 'autos' | 'marken' | 'rap'
  hinweis: string
  antwort?: string
  titel: string[]
  suche: string
}

export const NEU: NeuMotiv[] = [
  { id: 'renault', name: 'Renault', gruppe: 'autos', hinweis: 'Die Raute ist das Zeichen aus Boulogne-Billancourt.', titel: ['Renault Clio V', 'Renault Clio'], suche: 'Renault Clio front photo' },
  { id: 'peugeot', name: 'Peugeot', gruppe: 'autos', hinweis: 'Der Löwe auf den Hinterbeinen gehört zum Haus aus Sochaux.', titel: ['Peugeot 208'], suche: 'Peugeot 208 front photo' },
  { id: 'citroen', name: 'Citroën', gruppe: 'autos', hinweis: 'Die Doppelwinkel erinnern an Zahnräder.', titel: ['Citroën C3'], suche: 'Citroen C3 front photo' },
  { id: 'skoda', name: 'Škoda', gruppe: 'autos', hinweis: 'Der geflügelte Pfeil kommt aus Mladá Boleslav.', titel: ['Škoda Octavia IV', 'Škoda Octavia'], suche: 'Skoda Octavia front photo' },
  { id: 'seat', name: 'Seat', gruppe: 'autos', hinweis: 'Das S gehört zur spanischen Marke aus Martorell.', titel: ['Seat Leon IV', 'Seat Leon'], suche: 'Seat Leon front photo' },
  { id: 'volvo', name: 'Volvo', gruppe: 'autos', hinweis: 'Der Kreis mit dem Pfeil steht für Eisen, das Zeichen aus Göteborg.', titel: ['Volvo XC40'], suche: 'Volvo XC40 front photo' },
  { id: 'hyundai', name: 'Hyundai', gruppe: 'autos', hinweis: 'Das schräge H im Oval kommt aus Seoul.', titel: ['Hyundai Tucson'], suche: 'Hyundai Tucson front photo' },
  { id: 'kia', name: 'Kia', gruppe: 'autos', hinweis: 'Der Schriftzug im Oval gehört zum koreanischen Schwesterhaus von Hyundai.', titel: ['Kia Sportage'], suche: 'Kia Sportage front photo' },
  { id: 'mazda', name: 'Mazda', gruppe: 'autos', hinweis: 'Das M erinnert an Flügel, der Name an den Lichtgott Ahura Mazda.', titel: ['Mazda3'], suche: 'Mazda3 front photo' },
  { id: 'nissan', name: 'Nissan', gruppe: 'autos', hinweis: 'Der Balken im Kreis ist das Zeichen aus Yokohama.', titel: ['Nissan Qashqai'], suche: 'Nissan Qashqai front photo' },
  { id: 'jeep', name: 'Jeep', gruppe: 'autos', hinweis: 'Die sieben Schlitze im Kühler kommen vom Willys aus dem Zweiten Weltkrieg.', titel: ['Jeep Wrangler'], suche: 'Jeep Wrangler photo' },
  { id: 'chevrolet', name: 'Chevrolet', gruppe: 'autos', hinweis: 'Das goldene Kreuz ist die Fliege aus dem Tapetenmuster eines Hotels in Paris.', titel: ['Chevrolet Camaro'], suche: 'Chevrolet Camaro front photo' },
  { id: 'lamborghini', name: 'Lamborghini', gruppe: 'autos', hinweis: 'Der Stier steht für Ferruccio Lamborghinis Sternzeichen.', titel: ['Lamborghini Huracán'], suche: 'Lamborghini Huracan photo' },
  { id: 'maserati', name: 'Maserati', gruppe: 'autos', hinweis: 'Der Dreizack ist der von Neptun, dem Wahrzeichen von Bologna.', titel: ['Maserati Ghibli'], suche: 'Maserati front photo' },
  { id: 'bentley', name: 'Bentley', gruppe: 'autos', hinweis: 'Das geflügelte B gehört zu den Wagen aus Crewe.', titel: ['Bentley Continental GT'], suche: 'Bentley Continental GT photo' },
  { id: 'jaguar', name: 'Jaguar', gruppe: 'autos', hinweis: 'Der springende Jaguar, der Raubkatzen-Name aus Coventry.', titel: ['Jaguar F-Type'], suche: 'Jaguar F-Type photo' },
  { id: 'mini', name: 'Mini', gruppe: 'autos', hinweis: 'Der kleine Wagen aus Oxford, heute ein Haus von BMW.', titel: ['Mini Hatch', 'Mini (BMW)'], suche: 'Mini Cooper front photo' },
  { id: 'alfa', name: 'Alfa Romeo', gruppe: 'autos', hinweis: 'Das rote Kreuz und die Schlange sind das Wappen von Mailand.', titel: ['Alfa Romeo Giulia (952)', 'Alfa Romeo Giulia'], suche: 'Alfa Romeo Giulia photo' },
  { id: 'dacia', name: 'Dacia', gruppe: 'autos', hinweis: 'Das blaue Schild gehört zur rumänischen Marke aus Pitești.', titel: ['Dacia Sandero'], suche: 'Dacia Sandero front photo' },
  { id: 'bugatti', name: 'Bugatti', gruppe: 'autos', hinweis: 'Das rote Oval mit den 60 Perlen erinnert an Ettore Bugatti.', titel: ['Bugatti Chiron'], suche: 'Bugatti Chiron photo' },
  { id: 'mclaren', name: 'McLaren', gruppe: 'autos', hinweis: 'Der Keil kommt vom Rennstall aus Woking.', titel: ['McLaren 720S'], suche: 'McLaren 720S photo' },
  { id: 'lexus', name: 'Lexus', gruppe: 'autos', hinweis: 'Das L im Oval ist die Edelmarke von Toyota.', titel: ['Lexus RX'], suche: 'Lexus RX front photo' },
  { id: 'cupra', name: 'Cupra', gruppe: 'autos', hinweis: 'Die Kupferspitze, die Sportmarke von Seat aus Barcelona.', titel: ['Cupra Formentor'], suche: 'Cupra Formentor photo' },
  { id: 'smart', name: 'Smart', gruppe: 'autos', hinweis: 'Der kurze Zweisitzer, der Name mischt Swatch und Mercedes.', titel: ['Smart Fortwo'], suche: 'Smart Fortwo photo' },
  { id: 'subaru', name: 'Subaru', gruppe: 'autos', hinweis: 'Die sechs Sterne stehen für das Sternbild der Plejaden.', titel: ['Subaru Impreza'], suche: 'Subaru Impreza front photo' },
  { id: 'landrover', name: 'Land Rover', gruppe: 'autos', hinweis: 'Das grüne Oval gehört zu den Geländewagen aus Solihull.', titel: ['Land Rover Defender'], suche: 'Land Rover Defender photo' },
  { id: 'rolls', name: 'Rolls-Royce', gruppe: 'autos', hinweis: 'Die Kühlerfigur Spirit of Ecstasy steht über dem Pantheon-Kühler.', titel: ['Rolls-Royce Phantom VIII', 'Rolls-Royce Phantom'], suche: 'Rolls-Royce Phantom photo' },
  { id: 'suzuki', name: 'Suzuki', gruppe: 'autos', hinweis: 'Das S gehört zum Haus aus Hamamatsu, bekannt auch für Motorräder.', titel: ['Suzuki Swift'], suche: 'Suzuki Swift front photo' },

  { id: 'pepsi', name: 'Pepsi', gruppe: 'marken', hinweis: 'Rot, Weiß und Blau auf der Flasche, der große Rivale von Coca-Cola.', titel: ['Pepsi'], suche: 'Pepsi bottle' },
  { id: 'fanta', name: 'Fanta', gruppe: 'marken', hinweis: 'Die Orange, in Deutschland im Zweiten Weltkrieg entstanden, weil Cola-Sirup fehlte.', titel: ['Fanta'], suche: 'Fanta bottle orange' },
  { id: 'sprite', name: 'Sprite', gruppe: 'marken', hinweis: 'Die klare Zitrone-Limette-Brause mit dem grünen Schriftzug.', titel: ['Sprite (Getränk)'], suche: 'Sprite soda bottle' },
  { id: 'redbull', name: 'Red Bull', gruppe: 'marken', hinweis: 'Die schlanke Dose mit den zwei roten Stieren.', titel: ['Red Bull'], suche: 'Red Bull can' },
  { id: 'starbucks', name: 'Starbucks', gruppe: 'marken', hinweis: 'Die Sirene mit der Krone, die Kette aus Seattle.', titel: ['Starbucks'], suche: 'Starbucks cup' },
  { id: 'burgerking', name: 'Burger King', gruppe: 'marken', hinweis: 'Die Brötchen-Hälften als Logo, der Whopper ist der Klassiker.', titel: ['Burger King'], suche: 'Burger King restaurant' },
  { id: 'kfc', name: 'KFC', gruppe: 'marken', hinweis: 'Kentucky Fried Chicken, das Gesicht von Colonel Sanders.', titel: ['Kentucky Fried Chicken'], suche: 'KFC restaurant bucket' },
  { id: 'subway', name: 'Subway', gruppe: 'marken', hinweis: 'Die gelben Pfeile, belegte Baguettes nach Wahl.', titel: ['Subway (Restaurantkette)'], suche: 'Subway restaurant storefront' },
  { id: 'lidl', name: 'Lidl', gruppe: 'marken', hinweis: 'Der blaue Kreis mit dem gelben Rand, der Discounter aus Neckarsulm.', titel: ['Lidl'], suche: 'Lidl supermarket exterior' },
  { id: 'aldi', name: 'Aldi', gruppe: 'marken', hinweis: 'Der Name setzt sich aus Albrecht und Diskont zusammen.', titel: ['Aldi'], suche: 'Aldi store exterior' },
  { id: 'rewe', name: 'Rewe', gruppe: 'marken', hinweis: 'Die Revisionsverband-Einkaufsgenossenschaft, der Supermarkt mit dem roten Schriftzug.', titel: ['Rewe'], suche: 'REWE supermarket exterior' },
  { id: 'edeka', name: 'Edeka', gruppe: 'marken', hinweis: 'Der Einkaufsgenossenschaft Deutscher Kolonialwarenhändler, heute die gelbe Marke.', titel: ['Edeka'], suche: 'Edeka supermarket exterior' },
  { id: 'dm', name: 'dm', gruppe: 'marken', hinweis: 'Die Drogerie von Götz Werner, das Logo sind die Kleinbuchstaben dm.', titel: ['Dm-drogerie markt'], suche: 'dm drogerie store' },
  { id: 'rossmann', name: 'Rossmann', gruppe: 'marken', hinweis: 'Die Drogeriekette aus Burgwedel, gegründet von Dirk Rossmann.', titel: ['Rossmann (Handelskette)'], suche: 'Rossmann drugstore' },
  { id: 'puma', name: 'Puma', gruppe: 'marken', hinweis: 'Der springende Puma, gegründet von Rudolf Dassler, dem Bruder von Adi.', titel: ['Puma (Unternehmen)'], suche: 'Puma shoe' },
  { id: 'samsung', name: 'Samsung', gruppe: 'marken', hinweis: 'Das blaue Oval, die Telefone und Fernseher aus Suwon.', titel: ['Samsung Galaxy S23', 'Samsung Galaxy'], suche: 'Samsung Galaxy phone' },
  { id: 'nintendo', name: 'Nintendo', gruppe: 'marken', hinweis: 'Die Konsole mit den abnehmbaren Controllern, das Haus aus Kyōto.', titel: ['Nintendo Switch'], suche: 'Nintendo Switch console' },
  { id: 'playstation', name: 'PlayStation', gruppe: 'marken', hinweis: 'Das PS-Zeichen von Sony, die Konsole aus Tokio.', titel: ['PlayStation 5'], suche: 'PlayStation 5 console' },
  { id: 'xbox', name: 'Xbox', gruppe: 'marken', hinweis: 'Die Kugel von Microsoft, die Konsole aus Redmond.', titel: ['Xbox Series X'], suche: 'Xbox Series X console' },
  { id: 'ritter', name: 'Ritter Sport', gruppe: 'marken', hinweis: 'Die quadratische Tafel aus Waldenbuch.', titel: ['Ritter Sport'], suche: 'Ritter Sport chocolate' },
  { id: 'maggi', name: 'Maggi', gruppe: 'marken', hinweis: 'Die gelb-rote Würze, erfunden von Julius Maggi in der Schweiz.', titel: ['Maggi'], suche: 'Maggi seasoning bottle' },
  { id: 'persil', name: 'Persil', gruppe: 'marken', hinweis: 'Das Waschmittel von Henkel, der Name mischt Perborat und Silikat.', titel: ['Persil (Marke)'], suche: 'Persil detergent' },
  { id: 'kinder', name: 'Kinder Schokolade', gruppe: 'marken', hinweis: 'Der Milch-und-Kakao-Riegel von Ferrero mit dem Kind auf der Packung.', titel: ['Kinder Schokolade'], suche: 'Kinder chocolate bar' },
  { id: 'oreo', name: 'Oreo', gruppe: 'marken', hinweis: 'Der schwarze Keks mit der weißen Creme, von Nabisco.', titel: ['Oreo'], suche: 'Oreo cookie' },
  { id: 'pringles', name: 'Pringles', gruppe: 'marken', hinweis: 'Die gestapelten Chips in der Dose, das Gesicht mit dem Schnurrbart.', titel: ['Pringles'], suche: 'Pringles can' },
  { id: 'toblerone', name: 'Toblerone', gruppe: 'marken', hinweis: 'Die Dreiecksschokolade aus Bern, das Matterhorn auf der Packung.', titel: ['Toblerone'], suche: 'Toblerone chocolate' },
  { id: 'ferrero', name: 'Ferrero Rocher', gruppe: 'marken', hinweis: 'Die goldene Kugel mit der Haselnuss, aus Alba in Piemont.', titel: ['Ferrero Rocher'], suche: 'Ferrero Rocher' },
  { id: 'duplo', name: 'Duplo', gruppe: 'marken', hinweis: 'Der Riegel mit Waffel, Creme und Schokolade, ebenfalls von Ferrero.', titel: ['Duplo (Schokolade)'], suche: 'Duplo chocolate bar' },
  { id: 'hanuta', name: 'Hanuta', gruppe: 'marken', hinweis: 'Haselnusstafeln, der Name kürzt Haselnusstafel ab.', titel: ['Hanuta'], suche: 'Hanuta wafer' },
  { id: 'monster', name: 'Monster Energy', gruppe: 'marken', hinweis: 'Die grüne Dose mit der Klaue.', titel: ['Monster Energy'], suche: 'Monster Energy can' },
  { id: 'heineken', name: 'Heineken', gruppe: 'marken', hinweis: 'Das grüne Flaschenetikett, die Brauerei aus Amsterdam.', titel: ['Heineken (Bier)'], suche: 'Heineken bottle' },
  { id: 'bitburger', name: 'Bitburger', gruppe: 'marken', hinweis: 'Bitte ein Bit, die Brauerei aus Bitburg in der Eifel.', titel: ['Bitburger'], suche: 'Bitburger beer bottle' },
  { id: 'lufthansa', name: 'Lufthansa', gruppe: 'marken', hinweis: 'Der Kranich im Kreis, die Airline aus Köln.', titel: ['Lufthansa'], suche: 'Lufthansa airplane' },
  { id: 'bahn', name: 'Deutsche Bahn', gruppe: 'marken', hinweis: 'Die Buchstaben DB, die Züge in Verkehrsrot.', titel: ['Deutsche Bahn'], suche: 'Deutsche Bahn train ICE' },
  { id: 'dhl', name: 'DHL', gruppe: 'marken', hinweis: 'Gelb und Rot, der Paketdienst der Post.', titel: ['DHL'], suche: 'DHL delivery van' },
  { id: 'playmobil', name: 'Playmobil', gruppe: 'marken', hinweis: 'Die kleinen Figuren mit dem Lächeln, von geobra Brandstätter.', titel: ['Playmobil'], suche: 'Playmobil figures' },
  { id: 'hm', name: 'H&M', gruppe: 'marken', hinweis: 'Hennes & Mauritz, die Modekette aus Schweden.', titel: ['H&M'], suche: 'H&M store exterior' },
  { id: 'decathlon', name: 'Decathlon', gruppe: 'marken', hinweis: 'Der Sportmarkt aus Frankreich, benannt nach dem Zehnkampf.', titel: ['Decathlon'], suche: 'Decathlon store' },
  { id: 'bosch', name: 'Bosch', gruppe: 'marken', hinweis: 'Der Anker im Kreis, das Haus von Robert Bosch in Gerlingen.', titel: ['Robert Bosch GmbH'], suche: 'Bosch power drill' },
  { id: 'philips', name: 'Philips', gruppe: 'marken', hinweis: 'Das Schild mit den Sternen, gegründet in Eindhoven.', titel: ['Philips'], suche: 'Philips product' },
  { id: 'dyson', name: 'Dyson', gruppe: 'marken', hinweis: 'Der beutellose Staubsauger von James Dyson.', titel: ['Dyson (Unternehmen)'], suche: 'Dyson vacuum cleaner' },
  { id: 'barbie', name: 'Barbie', gruppe: 'marken', hinweis: 'Die Puppe von Mattel, benannt nach Barbara Handler.', titel: ['Barbie'], suche: 'Barbie doll' },
  { id: 'converse', name: 'Converse', gruppe: 'marken', hinweis: 'Der Stern am Knöchel, die Chucks aus den USA.', titel: ['Converse (Unternehmen)'], suche: 'Converse Chuck Taylor shoe' },
  { id: 'vans', name: 'Vans', gruppe: 'marken', hinweis: 'Der Seitenstreifen, die Skate-Schuhe aus Kalifornien.', titel: ['Vans'], suche: 'Vans shoe' },
  { id: 'obi', name: 'OBI', gruppe: 'marken', hinweis: 'Der orangefarbene Biber, der Baumarkt aus Wermelskirchen.', titel: ['Obi (Baumarkt)'], suche: 'OBI hardware store' },
  { id: 'hornbach', name: 'Hornbach', gruppe: 'marken', hinweis: 'Der Baumarkt aus Bornheim, das orange Logo.', titel: ['Hornbach (Baumarkt)'], suche: 'Hornbach store' },
  { id: 'mediamarkt', name: 'MediaMarkt', gruppe: 'marken', hinweis: 'Der rote Schriftzug, die Elektro-Kette aus Ingolstadt.', titel: ['MediaMarkt'], suche: 'MediaMarkt store' },
  { id: 'rolex', name: 'Rolex', gruppe: 'marken', hinweis: 'Die Krone über dem Namen, die Uhren aus Genf.', titel: ['Rolex'], suche: 'Rolex watch' },
  { id: 'swatch', name: 'Swatch', gruppe: 'marken', hinweis: 'Die bunten Plastikuhren aus der Schweiz, Second Watch.', titel: ['Swatch'], suche: 'Swatch watch' },
  { id: 'pampers', name: 'Pampers', gruppe: 'marken', hinweis: 'Die Windeln von Procter & Gamble.', titel: ['Pampers'], suche: 'Pampers diapers' },
  { id: 'zara', name: 'Zara', gruppe: 'marken', hinweis: 'Die Modekette von Inditex aus Arteixo in Spanien.', titel: ['Zara (Modeunternehmen)'], suche: 'Zara store exterior' },

  { id: 'farid', name: 'Farid Bang', gruppe: 'rap', antwort: 'farid', hinweis: 'Farid Bang, deutscher Rapper aus Düsseldorf, bekannt aus dem Asphalt Massaka-Umfeld.', titel: ['Farid Bang'], suche: 'Farid Bang' },
  { id: 'kc', name: 'KC Rebell', gruppe: 'rap', antwort: 'kc', hinweis: 'KC Rebell, Rapper mit kurdischen Wurzeln, lange bei Banger Musik.', titel: ['KC Rebell'], suche: 'KC Rebell' },
  { id: 'gzuz', name: 'Gzuz', gruppe: 'rap', antwort: 'gzuz', hinweis: 'Gzuz, Mitglied der 187 Strassenbande aus Hamburg.', titel: ['Gzuz'], suche: 'Gzuz rapper' },
  { id: 'ufo', name: 'Ufo361', gruppe: 'rap', antwort: 'ufo', hinweis: 'Ufo361, Berliner Rapper, bürgerlich Ufuk Bayraktar.', titel: ['Ufo361'], suche: 'Ufo361' },
  { id: 'rin', name: 'RIN', gruppe: 'rap', antwort: 'rin', hinweis: 'RIN, Rapper aus Bietigheim-Bissingen.', titel: ['RIN (Rapper)'], suche: 'RIN rapper' },
  { id: 'summer', name: 'Summer Cem', gruppe: 'rap', antwort: 'summer', hinweis: 'Summer Cem, Rapper aus Düsseldorf.', titel: ['Summer Cem'], suche: 'Summer Cem' },
  { id: 'shindy', name: 'Shindy', gruppe: 'rap', antwort: 'shindy', hinweis: 'Shindy, Rapper aus Stuttgart, lange mit Bushido verbunden.', titel: ['Shindy'], suche: 'Shindy rapper' },
  { id: 'fler', name: 'Fler', gruppe: 'rap', antwort: 'fler', hinweis: 'Fler, Berliner Rapper, Mitgründer von Aggro Berlin.', titel: ['Fler'], suche: 'Fler rapper' },
  { id: 'kollegah', name: 'Kollegah', gruppe: 'rap', antwort: 'kollegah', hinweis: 'Kollegah, Rapper aus Friedberg, bekannt für Punchlines.', titel: ['Kollegah'], suche: 'Kollegah' },
  { id: 'marteria', name: 'Marteria', gruppe: 'rap', antwort: 'marteria', hinweis: 'Marteria, Rapper aus Rostock, bürgerlich Marten Laciny.', titel: ['Marteria'], suche: 'Marteria' },
  { id: 'samy', name: 'Samy Deluxe', gruppe: 'rap', antwort: 'samy', hinweis: 'Samy Deluxe, Hamburger Rapper der Dynamite Deluxe.', titel: ['Samy Deluxe'], suche: 'Samy Deluxe' },
  { id: 'savas', name: 'Kool Savas', gruppe: 'rap', antwort: 'savas', hinweis: 'Kool Savas, einer der frühen deutschen Battle-Rapper, aus Aachen und Berlin.', titel: ['Kool Savas'], suche: 'Kool Savas' },
  { id: 'azad', name: 'Azad', gruppe: 'rap', antwort: 'azad', hinweis: 'Azad, Frankfurter Rapper, Mitgründer von Asiatic Warriors.', titel: ['Azad (Rapper)'], suche: 'Azad rapper' },
  { id: 'eko', name: 'Eko Fresh', gruppe: 'rap', antwort: 'eko', hinweis: 'Eko Fresh, Rapper aus Köln, bürgerlich Ekrem Bora.', titel: ['Eko Fresh'], suche: 'Eko Fresh' },
  { id: 'bausa', name: 'Bausa', gruppe: 'rap', antwort: 'bausa', hinweis: 'Bausa, Rapper aus Saarbrücken.', titel: ['Bausa'], suche: 'Bausa rapper' },
  { id: 'trettmann', name: 'Trettmann', gruppe: 'rap', antwort: 'trettmann', hinweis: 'Trettmann, Rapper aus Chemnitz, früher unter dem Namen Ronny Trettmann.', titel: ['Trettmann'], suche: 'Trettmann' },
  { id: 'mero', name: 'Mero', gruppe: 'rap', antwort: 'mero', hinweis: 'Mero, Rapper aus Rüsselsheim, bürgerlich Enes Meral.', titel: ['Mero (Rapper)'], suche: 'Mero rapper' },
  { id: 'olexesh', name: 'Olexesh', gruppe: 'rap', antwort: 'olexesh', hinweis: 'Olexesh, Rapper aus Kiew, aufgewachsen in Darmstadt.', titel: ['Olexesh'], suche: 'Olexesh' },
  { id: 'nimo', name: 'Nimo', gruppe: 'rap', antwort: 'nimo', hinweis: 'Nimo, Rapper aus Karlsruhe.', titel: ['Nimo (Rapper)'], suche: 'Nimo rapper Karlsruhe' },
  { id: 'pa', name: 'PA Sports', gruppe: 'rap', antwort: 'pasports', hinweis: 'PA Sports, Rapper aus Euskirchen.', titel: ['PA Sports'], suche: 'PA Sports rapper' },
  { id: 'motrip', name: 'MoTrip', gruppe: 'rap', antwort: 'motrip', hinweis: 'MoTrip, Rapper aus Beirut, aufgewachsen in Braunschweig.', titel: ['MoTrip'], suche: 'MoTrip' },
  { id: 'massiv', name: 'Massiv', gruppe: 'rap', antwort: 'massiv', hinweis: 'Massiv, Berliner Rapper, bürgerlich Wasiem Taha.', titel: ['Massiv (Rapper)'], suche: 'Massiv rapper' },
  { id: 'xatar', name: 'Xatar', gruppe: 'rap', antwort: 'xatar', hinweis: 'Xatar, Rapper und Labelchef aus Bonn, bürgerlich Giwar Hajabi.', titel: ['Xatar'], suche: 'Xatar rapper' },
  { id: 'juju', name: 'Juju', gruppe: 'rap', antwort: 'juju', hinweis: 'Juju, Rapperin aus Berlin, früher bei den SXTN.', titel: ['Juju (Rapperin)'], suche: 'Juju rapper SXTN' },
  { id: 'loredana', name: 'Loredana', gruppe: 'rap', antwort: 'loredana', hinweis: 'Loredana, Rapperin mit kosovarischen Wurzeln, aufgewachsen in der Schweiz.', titel: ['Loredana (Rapperin)'], suche: 'Loredana rapper' },
  { id: 'shirin', name: 'Shirin David', gruppe: 'rap', antwort: 'shirin', hinweis: 'Shirin David, Sängerin und Rapperin aus Hamburg.', titel: ['Shirin David'], suche: 'Shirin David' },
  { id: 'money', name: 'Money Boy', gruppe: 'rap', antwort: 'money', hinweis: 'Money Boy, Rapper aus Wien.', titel: ['Money Boy'], suche: 'Money Boy rapper' },
  { id: 'yunghurn', name: 'Yung Hurn', gruppe: 'rap', antwort: 'yunghurn', hinweis: 'Yung Hurn, Rapper aus Wien.', titel: ['Yung Hurn'], suche: 'Yung Hurn' },
  { id: 'ski', name: 'Ski Aggu', gruppe: 'rap', antwort: 'ski', hinweis: 'Ski Aggu, Rapper aus Berlin, bürgerlich August Jean Diederich.', titel: ['Ski Aggu'], suche: 'Ski Aggu' },
  { id: 'pashanim', name: 'Pashanim', gruppe: 'rap', antwort: 'pashanim', hinweis: 'Pashanim, Berliner Rapper.', titel: ['Pashanim'], suche: 'Pashanim' },
  { id: 'jamule', name: 'Jamule', gruppe: 'rap', antwort: 'jamule', hinweis: 'Jamule, Rapper aus Bonn.', titel: ['Jamule'], suche: 'Jamule rapper' },
  { id: 'zuna', name: 'Zuna', gruppe: 'rap', antwort: 'zuna', hinweis: 'Zuna, Rapper aus Kassel.', titel: ['Zuna (Rapper)'], suche: 'Zuna rapper' },
  { id: 'reezy', name: 'Reezy', gruppe: 'rap', antwort: 'reezy', hinweis: 'Reezy, Rapper aus Frankfurt.', titel: ['Reezy'], suche: 'Reezy rapper' },
  { id: 'manuellsen', name: 'Manuellsen', gruppe: 'rap', antwort: 'manuellsen', hinweis: 'Manuellsen, Rapper aus Gelsenkirchen.', titel: ['Manuellsen'], suche: 'Manuellsen' },
  { id: 'prinz', name: 'Prinz Pi', gruppe: 'rap', antwort: 'prinz', hinweis: 'Prinz Pi, Berliner Rapper, früher Prinz Porno.', titel: ['Prinz Pi'], suche: 'Prinz Pi' },
  { id: 'curse', name: 'Curse', gruppe: 'rap', antwort: 'curse', hinweis: 'Curse, Rapper aus Minden.', titel: ['Curse (Rapper)'], suche: 'Curse rapper' },
  { id: 'megaloh', name: 'Megaloh', gruppe: 'rap', antwort: 'megaloh', hinweis: 'Megaloh, Rapper aus Berlin.', titel: ['Megaloh'], suche: 'Megaloh' },
  { id: 'nura', name: 'Nura', gruppe: 'rap', antwort: 'nura', hinweis: 'Nura, Rapperin aus Berlin, früher bei den SXTN.', titel: ['Nura (Rapperin)'], suche: 'Nura rapper' },
  { id: 'kalim', name: 'Kalim', gruppe: 'rap', antwort: 'kalim', hinweis: 'Kalim, Rapper aus Essen.', titel: ['Kalim (Rapper)'], suche: 'Kalim rapper' },
  { id: 'btight', name: 'B-Tight', gruppe: 'rap', antwort: 'btight', hinweis: 'B-Tight, Berliner Rapper, Mitgründer von Aggro Berlin.', titel: ['B-Tight'], suche: 'B-Tight rapper' },
  { id: 'silla', name: 'Silla', gruppe: 'rap', antwort: 'silla', hinweis: 'Silla, Rapper aus Berlin.', titel: ['Silla (Rapper)'], suche: 'Silla rapper' },
  { id: 'vega', name: 'Vega', gruppe: 'rap', antwort: 'vega', hinweis: 'Vega, Rapper aus der Pfalz.', titel: ['Vega (Rapper)'], suche: 'Vega rapper' },
  { id: 'hanybal', name: 'Hanybal', gruppe: 'rap', antwort: 'hanybal', hinweis: 'Hanybal, Rapper aus Offenbach.', titel: ['Hanybal'], suche: 'Hanybal' },
]
