export interface NeuMotiv {
  id: string
  name: string
  gruppe: 'autos' | 'marken' | 'orte' | 'natur' | 'rap'
  hinweis: string
  antwort?: string
  titel: string[]
  suche: string
}

export const NEU: NeuMotiv[] = [
  { id: 'renault', name: 'Renault', gruppe: 'autos', hinweis: 'Die Raute ist das Zeichen aus Boulogne-Billancourt.', titel: ['Renault Clio V', 'Renault Clio'], suche: 'Renault Clio front photo' },
  { id: 'peugeot', name: 'Peugeot', gruppe: 'autos', hinweis: 'Der Löwe auf den Hinterbeinen gehört zum Haus aus Sochaux.', titel: ['Peugeot 208'], suche: 'Peugeot 208 front photo' },
  { id: 'citroen', name: 'Citroën', gruppe: 'autos', hinweis: 'Die Doppelwinkel erinnern an Zahnräder.', titel: ['Citroën C3'], suche: 'Citroen C3 front photo' },
  { id: 'skoda', name: 'Škoda', gruppe: 'autos', hinweis: 'Der geflügelte Pfeil kommt aus Mladá Boleslav.', titel: ['Škoda Octavia IV', 'Škoda Octavia'], suche: 'Skoda Octavia front photo' },
  { id: 'seat', name: 'Seat', gruppe: 'autos', hinweis: 'Das S gehört zur spanischen Marke aus Martorell.', titel: ['Seat Leon IV', 'Seat Leon'], suche: 'Seat Leon front photo' },
  { id: 'volvo', name: 'Volvo', gruppe: 'autos', hinweis: 'Der Kreis mit dem Pfeil steht für Eisen, das Zeichen aus Göteborg.', titel: ['Volvo XC40'], suche: 'Volvo XC40 front photo' },
  { id: 'hyundai', name: 'Hyundai', gruppe: 'autos', hinweis: 'Das schräge H im Oval kommt aus Seoul.', titel: ['Hyundai Tucson'], suche: 'Hyundai Tucson front photo' },
  { id: 'kia', name: 'Kia', gruppe: 'autos', hinweis: 'Der Schriftzug im Oval gehört zum koreanischen Schwesterhaus von Hyundai.', titel: ['Kia Sportage'], suche: 'Kia Sportage front photo' },
  { id: 'mazda', name: 'Mazda', gruppe: 'autos', hinweis: 'Das M erinnert an Flügel, der Name an den Lichtgott Ahura Mazda.', titel: ['Mazda3'], suche: 'Mazda3 front photo' },
  { id: 'nissan', name: 'Nissan', gruppe: 'autos', hinweis: 'Der Balken im Kreis ist das Zeichen aus Yokohama.', titel: ['Nissan Qashqai'], suche: 'Nissan Qashqai front photo' },
  { id: 'jeep', name: 'Jeep', gruppe: 'autos', hinweis: 'Die sieben Schlitze im Kühler kommen vom Willys aus dem Zweiten Weltkrieg.', titel: ['Jeep Wrangler'], suche: 'Jeep Wrangler photo' },
  { id: 'chevrolet', name: 'Chevrolet', gruppe: 'autos', hinweis: 'Das goldene Kreuz ist die Fliege aus dem Tapetenmuster eines Hotels in Paris.', titel: ['Chevrolet Camaro'], suche: 'Chevrolet Camaro front photo' },
  { id: 'lamborghini', name: 'Lamborghini', gruppe: 'autos', hinweis: 'Der Stier steht für Ferruccio Lamborghinis Sternzeichen.', titel: ['Lamborghini Huracán'], suche: 'Lamborghini Huracan photo' },
  { id: 'maserati', name: 'Maserati', gruppe: 'autos', hinweis: 'Der Dreizack ist der von Neptun, dem Wahrzeichen von Bologna.', titel: ['Maserati Ghibli'], suche: 'Maserati front photo' },
  { id: 'bentley', name: 'Bentley', gruppe: 'autos', hinweis: 'Das geflügelte B gehört zu den Wagen aus Crewe.', titel: ['Bentley Continental GT'], suche: 'Bentley Continental GT photo' },
  { id: 'jaguar', name: 'Jaguar', gruppe: 'autos', hinweis: 'Der springende Jaguar, der Raubkatzen-Name aus Coventry.', titel: ['Jaguar F-Type'], suche: 'Jaguar F-Type photo' },
  { id: 'mini', name: 'Mini', gruppe: 'autos', hinweis: 'Der kleine Wagen aus Oxford, heute ein Haus von BMW.', titel: ['Mini Hatch', 'Mini (BMW)'], suche: 'Mini Cooper front photo' },
  { id: 'alfa', name: 'Alfa Romeo', gruppe: 'autos', hinweis: 'Das rote Kreuz und die Schlange sind das Wappen von Mailand.', titel: ['Alfa Romeo Giulia (952)', 'Alfa Romeo Giulia'], suche: 'Alfa Romeo Giulia photo' },
  { id: 'dacia', name: 'Dacia', gruppe: 'autos', hinweis: 'Das blaue Schild gehört zur rumänischen Marke aus Pitești.', titel: ['Dacia Sandero'], suche: 'Dacia Sandero front photo' },
  { id: 'bugatti', name: 'Bugatti', gruppe: 'autos', hinweis: 'Das rote Oval mit den 60 Perlen erinnert an Ettore Bugatti.', titel: ['Bugatti Chiron'], suche: 'Bugatti Chiron photo' },
  { id: 'mclaren', name: 'McLaren', gruppe: 'autos', hinweis: 'Der Keil kommt vom Rennstall aus Woking.', titel: ['McLaren 720S'], suche: 'McLaren 720S photo' },
  { id: 'lexus', name: 'Lexus', gruppe: 'autos', hinweis: 'Das L im Oval ist die Edelmarke von Toyota.', titel: ['Lexus RX'], suche: 'Lexus RX front photo' },
  { id: 'cupra', name: 'Cupra', gruppe: 'autos', hinweis: 'Die Kupferspitze, die Sportmarke von Seat aus Barcelona.', titel: ['Cupra Formentor'], suche: 'Cupra Formentor photo' },
  { id: 'smart', name: 'Smart', gruppe: 'autos', hinweis: 'Der kurze Zweisitzer, der Name mischt Swatch und Mercedes.', titel: ['Smart Fortwo'], suche: 'Smart Fortwo photo' },
  { id: 'subaru', name: 'Subaru', gruppe: 'autos', hinweis: 'Die sechs Sterne stehen für das Sternbild der Plejaden.', titel: ['Subaru Impreza'], suche: 'Subaru Impreza front photo' },
  { id: 'landrover', name: 'Land Rover', gruppe: 'autos', hinweis: 'Das grüne Oval gehört zu den Geländewagen aus Solihull.', titel: ['Land Rover Defender'], suche: 'Land Rover Defender photo' },
  { id: 'rolls', name: 'Rolls-Royce', gruppe: 'autos', hinweis: 'Die Kühlerfigur Spirit of Ecstasy steht über dem Pantheon-Kühler.', titel: ['Rolls-Royce Phantom VIII', 'Rolls-Royce Phantom'], suche: 'Rolls-Royce Phantom photo' },
  { id: 'suzuki', name: 'Suzuki', gruppe: 'autos', hinweis: 'Das S gehört zum Haus aus Hamamatsu, bekannt auch für Motorräder.', titel: ['Suzuki Swift'], suche: 'Suzuki Swift front photo' },

  { id: 'puma', name: 'Puma', gruppe: 'marken', hinweis: 'Der springende Puma, gegründet von Rudolf Dassler, dem Bruder von Adi.', titel: ['Puma (Unternehmen)'], suche: 'Puma shoe' },
  { id: 'nintendo', name: 'Nintendo', gruppe: 'marken', hinweis: 'Die Konsole mit den abnehmbaren Controllern, das Haus aus Kyōto.', titel: ['Nintendo Switch'], suche: 'Nintendo Switch console' },
  { id: 'playstation', name: 'PlayStation', gruppe: 'marken', hinweis: 'Das PS-Zeichen von Sony, die Konsole aus Tokio.', titel: ['PlayStation 5'], suche: 'PlayStation 5 console' },
  { id: 'xbox', name: 'Xbox', gruppe: 'marken', hinweis: 'Die Kugel von Microsoft, die Konsole aus Redmond.', titel: ['Xbox Series X'], suche: 'Xbox Series X console' },
  { id: 'toblerone', name: 'Toblerone', gruppe: 'marken', hinweis: 'Die Dreiecksschokolade aus Bern, das Matterhorn auf der Packung.', titel: ['Toblerone'], suche: 'Toblerone chocolate' },
  { id: 'ferrero', name: 'Ferrero Rocher', gruppe: 'marken', hinweis: 'Die goldene Kugel mit der Haselnuss, aus Alba in Piemont.', titel: ['Ferrero Rocher'], suche: 'Ferrero Rocher' },
  { id: 'lufthansa', name: 'Lufthansa', gruppe: 'marken', hinweis: 'Der Kranich im Kreis, die Airline aus Köln.', titel: ['Lufthansa'], suche: 'Lufthansa airplane' },
  { id: 'bahn', name: 'Deutsche Bahn', gruppe: 'marken', hinweis: 'Die Buchstaben DB, die Züge in Verkehrsrot.', titel: ['Deutsche Bahn'], suche: 'Deutsche Bahn train ICE' },
  { id: 'playmobil', name: 'Playmobil', gruppe: 'marken', hinweis: 'Die kleinen Figuren mit dem Lächeln, von geobra Brandstätter.', titel: ['Playmobil'], suche: 'Playmobil figures' },
  { id: 'bosch', name: 'Bosch', gruppe: 'marken', hinweis: 'Der Anker im Kreis, das Haus von Robert Bosch in Gerlingen.', titel: ['Robert Bosch GmbH'], suche: 'Bosch power drill' },
  { id: 'philips', name: 'Philips', gruppe: 'marken', hinweis: 'Das Schild mit den Sternen, gegründet in Eindhoven.', titel: ['Philips'], suche: 'Philips product' },
  { id: 'dyson', name: 'Dyson', gruppe: 'marken', hinweis: 'Der beutellose Staubsauger von James Dyson.', titel: ['Dyson (Unternehmen)'], suche: 'Dyson vacuum cleaner' },
  { id: 'barbie', name: 'Barbie', gruppe: 'marken', hinweis: 'Die Puppe von Mattel, benannt nach Barbara Handler.', titel: ['Barbie'], suche: 'Barbie doll' },
  { id: 'converse', name: 'Converse', gruppe: 'marken', hinweis: 'Der Stern am Knöchel, die Chucks aus den USA.', titel: ['Converse (Unternehmen)'], suche: 'Converse Chuck Taylor shoe' },
  { id: 'vans', name: 'Vans', gruppe: 'marken', hinweis: 'Der Seitenstreifen, die Skate-Schuhe aus Kalifornien.', titel: ['Vans'], suche: 'Vans shoe' },
  { id: 'rolex', name: 'Rolex', gruppe: 'marken', hinweis: 'Die Krone über dem Namen, die Uhren aus Genf.', titel: ['Rolex'], suche: 'Rolex watch' },
  { id: 'swatch', name: 'Swatch', gruppe: 'marken', hinweis: 'Die bunten Plastikuhren aus der Schweiz, Second Watch.', titel: ['Swatch'], suche: 'Swatch watch' },
  { id: 'vespa', name: 'Vespa', gruppe: 'marken', hinweis: 'Der Roller aus Pontedera, das Schild an der Beinschild-Front ist rund.', titel: ['Vespa'], suche: 'Vespa scooter photo' },
  { id: 'harley', name: 'Harley-Davidson', gruppe: 'marken', hinweis: 'Das schwere Motorrad aus Milwaukee, der Schriftzug sitzt am Tank.', titel: ['Harley-Davidson'], suche: 'Harley-Davidson motorcycle photo' },
  { id: 'birken', name: 'Birkenstock', gruppe: 'marken', hinweis: 'Die Sandale mit dem tiefen Fußbett, das Haus aus Linz am Rhein.', titel: ['Birkenstock'], suche: 'Birkenstock sandal' },
  { id: 'crocs', name: 'Crocs', gruppe: 'marken', hinweis: 'Der Schuh aus Schaum mit den Löchern, aus Boulder in Colorado.', titel: ['Crocs'], suche: 'Crocs shoe' },
  { id: 'drmartens', name: 'Dr. Martens', gruppe: 'marken', hinweis: 'Die Stiefel mit der gelben Naht, aus Northampton.', titel: ['Dr. Martens'], suche: 'Dr. Martens boot' },
  { id: 'newbalance', name: 'New Balance', gruppe: 'marken', hinweis: 'Das N auf dem Schuh, die Laufschuhe aus Boston.', titel: ['New Balance'], suche: 'New Balance shoe' },
  { id: 'schleich', name: 'Schleich', gruppe: 'marken', hinweis: 'Die detailreichen Tierfiguren aus Schwäbisch Gmünd.', titel: ['Schleich (Spielwaren)'], suche: 'Schleich animal figure' },
  { id: 'playdoh', name: 'Play-Doh', gruppe: 'marken', hinweis: 'Die Knetmasse in der Dose, von Hasbro.', titel: ['Play-Doh'], suche: 'Play-Doh' },
  { id: 'rubik', name: 'Rubik’s Cube', gruppe: 'marken', hinweis: 'Der Würfel mit den sechs Farben, erfunden von Ernő Rubik.', titel: ['Zauberwürfel'], suche: 'Rubik cube' },
  { id: 'hotwheels', name: 'Hot Wheels', gruppe: 'marken', hinweis: 'Die kleinen Gussautos von Mattel.', titel: ['Hot Wheels'], suche: 'Hot Wheels toy car' },
  { id: 'fischer', name: 'Fischertechnik', gruppe: 'marken', hinweis: 'Der graue Baustein mit der Nut, aus Waldachtal.', titel: ['Fischertechnik'], suche: 'Fischertechnik model' },
  { id: 'monchi', name: 'Monchhichi', gruppe: 'marken', hinweis: 'Das Äffchen mit dem Schnuller, aus Japan.', titel: ['Monchhichi'], suche: 'Monchhichi doll' },

  { id: 'farid', name: 'Farid Bang', gruppe: 'rap', antwort: 'farid', hinweis: 'Farid Bang, deutscher Rapper aus Düsseldorf, bekannt aus dem Asphalt Massaka-Umfeld.', titel: ['Farid Bang'], suche: 'Farid Bang' },
  { id: 'kc', name: 'KC Rebell', gruppe: 'rap', antwort: 'kc', hinweis: 'KC Rebell, Rapper mit kurdischen Wurzeln, lange bei Banger Musik.', titel: ['KC Rebell'], suche: 'KC Rebell' },
  { id: 'gzuz', name: 'Gzuz', gruppe: 'rap', antwort: 'gzuz', hinweis: 'Gzuz, Mitglied der 187 Strassenbande aus Hamburg.', titel: ['Gzuz'], suche: 'Gzuz rapper' },
  { id: 'ufo', name: 'Ufo361', gruppe: 'rap', antwort: 'ufo', hinweis: 'Ufo361, Berliner Rapper, bürgerlich Ufuk Bayraktar.', titel: ['Ufo361'], suche: 'Ufo361' },
  { id: 'rin', name: 'RIN', gruppe: 'rap', antwort: 'rin', hinweis: 'RIN, Rapper aus Bietigheim-Bissingen.', titel: ['RIN (Rapper)'], suche: 'RIN rapper' },
  { id: 'summer', name: 'Summer Cem', gruppe: 'rap', antwort: 'summer', hinweis: 'Summer Cem, Rapper aus Düsseldorf.', titel: ['Summer Cem'], suche: 'Summer Cem' },
  { id: 'shindy', name: 'Shindy', gruppe: 'rap', antwort: 'shindy', hinweis: 'Shindy, Rapper aus Stuttgart, lange mit Bushido verbunden.', titel: ['Shindy'], suche: 'Shindy rapper' },
  { id: 'fler', name: 'Fler', gruppe: 'rap', antwort: 'fler', hinweis: 'Fler, Berliner Rapper, Mitgründer von Aggro Berlin.', titel: ['Fler'], suche: 'Fler rapper' },
  { id: 'kollegah', name: 'Kollegah', gruppe: 'rap', antwort: 'kollegah', hinweis: 'Kollegah, Rapper aus Friedberg, bekannt für Punchlines.', titel: ['Kollegah'], suche: 'Kollegah' },
  { id: 'marteria', name: 'Marteria', gruppe: 'rap', antwort: 'marteria', hinweis: 'Marteria, Rapper aus Rostock, bürgerlich Marten Laciny.', titel: ['Marteria'], suche: 'Marteria' },
  { id: 'samy', name: 'Samy Deluxe', gruppe: 'rap', antwort: 'samy', hinweis: 'Samy Deluxe, Hamburger Rapper der Dynamite Deluxe.', titel: ['Samy Deluxe'], suche: 'Samy Deluxe' },
  { id: 'savas', name: 'Kool Savas', gruppe: 'rap', antwort: 'savas', hinweis: 'Kool Savas, einer der frühen deutschen Battle-Rapper, aus Aachen und Berlin.', titel: ['Kool Savas'], suche: 'Kool Savas' },
  { id: 'azad', name: 'Azad', gruppe: 'rap', antwort: 'azad', hinweis: 'Azad, Frankfurter Rapper, Mitgründer von Asiatic Warriors.', titel: ['Azad (Rapper)'], suche: 'Azad rapper' },
  { id: 'eko', name: 'Eko Fresh', gruppe: 'rap', antwort: 'eko', hinweis: 'Eko Fresh, Rapper aus Köln, bürgerlich Ekrem Bora.', titel: ['Eko Fresh'], suche: 'Eko Fresh' },
  { id: 'bausa', name: 'Bausa', gruppe: 'rap', antwort: 'bausa', hinweis: 'Bausa, Rapper aus Saarbrücken.', titel: ['Bausa'], suche: 'Bausa rapper' },
  { id: 'trettmann', name: 'Trettmann', gruppe: 'rap', antwort: 'trettmann', hinweis: 'Trettmann, Rapper aus Chemnitz, früher unter dem Namen Ronny Trettmann.', titel: ['Trettmann'], suche: 'Trettmann' },
  { id: 'mero', name: 'Mero', gruppe: 'rap', antwort: 'mero', hinweis: 'Mero, Rapper aus Rüsselsheim, bürgerlich Enes Meral.', titel: ['Mero (Rapper)'], suche: 'Mero rapper' },
  { id: 'olexesh', name: 'Olexesh', gruppe: 'rap', antwort: 'olexesh', hinweis: 'Olexesh, Rapper aus Kiew, aufgewachsen in Darmstadt.', titel: ['Olexesh'], suche: 'Olexesh' },
  { id: 'nimo', name: 'Nimo', gruppe: 'rap', antwort: 'nimo', hinweis: 'Nimo, Rapper aus Karlsruhe.', titel: ['Nimo (Rapper)'], suche: 'Nimo rapper Karlsruhe' },
  { id: 'pa', name: 'PA Sports', gruppe: 'rap', antwort: 'pasports', hinweis: 'PA Sports, Rapper aus Euskirchen.', titel: ['PA Sports'], suche: 'PA Sports rapper' },
  { id: 'motrip', name: 'MoTrip', gruppe: 'rap', antwort: 'motrip', hinweis: 'MoTrip, Rapper aus Beirut, aufgewachsen in Braunschweig.', titel: ['MoTrip'], suche: 'MoTrip' },
  { id: 'massiv', name: 'Massiv', gruppe: 'rap', antwort: 'massiv', hinweis: 'Massiv, Berliner Rapper, bürgerlich Wasiem Taha.', titel: ['Massiv (Rapper)'], suche: 'Massiv rapper' },
  { id: 'xatar', name: 'Xatar', gruppe: 'rap', antwort: 'xatar', hinweis: 'Xatar, Rapper und Labelchef aus Bonn, bürgerlich Giwar Hajabi.', titel: ['Xatar'], suche: 'Xatar rapper' },
  { id: 'juju', name: 'Juju', gruppe: 'rap', antwort: 'juju', hinweis: 'Juju, Rapperin aus Berlin, früher bei den SXTN.', titel: ['Juju (Rapperin)'], suche: 'Juju rapper SXTN' },
  { id: 'loredana', name: 'Loredana', gruppe: 'rap', antwort: 'loredana', hinweis: 'Loredana, Rapperin mit kosovarischen Wurzeln, aufgewachsen in der Schweiz.', titel: ['Loredana (Rapperin)'], suche: 'Loredana rapper' },
  { id: 'shirin', name: 'Shirin David', gruppe: 'rap', antwort: 'shirin', hinweis: 'Shirin David, Sängerin und Rapperin aus Hamburg.', titel: ['Shirin David'], suche: 'Shirin David' },
  { id: 'money', name: 'Money Boy', gruppe: 'rap', antwort: 'money', hinweis: 'Money Boy, Rapper aus Wien.', titel: ['Money Boy'], suche: 'Money Boy rapper' },
  { id: 'yunghurn', name: 'Yung Hurn', gruppe: 'rap', antwort: 'yunghurn', hinweis: 'Yung Hurn, Rapper aus Wien.', titel: ['Yung Hurn'], suche: 'Yung Hurn' },
  { id: 'ski', name: 'Ski Aggu', gruppe: 'rap', antwort: 'ski', hinweis: 'Ski Aggu, Rapper aus Berlin, bürgerlich August Jean Diederich.', titel: ['Ski Aggu'], suche: 'Ski Aggu' },
  { id: 'pashanim', name: 'Pashanim', gruppe: 'rap', antwort: 'pashanim', hinweis: 'Pashanim, Berliner Rapper.', titel: ['Pashanim'], suche: 'Pashanim' },
  { id: 'jamule', name: 'Jamule', gruppe: 'rap', antwort: 'jamule', hinweis: 'Jamule, Rapper aus Bonn.', titel: ['Jamule'], suche: 'Jamule rapper' },
  { id: 'zuna', name: 'Zuna', gruppe: 'rap', antwort: 'zuna', hinweis: 'Zuna, Rapper aus Kassel.', titel: ['Zuna (Rapper)'], suche: 'Zuna rapper' },
  { id: 'reezy', name: 'Reezy', gruppe: 'rap', antwort: 'reezy', hinweis: 'Reezy, Rapper aus Frankfurt.', titel: ['Reezy'], suche: 'Reezy rapper' },
  { id: 'manuellsen', name: 'Manuellsen', gruppe: 'rap', antwort: 'manuellsen', hinweis: 'Manuellsen, Rapper aus Gelsenkirchen.', titel: ['Manuellsen'], suche: 'Manuellsen' },
  { id: 'prinz', name: 'Prinz Pi', gruppe: 'rap', antwort: 'prinz', hinweis: 'Prinz Pi, Berliner Rapper, früher Prinz Porno.', titel: ['Prinz Pi'], suche: 'Prinz Pi' },
  { id: 'curse', name: 'Curse', gruppe: 'rap', antwort: 'curse', hinweis: 'Curse, Rapper aus Minden.', titel: ['Curse (Rapper)'], suche: 'Curse rapper' },
  { id: 'megaloh', name: 'Megaloh', gruppe: 'rap', antwort: 'megaloh', hinweis: 'Megaloh, Rapper aus Berlin.', titel: ['Megaloh'], suche: 'Megaloh' },
  { id: 'nura', name: 'Nura', gruppe: 'rap', antwort: 'nura', hinweis: 'Nura, Rapperin aus Berlin, früher bei den SXTN.', titel: ['Nura (Rapperin)'], suche: 'Nura rapper' },
  { id: 'kalim', name: 'Kalim', gruppe: 'rap', antwort: 'kalim', hinweis: 'Kalim, Rapper aus Essen.', titel: ['Kalim (Rapper)'], suche: 'Kalim rapper' },
  { id: 'btight', name: 'B-Tight', gruppe: 'rap', antwort: 'btight', hinweis: 'B-Tight, Berliner Rapper, Mitgründer von Aggro Berlin.', titel: ['B-Tight'], suche: 'B-Tight rapper' },
  { id: 'silla', name: 'Silla', gruppe: 'rap', antwort: 'silla', hinweis: 'Silla, Rapper aus Berlin.', titel: ['Silla (Rapper)'], suche: 'Silla rapper' },
  { id: 'vega', name: 'Vega', gruppe: 'rap', antwort: 'vega', hinweis: 'Vega, Rapper aus der Pfalz.', titel: ['Vega (Rapper)'], suche: 'Vega rapper' },
  { id: 'hanybal', name: 'Hanybal', gruppe: 'rap', antwort: 'hanybal', hinweis: 'Hanybal, Rapper aus Offenbach.', titel: ['Hanybal'], suche: 'Hanybal' },
  { id: 'ssio', name: 'SSIO', gruppe: 'rap', antwort: 'ssio', hinweis: 'SSIO, Rapper aus Köln, bürgerlich Ssiawosch Sadat.', titel: ['SSIO'], suche: 'SSIO rapper' },
  { id: 'dcvdns', name: 'DCVDNS', gruppe: 'rap', antwort: 'dcvdns', hinweis: 'DCVDNS, Rapper aus Köln, bekannt für den Track „Brille“.', titel: ['DCVDNS'], suche: 'DCVDNS rapper' },
  { id: 'banjo', name: 'Olli Banjo', gruppe: 'rap', antwort: 'banjo', hinweis: 'Olli Banjo, Rapper aus Frankfurt.', titel: ['Olli Banjo'], suche: 'Olli Banjo' },
  { id: 'ferris', name: 'Ferris MC', gruppe: 'rap', antwort: 'ferris', hinweis: 'Ferris MC, Rapper aus Kiel, früher bei den Deichkind-Umfeld und Rödelheim Hartreim.', titel: ['Ferris MC'], suche: 'Ferris MC' },
  { id: 'denyo', name: 'Denyo', gruppe: 'rap', antwort: 'denyo', hinweis: 'Denyo, Rapper der Beginner aus Hamburg.', titel: ['Denyo'], suche: 'Denyo rapper' },
  { id: 'dendemann', name: 'Dendemann', gruppe: 'rap', antwort: 'dendemann', hinweis: 'Dendemann, Rapper aus Hamburg, Mitglied der Beginner.', titel: ['Dendemann'], suche: 'Dendemann' },
  { id: 'torch', name: 'Torch', gruppe: 'rap', antwort: 'torch', hinweis: 'Torch, Rapper der Advanced Chemistry aus Heidelberg.', titel: ['Torch (Rapper)'], suche: 'Torch rapper Advanced Chemistry' },
  { id: 'blumio', name: 'Blumio', gruppe: 'rap', antwort: 'blumio', hinweis: 'Blumio, Rapper aus Hilden, bürgerlich Fumio Kuniyoshi.', titel: ['Blumio'], suche: 'Blumio rapper' },
  { id: 'celo', name: 'Celo', gruppe: 'rap', antwort: 'celo', hinweis: 'Celo, eine Hälfte von Celo & Abdi aus Frankfurt.', titel: ['Celo & Abdi'], suche: 'Celo rapper Frankfurt' },
  { id: 'abdi', name: 'Abdi', gruppe: 'rap', antwort: 'abdi', hinweis: 'Abdi, die andere Hälfte von Celo & Abdi.', titel: ['Abdi Abdullahi'], suche: 'Abdi rapper portrait' },
  { id: 'nate', name: 'Nate57', gruppe: 'rap', antwort: 'nate', hinweis: 'Nate57, Rapper aus Hamburg.', titel: ['Nate57'], suche: 'Nate57' },
  { id: 'veysel', name: 'Veysel', gruppe: 'rap', antwort: 'veysel', hinweis: 'Veysel, Rapper aus Essen.', titel: ['Veysel (Rapper)'], suche: 'Veysel rapper' },
  { id: 'badmomz', name: 'Badmómzjay', gruppe: 'rap', antwort: 'badmomz', hinweis: 'Badmómzjay, Rapperin aus Berlin.', titel: ['Badmómzjay'], suche: 'Badmomzjay' },
  { id: 'katja', name: 'Katja Krasavice', gruppe: 'rap', antwort: 'katja', hinweis: 'Katja Krasavice, Sängerin und Rapperin aus Dresden.', titel: ['Katja Krasavice'], suche: 'Katja Krasavice' },
  { id: 'nina', name: 'Nina Chuba', gruppe: 'rap', antwort: 'nina', hinweis: 'Nina Chuba, Sängerin und Rapperin aus Wedel.', titel: ['Nina Chuba'], suche: 'Nina Chuba' },
  { id: 'frauenarzt', name: 'Frauenarzt', gruppe: 'rap', antwort: 'frauenarzt', hinweis: 'Frauenarzt, Berliner Rapper, eine Hälfte der Atzen.', titel: ['Frauenarzt (Rapper)'], suche: 'Frauenarzt rapper' },
  { id: 'manny', name: 'Manny Marc', gruppe: 'rap', antwort: 'manny', hinweis: 'Manny Marc, Berliner Rapper, die andere Hälfte der Atzen.', titel: ['Manny Marc'], suche: 'Manny Marc' },
  { id: 'ignaz', name: 'Crack Ignaz', gruppe: 'rap', antwort: 'ignaz', hinweis: 'Crack Ignaz, Rapper aus Berlin.', titel: ['Crack Ignaz'], suche: 'Crack Ignaz' },

  { id: 'aston', name: 'Aston Martin', gruppe: 'autos', hinweis: 'Die Flügel stehen für die Fluginsekten des Firmennamens, die Wagen kommen aus Gaydon.', titel: ['Aston Martin DB11'], suche: 'Aston Martin DB11 photo' },
  { id: 'dodge', name: 'Dodge', gruppe: 'autos', hinweis: 'Der Widderkopf, die Muscle-Cars aus den USA.', titel: ['Dodge Challenger'], suche: 'Dodge Challenger photo' },
  { id: 'cadillac', name: 'Cadillac', gruppe: 'autos', hinweis: 'Das Wappen erinnert an Antoine de la Mothe Cadillac.', titel: ['Cadillac Escalade'], suche: 'Cadillac Escalade photo' },
  { id: 'mitsubishi', name: 'Mitsubishi', gruppe: 'autos', hinweis: 'Die drei Rauten sind das Zeichen der Familie Iwasaki.', titel: ['Mitsubishi Lancer'], suche: 'Mitsubishi Lancer front photo' },
  { id: 'infiniti', name: 'Infiniti', gruppe: 'autos', hinweis: 'Die Edelmarke von Nissan, das Oval mit dem Weg zur Unendlichkeit.', titel: ['Infiniti Q50'], suche: 'Infiniti Q50 photo' },
  { id: 'pagani', name: 'Pagani', gruppe: 'autos', hinweis: 'Die Wagen von Horacio Pagani aus Modena.', titel: ['Pagani Huayra'], suche: 'Pagani Huayra photo' },
  { id: 'koenig', name: 'Koenigsegg', gruppe: 'autos', hinweis: 'Der Geist im Schild, die Supersportwagen aus Ängelholm.', titel: ['Koenigsegg Jesko'], suche: 'Koenigsegg Jesko photo' },
  { id: 'alpine', name: 'Alpine', gruppe: 'autos', hinweis: 'Das A mit dem Pfeil, die Sportwagen aus Dieppe.', titel: ['Alpine A110 (2017)'], suche: 'Alpine A110 photo' },
  { id: 'lancia', name: 'Lancia', gruppe: 'autos', hinweis: 'Das Lenkrad und die Lanze, die Marke aus Turin.', titel: ['Lancia Delta'], suche: 'Lancia Delta photo' },
  { id: 'genesis', name: 'Genesis', gruppe: 'autos', hinweis: 'Die Edelmarke von Hyundai, das Wappen mit den Flügeln.', titel: ['Genesis G70'], suche: 'Genesis G70 photo' },
  { id: 'polestar', name: 'Polestar', gruppe: 'autos', hinweis: 'Der Polarstern, die Elektromarke aus dem Volvo-Umfeld.', titel: ['Polestar 2'], suche: 'Polestar 2 photo' },
  { id: 'lotuscar', name: 'Lotus', gruppe: 'autos', hinweis: 'Die leichten Sportwagen von Colin Chapman aus Hethel.', titel: [], suche: 'Lotus Elise sports car' },
  { id: 'morgan', name: 'Morgan', gruppe: 'autos', hinweis: 'Die offenen Wagen mit dem langen Blech, aus Malvern.', titel: ['Morgan Plus Six'], suche: 'Morgan car photo' },
  { id: 'saab', name: 'Saab', gruppe: 'autos', hinweis: 'Der Greif, die Wagen aus Trollhättan, ursprünglich ein Flugzeugwerk.', titel: [], suche: 'Saab 900 car front' },
  { id: 'mg', name: 'MG', gruppe: 'autos', hinweis: 'Die Oktagon-Marke, Morris Garages aus Abingdon.', titel: ['MG B'], suche: 'MGB roadster photo' },
  { id: 'daihatsu', name: 'Daihatsu', gruppe: 'autos', hinweis: 'Das stilisierte D, die Kleinwagen aus Osaka.', titel: [], suche: 'Daihatsu Copen exterior' },
  { id: 'isuzu', name: 'Isuzu', gruppe: 'autos', hinweis: 'Die zwei Stangen, der Name ist ein Fluss in Japan.', titel: ['Isuzu D-Max'], suche: 'Isuzu D-Max photo' },
  { id: 'lincoln', name: 'Lincoln', gruppe: 'autos', hinweis: 'Das Sternenkreuz, die Edelmarke von Ford.', titel: ['Lincoln Navigator'], suche: 'Lincoln Navigator photo' },

  { id: 'pisa', name: 'Schiefer Turm von Pisa', gruppe: 'orte', hinweis: 'Der Glockenturm in Pisa steht seit dem 12. Jahrhundert schief.', titel: ['Schiefer Turm von Pisa'], suche: 'Leaning Tower of Pisa' },
  { id: 'petra', name: 'Petra', gruppe: 'orte', hinweis: 'Die in den Fels geschlagene Stadt in Jordanien, bekannt durch das Schatzhaus.', titel: ['Petra (Jordanien)'], suche: 'Petra Treasury Jordan' },
  { id: 'machu', name: 'Machu Picchu', gruppe: 'orte', hinweis: 'Die Inka-Stadt in den Anden über dem Urubamba.', titel: ['Machu Picchu'], suche: 'Machu Picchu' },
  { id: 'christus', name: 'Christusstatue', gruppe: 'orte', hinweis: 'Cristo Redentor steht mit ausgebreiteten Armen über Rio de Janeiro.', titel: ['Cristo Redentor (Rio de Janeiro)'], suche: 'Christ the Redeemer Rio' },
  { id: 'stonehenge', name: 'Stonehenge', gruppe: 'orte', hinweis: 'Der Steinkreis in Wiltshire, gesetzt in der Jungsteinzeit.', titel: ['Stonehenge'], suche: 'Stonehenge' },
  { id: 'akropolis', name: 'Akropolis', gruppe: 'orte', hinweis: 'Der Burgberg in Athen, darauf der Parthenon.', titel: ['Akropolis'], suche: 'Acropolis Athens Parthenon' },
  { id: 'petronas', name: 'Petronas Towers', gruppe: 'orte', hinweis: 'Die beiden Türme in Kuala Lumpur, verbunden durch eine Brücke.', titel: ['Petronas Towers'], suche: 'Petronas Towers' },
  { id: 'burj', name: 'Burj Khalifa', gruppe: 'orte', hinweis: 'Der höchste Turm der Welt, in Dubai.', titel: ['Burj Khalifa'], suche: 'Burj Khalifa' },
  { id: 'goldengate', name: 'Golden Gate Bridge', gruppe: 'orte', hinweis: 'Die rote Hängebrücke über die Bucht von San Francisco.', titel: ['Golden Gate Bridge'], suche: 'Golden Gate Bridge' },
  { id: 'towerbridge', name: 'Tower Bridge', gruppe: 'orte', hinweis: 'Die Klappbrücke in London, neben dem Tower.', titel: ['Tower Bridge'], suche: 'Tower Bridge London' },
  { id: 'reichstag', name: 'Reichstag', gruppe: 'orte', hinweis: 'Das Parlamentsgebäude in Berlin, oben die Glaskuppel von Norman Foster.', titel: ['Reichstagsgebäude'], suche: 'Reichstag Berlin dome' },
  { id: 'frauenkirche', name: 'Frauenkirche Dresden', gruppe: 'orte', hinweis: 'Die barocke Kirche am Neumarkt, nach dem Krieg wieder aufgebaut.', titel: ['Frauenkirche (Dresden)'], suche: 'Frauenkirche Dresden' },
  { id: 'ulm', name: 'Ulmer Münster', gruppe: 'orte', hinweis: 'Der höchste Kirchturm der Welt steht in Ulm.', titel: ['Ulmer Münster'], suche: 'Ulm Minster' },
  { id: 'versaille', name: 'Schloss Versailles', gruppe: 'orte', hinweis: 'Die Residenz Ludwigs XIV. vor den Toren von Paris.', titel: ['Schloss Versailles'], suche: 'Palace of Versailles' },
  { id: 'buckingham', name: 'Buckingham Palace', gruppe: 'orte', hinweis: 'Die Londoner Residenz des britischen Monarchen.', titel: ['Buckingham Palace'], suche: 'Buckingham Palace' },
  { id: 'kreml', name: 'Kreml', gruppe: 'orte', hinweis: 'Die Festung in Moskau, an der Mauer die roten Türme.', titel: ['Moskauer Kreml'], suche: 'Moscow Kremlin' },
  { id: 'hagia', name: 'Hagia Sophia', gruppe: 'orte', hinweis: 'Die ehemalige Kirche in Istanbul, mit der großen Kuppel.', titel: ['Hagia Sophia'], suche: 'Hagia Sophia' },
  { id: 'angkor', name: 'Angkor Wat', gruppe: 'orte', hinweis: 'Die Tempelanlage in Kambodscha, mit den fünf Türmen.', titel: ['Angkor Wat'], suche: 'Angkor Wat' },
  { id: 'chichen', name: 'Chichén Itzá', gruppe: 'orte', hinweis: 'Die Stufenpyramide der Maya auf Yucatán.', titel: ['Chichén Itzá'], suche: 'Chichen Itza pyramid' },
  { id: 'moai', name: 'Moai', gruppe: 'orte', hinweis: 'Die Steinköpfe auf der Osterinsel.', titel: ['Moai'], suche: 'Moai Easter Island' },
  { id: 'niagara', name: 'Niagarafälle', gruppe: 'orte', hinweis: 'Die Fälle an der Grenze zwischen Kanada und den USA.', titel: ['Niagarafälle'], suche: 'Niagara Falls' },
  { id: 'matterhorn', name: 'Matterhorn', gruppe: 'orte', hinweis: 'Der spitze Gipfel über Zermatt, an der Grenze zur Italien.', titel: ['Matterhorn'], suche: 'Matterhorn' },
  { id: 'fuji', name: 'Fuji', gruppe: 'orte', hinweis: 'Der Vulkan mit dem Schneehut, das Wahrzeichen Japans.', titel: [], suche: 'Mount Fuji photograph snow' },
  { id: 'canyon', name: 'Grand Canyon', gruppe: 'orte', hinweis: 'Die Schlucht des Colorado in Arizona.', titel: ['Grand Canyon'], suche: 'Grand Canyon' },
  { id: 'uluru', name: 'Uluru', gruppe: 'orte', hinweis: 'Der rote Felsen im Zentrum Australiens, auch Ayers Rock genannt.', titel: ['Uluru'], suche: 'Uluru' },
  { id: 'santorin', name: 'Santorin', gruppe: 'orte', hinweis: 'Die weißen Häuser über der Caldera in der Ägäis.', titel: [], suche: 'Oia Santorini white houses' },
  { id: 'markusdom', name: 'Markusdom', gruppe: 'orte', hinweis: 'Die Kirche am Markusplatz in Venedig, mit den fünf Kuppeln.', titel: ['Markusdom'], suche: 'St Mark Basilica Venice' },
  { id: 'atomium', name: 'Atomium', gruppe: 'orte', hinweis: 'Die neun Kugeln in Brüssel, gebaut für die Weltausstellung 1958.', titel: ['Atomium'], suche: 'Atomium Brussels' },
  { id: 'louvre', name: 'Louvre', gruppe: 'orte', hinweis: 'Die Glaspyramide im Hof des Museums in Paris.', titel: ['Louvre'], suche: 'Louvre Pyramid' },
  { id: 'montsaint', name: 'Mont-Saint-Michel', gruppe: 'orte', hinweis: 'Die Abtei auf der Gezeiteninsel in der Normandie.', titel: ['Mont-Saint-Michel'], suche: 'Mont Saint Michel' },
  { id: 'alhambra', name: 'Alhambra', gruppe: 'orte', hinweis: 'Die Palastanlage der Nasriden über Granada.', titel: [], suche: 'Alhambra palace courtyard photo' },
  { id: 'sacre', name: 'Sacré-Cœur', gruppe: 'orte', hinweis: 'Die weiße Kirche auf dem Montmartre in Paris.', titel: ['Sacré-Cœur de Montmartre'], suche: 'Sacre Coeur Paris' },
  { id: 'notredame', name: 'Notre-Dame', gruppe: 'orte', hinweis: 'Die Kathedrale auf der Île de la Cité in Paris.', titel: [], suche: 'Notre-Dame cathedral facade Paris' },
  { id: 'fernsehturm', name: 'Fernsehturm Berlin', gruppe: 'orte', hinweis: 'Die Kugel am Schaft am Alexanderplatz.', titel: ['Berliner Fernsehturm'], suche: 'Berlin TV tower' },
  { id: 'zugspitze', name: 'Zugspitze', gruppe: 'orte', hinweis: 'Der höchste Berg Deutschlands, über Garmisch-Partenkirchen.', titel: ['Zugspitze'], suche: 'Zugspitze summit' },
  { id: 'elphi', name: 'Elbphilharmonie', gruppe: 'orte', hinweis: 'Die Glaswelle auf dem Kaispeicher in Hamburg.', titel: ['Elbphilharmonie'], suche: 'Elbphilharmonie' },
  { id: 'stephansdom', name: 'Stephansdom', gruppe: 'orte', hinweis: 'Die Kathedrale in Wien, mit dem bunten Ziegeldach.', titel: ['Stephansdom'], suche: 'St Stephen Cathedral Vienna' },
  { id: 'karlsbruecke', name: 'Karlsbrücke', gruppe: 'orte', hinweis: 'Die Steinbrücke über die Moldau in Prag, gesäumt von Statuen.', titel: ['Karlsbrücke'], suche: 'Charles Bridge Prague' },
  { id: 'basilius', name: 'Basilius-Kathedrale', gruppe: 'orte', hinweis: 'Die bunten Zwiebeltürme am Roten Platz in Moskau.', titel: ['Basilius-Kathedrale'], suche: 'Saint Basil Cathedral' },
  { id: 'petersdom', name: 'Petersdom', gruppe: 'orte', hinweis: 'Die Kirche im Vatikan, davor der Petersplatz mit der Kolonnade.', titel: ['Petersdom'], suche: 'St Peter Basilica' },
  { id: 'mailand', name: 'Mailänder Dom', gruppe: 'orte', hinweis: 'Die Marmorkathedrale mit dem Wald aus Fialen.', titel: ['Mailänder Dom'], suche: 'Milan Cathedral' },
  { id: 'heidelberg', name: 'Schloss Heidelberg', gruppe: 'orte', hinweis: 'Die Ruine über der Altstadt am Neckar.', titel: ['Heidelberger Schloss'], suche: 'Heidelberg Castle' },
  { id: 'sanssouci', name: 'Schloss Sanssouci', gruppe: 'orte', hinweis: 'Das Sommerschloss Friedrichs II. in Potsdam.', titel: ['Schloss Sanssouci'], suche: 'Sanssouci' },
  { id: 'holstentor', name: 'Holstentor', gruppe: 'orte', hinweis: 'Das Stadttor in Lübeck, mit den zwei runden Türmen.', titel: ['Holstentor'], suche: 'Holstentor Lubeck' },
  { id: 'semper', name: 'Semperoper', gruppe: 'orte', hinweis: 'Das Opernhaus von Gottfried Semper in Dresden.', titel: ['Semperoper'], suche: 'Semperoper' },
  { id: 'speicherstadt', name: 'Speicherstadt', gruppe: 'orte', hinweis: 'Die Backsteinlagerhäuser auf den Fleeten in Hamburg.', titel: ['Speicherstadt'], suche: 'Speicherstadt Hamburg' },
  { id: 'walhalla', name: 'Walhalla', gruppe: 'orte', hinweis: 'Die Ruhmeshalle über der Donau bei Donaustauf.', titel: ['Walhalla'], suche: 'Walhalla Donaustauf' },
  { id: 'linderhof', name: 'Schloss Linderhof', gruppe: 'orte', hinweis: 'Das kleinste Schloss Ludwigs II., in den Ammergauer Alpen.', titel: ['Schloss Linderhof'], suche: 'Linderhof Palace' },
  { id: 'sphinx', name: 'Sphinx von Gizeh', gruppe: 'orte', hinweis: 'Der Löwe mit dem Menschenkopf vor den Pyramiden.', titel: ['Große Sphinx von Gizeh'], suche: 'Great Sphinx Giza' },
  { id: 'harbour', name: 'Sydney Harbour Bridge', gruppe: 'orte', hinweis: 'Der Stahlbogen neben dem Opernhaus.', titel: ['Sydney Harbour Bridge'], suche: 'Sydney Harbour Bridge' },
  { id: 'rushmore', name: 'Mount Rushmore', gruppe: 'orte', hinweis: 'Vier Präsidentenköpfe im Fels in South Dakota.', titel: ['Mount Rushmore'], suche: 'Mount Rushmore' },
  { id: 'empire', name: 'Empire State Building', gruppe: 'orte', hinweis: 'Der Wolkenkratzer in Manhattan, mit dem Mast auf dem Dach.', titel: ['Empire State Building'], suche: 'Empire State Building' },
  { id: 'brooklyn', name: 'Brooklyn Bridge', gruppe: 'orte', hinweis: 'Die Hängebrücke zwischen Manhattan und Brooklyn.', titel: ['Brooklyn Bridge'], suche: 'Brooklyn Bridge' },
  { id: 'halfdome', name: 'Half Dome', gruppe: 'orte', hinweis: 'Der Granitdom im Yosemite-Tal.', titel: ['Half Dome'], suche: 'Half Dome Yosemite' },
  { id: 'cntower', name: 'CN Tower', gruppe: 'orte', hinweis: 'Der Betonturm in Toronto, mit der Kapsel in der Höhe.', titel: ['CN Tower'], suche: 'CN Tower Toronto' },
  { id: 'galata', name: 'Galataturm', gruppe: 'orte', hinweis: 'Der mittelalterliche Turm in Istanbul, auf der europäischen Seite.', titel: ['Galataturm'], suche: 'Galata Tower' },
  { id: 'sheikh', name: 'Scheich-Zayid-Moschee', gruppe: 'orte', hinweis: 'Die weiße Moschee in Abu Dhabi.', titel: [], suche: 'Sheikh Zayed Grand Mosque domes' },
  { id: 'victoria', name: 'Victoriafälle', gruppe: 'orte', hinweis: 'Die Fälle des Sambesi zwischen Sambia und Simbabwe.', titel: ['Victoriafälle'], suche: 'Victoria Falls' },
  { id: 'tafelberg', name: 'Tafelberg', gruppe: 'orte', hinweis: 'Der flache Berg über Kapstadt.', titel: ['Tafelberg'], suche: 'Table Mountain Cape Town' },
  { id: 'parkguell', name: 'Park Güell', gruppe: 'orte', hinweis: 'Der Park von Antoni Gaudí in Barcelona, mit der Drachentreppe.', titel: ['Park Güell'], suche: 'Park Guell' },
  { id: 'casabat', name: 'Casa Batlló', gruppe: 'orte', hinweis: 'Das Haus von Gaudí am Passeig de Gràcia, die Fassade erinnert an Knochen.', titel: ['Casa Batlló'], suche: 'Casa Batllo' },
  { id: 'arc', name: 'Arc de Triomphe', gruppe: 'orte', hinweis: 'Der Triumphbogen auf dem Platz Charles-de-Gaulle in Paris.', titel: ['Arc de Triomphe'], suche: 'Arc de Triomphe Paris' },
  { id: 'mostar', name: 'Stari Most', gruppe: 'orte', hinweis: 'Die alte Bogenbrücke über die Neretva in Mostar.', titel: ['Stari Most'], suche: 'Stari Most Mostar' },
  { id: 'blauemoschee', name: 'Blaue Moschee', gruppe: 'orte', hinweis: 'Die Sultan-Ahmed-Moschee in Istanbul, mit den sechs Minaretten.', titel: ['Sultan-Ahmed-Moschee'], suche: 'Blue Mosque Istanbul' },
  { id: 'himmelstempel', name: 'Himmelstempel', gruppe: 'orte', hinweis: 'Die runde Halle in Peking, in der der Kaiser für die Ernte betete.', titel: ['Himmelstempel'], suche: 'Temple of Heaven' },
  { id: 'verboten', name: 'Verbotene Stadt', gruppe: 'orte', hinweis: 'Der Palastkomplex in Peking, mit den gelben Dächern.', titel: ['Verbotene Stadt'], suche: 'Forbidden City Beijing' },
  { id: 'kiyomizu', name: 'Kiyomizu-dera', gruppe: 'orte', hinweis: 'Der Tempel in Kyōto auf der hölzernen Bühne über dem Hang.', titel: ['Kiyomizu-dera'], suche: 'Kiyomizu-dera' },
  { id: 'iguazu', name: 'Iguazú-Wasserfälle', gruppe: 'orte', hinweis: 'Die Fälle an der Grenze von Argentinien und Brasilien.', titel: [], suche: 'Iguazu Falls waterfall' },
  { id: 'zuckerhut', name: 'Zuckerhut', gruppe: 'orte', hinweis: 'Der Felskegel in der Bucht von Rio de Janeiro.', titel: [], suche: 'Sugarloaf Mountain Rio de Janeiro peak' },
  { id: 'teotihuacan', name: 'Teotihuacán', gruppe: 'orte', hinweis: 'Die Sonnenpyramide in der alten Stadt nördlich von Mexiko-Stadt.', titel: ['Teotihuacán'], suche: 'Teotihuacan pyramid' },

  { id: 'tiger', name: 'Tiger', gruppe: 'natur', hinweis: 'Die größte Katze, das Fell ist orange mit schwarzen Streifen.', titel: ['Tiger'], suche: 'tiger animal' },
  { id: 'zebra', name: 'Zebra', gruppe: 'natur', hinweis: 'Das Pferd mit den schwarz-weißen Streifen, aus Afrika.', titel: ['Steppenzebra'], suche: 'zebra' },
  { id: 'koala', name: 'Koala', gruppe: 'natur', hinweis: 'Der Beutler aus Australien, er schläft in Eukalyptusbäumen.', titel: ['Koala'], suche: 'koala' },
  { id: 'kaenguru', name: 'Känguru', gruppe: 'natur', hinweis: 'Es springt auf den Hinterbeinen und trägt das Junge im Beutel.', titel: ['Rotes Riesenkänguru'], suche: 'kangaroo' },
  { id: 'wolf', name: 'Wolf', gruppe: 'natur', hinweis: 'Der Vorfahr des Hundes, er jagt im Rudel.', titel: ['Wolf'], suche: 'grey wolf' },
  { id: 'baer', name: 'Braunbär', gruppe: 'natur', hinweis: 'Der große Bär mit dem Buckel, in Europa und Nordamerika.', titel: ['Braunbär'], suche: 'brown bear' },
  { id: 'eisbaer', name: 'Eisbär', gruppe: 'natur', hinweis: 'Das Fell ist weiß, die Haut darunter schwarz. Er lebt in der Arktis.', titel: ['Eisbär'], suche: 'polar bear' },
  { id: 'gorilla', name: 'Gorilla', gruppe: 'natur', hinweis: 'Der größte Menschenaffe, er lebt in den Wäldern Afrikas.', titel: ['Gorillas'], suche: 'gorilla' },
  { id: 'schimpanse', name: 'Schimpanse', gruppe: 'natur', hinweis: 'Der Menschenaffe mit den großen Ohren, eng verwandt mit dem Menschen.', titel: ['Schimpanse'], suche: 'chimpanzee' },
  { id: 'nashorn', name: 'Nashorn', gruppe: 'natur', hinweis: 'Das Horn sitzt auf der Nase, die Haut ist dick und gefaltet.', titel: ['Breitmaulnashorn'], suche: 'white rhinoceros' },
  { id: 'nilpferd', name: 'Nilpferd', gruppe: 'natur', hinweis: 'Es liegt tagsüber im Wasser, nachts grast es an Land.', titel: ['Flusspferd'], suche: 'hippopotamus' },
  { id: 'krokodil', name: 'Krokodil', gruppe: 'natur', hinweis: 'Das Reptil mit der langen Schnauze, es lauert am Ufer.', titel: ['Nilkrokodil'], suche: 'nile crocodile' },
  { id: 'python', name: 'Python', gruppe: 'natur', hinweis: 'Die Würgeschlange, sie legt sich um die Beute.', titel: ['Netzpython'], suche: 'reticulated python' },
  { id: 'adler', name: 'Adler', gruppe: 'natur', hinweis: 'Der große Greif mit dem Hakenschnabel.', titel: ['Steinadler'], suche: 'golden eagle' },
  { id: 'flamingo', name: 'Flamingo', gruppe: 'natur', hinweis: 'Der rosa Vogel steht oft auf einem Bein.', titel: ['Flamingos'], suche: 'flamingo' },
  { id: 'pfau', name: 'Pfau', gruppe: 'natur', hinweis: 'Das Männchen schlägt das Rad mit den Augenflecken.', titel: ['Blauer Pfau'], suche: 'peacock' },
  { id: 'schwan', name: 'Schwan', gruppe: 'natur', hinweis: 'Der große weiße Vogel mit dem gebogenen Hals.', titel: ['Höckerschwan'], suche: 'mute swan' },
  { id: 'storch', name: 'Storch', gruppe: 'natur', hinweis: 'Der weiß-schwarze Vogel mit dem langen roten Schnabel.', titel: ['Weißstorch'], suche: 'white stork' },
  { id: 'ara', name: 'Ara', gruppe: 'natur', hinweis: 'Der große Papagei, oft rot oder blau, aus Südamerika.', titel: ['Gelbbrustara'], suche: 'macaw' },
  { id: 'tukan', name: 'Tukan', gruppe: 'natur', hinweis: 'Der Vogel mit dem übergroßen bunten Schnabel.', titel: ['Riesentukan'], suche: 'toucan' },
  { id: 'chamaeleon', name: 'Chamäleon', gruppe: 'natur', hinweis: 'Es wechselt die Farbe und bewegt die Augen unabhängig.', titel: ['Chamäleons'], suche: 'chameleon' },
  { id: 'schildkroete', name: 'Schildkröte', gruppe: 'natur', hinweis: 'Der Panzer schützt den Körper, an Land und im Meer.', titel: ['Grüne Meeresschildkröte'], suche: 'sea turtle' },
  { id: 'buckelwal', name: 'Buckelwal', gruppe: 'natur', hinweis: 'Der Wal mit den langen Brustflossen, bekannt für den Gesang.', titel: ['Buckelwal'], suche: 'humpback whale' },
  { id: 'orca', name: 'Orca', gruppe: 'natur', hinweis: 'Der schwarz-weiße Zahnwal, auch Schwertwal genannt.', titel: ['Schwertwal'], suche: 'orca' },
  { id: 'hai', name: 'Hai', gruppe: 'natur', hinweis: 'Der Knorpelfisch mit der Rückenflosse, die aus dem Wasser ragt.', titel: ['Weißer Hai'], suche: 'great white shark' },
  { id: 'qualle', name: 'Qualle', gruppe: 'natur', hinweis: 'Der gallertige Schirm mit den Tentakeln, ohne Gehirn.', titel: ['Ohrenqualle'], suche: 'jellyfish' },
  { id: 'seestern', name: 'Seestern', gruppe: 'natur', hinweis: 'Meist fünf Arme, er lebt auf dem Meeresboden.', titel: ['Seesterne'], suche: 'starfish' },
  { id: 'krake', name: 'Krake', gruppe: 'natur', hinweis: 'Acht Arme mit Saugnäpfen, er kann die Farbe wechseln.', titel: ['Gemeiner Krake'], suche: 'octopus' },
  { id: 'biene', name: 'Biene', gruppe: 'natur', hinweis: 'Sie sammelt Nektar und bestäubt Blüten, im Stock entsteht Honig.', titel: ['Westliche Honigbiene'], suche: 'honey bee' },
  { id: 'schmetterling', name: 'Schmetterling', gruppe: 'natur', hinweis: 'Die Flügel sind mit Schuppen bedeckt, die Raupe ist die Larve.', titel: ['Tagpfauenauge'], suche: 'peacock butterfly' },
  { id: 'marienkaefer', name: 'Marienkäfer', gruppe: 'natur', hinweis: 'Der kleine Käfer mit den Punkten auf den roten Flügeln.', titel: ['Siebenpunkt-Marienkäfer'], suche: 'ladybug' },
  { id: 'ameise', name: 'Ameise', gruppe: 'natur', hinweis: 'Sie lebt im Staat, mit Königin, Arbeiterinnen und Soldaten.', titel: ['Rote Waldameise'], suche: 'ant insect' },
  { id: 'spinne', name: 'Spinne', gruppe: 'natur', hinweis: 'Acht Beine, viele Arten bauen ein Netz.', titel: ['Gartenkreuzspinne'], suche: 'garden spider close' },
  { id: 'skorpion', name: 'Skorpion', gruppe: 'natur', hinweis: 'Die Scheren vorn, der Stachel am gebogenen Schwanz.', titel: ['Skorpione'], suche: 'scorpion' },
  { id: 'frosch', name: 'Frosch', gruppe: 'natur', hinweis: 'Er beginnt als Kaulquappe im Wasser und springt später an Land.', titel: ['Grasfrosch'], suche: 'frog' },
  { id: 'salamander', name: 'Feuersalamander', gruppe: 'natur', hinweis: 'Schwarz mit gelben Flecken, er lebt in feuchten Wäldern.', titel: ['Feuersalamander'], suche: 'fire salamander' },
  { id: 'igel', name: 'Igel', gruppe: 'natur', hinweis: 'Die Stacheln sind verhornte Haare, bei Gefahr rollt er sich ein.', titel: ['Braunbrustigel'], suche: 'hedgehog' },
  { id: 'dachs', name: 'Dachs', gruppe: 'natur', hinweis: 'Der schwarze Streifen über dem weißen Kopf, er gräbt einen Bau.', titel: ['Europäischer Dachs'], suche: 'european badger' },
  { id: 'otter', name: 'Otter', gruppe: 'natur', hinweis: 'Der Marder am Wasser, er schwimmt mit dem Ruderschwanz.', titel: ['Fischotter'], suche: 'eurasian otter' },
  { id: 'waschbaer', name: 'Waschbär', gruppe: 'natur', hinweis: 'Die schwarze Maske und der geringelte Schwanz.', titel: ['Waschbär'], suche: 'raccoon' },
  { id: 'faultier', name: 'Faultier', gruppe: 'natur', hinweis: 'Es hängt kopfüber in den Bäumen Südamerikas und bewegt sich sehr langsam.', titel: ['Faultiere'], suche: 'sloth' },
  { id: 'gepard', name: 'Gepard', gruppe: 'natur', hinweis: 'Die schnellste Katze, das Fell hat volle Punkte, keine Rosetten.', titel: ['Gepard'], suche: 'cheetah' },
  { id: 'leopard', name: 'Leopard', gruppe: 'natur', hinweis: 'Die Katze mit den Rosetten, sie klettert und legt Beute in Bäume.', titel: ['Leopard'], suche: 'leopard' },
  { id: 'schneeleopard', name: 'Schneeleopard', gruppe: 'natur', hinweis: 'Die graue Katze mit den dicken Flecken, sie lebt im Hochgebirge Asiens.', titel: ['Schneeleopard'], suche: 'snow leopard' },
  { id: 'kamel', name: 'Kamel', gruppe: 'natur', hinweis: 'Das Dromedar hat einen Höcker, das Trampeltier zwei.', titel: ['Dromedar'], suche: 'dromedary camel' },
  { id: 'alpaka', name: 'Alpaka', gruppe: 'natur', hinweis: 'Das Höckertier aus den Anden, kleiner als das Lama, mit dichter Wolle.', titel: ['Alpaka'], suche: 'alpaca' },
  { id: 'rentier', name: 'Rentier', gruppe: 'natur', hinweis: 'Beide Geschlechter tragen ein Geweih, es lebt im Norden.', titel: [], suche: 'reindeer rangifer tarandus' },
  { id: 'elch', name: 'Elch', gruppe: 'natur', hinweis: 'Der größte Hirsch, das Geweih ist schaufelförmig.', titel: ['Elch'], suche: 'moose' },
  { id: 'hirsch', name: 'Rothirsch', gruppe: 'natur', hinweis: 'Das Männchen trägt ein verzweigtes Geweih, das es jährlich abwirft.', titel: ['Rothirsch'], suche: 'red deer stag' },
  { id: 'wildschwein', name: 'Wildschwein', gruppe: 'natur', hinweis: 'Die borstige Sau mit dem Rüssel, die Frischlinge sind gestreift.', titel: ['Wildschwein'], suche: 'wild boar' },
  { id: 'hase', name: 'Feldhase', gruppe: 'natur', hinweis: 'Die langen Ohren mit den schwarzen Spitzen, er lebt auf dem Feld.', titel: ['Feldhase'], suche: 'european hare' },
  { id: 'eichhoernchen', name: 'Eichhörnchen', gruppe: 'natur', hinweis: 'Der buschige Schwanz, es vergräbt Nüsse als Vorrat.', titel: ['Eurasisches Eichhörnchen'], suche: 'red squirrel' },
  { id: 'fledermaus', name: 'Fledermaus', gruppe: 'natur', hinweis: 'Das einzige Säugetier, das aktiv fliegt, die Flügel sind Haut zwischen den Fingern.', titel: ['Großer Abendsegler'], suche: 'bat flying' },
  { id: 'tulpe', name: 'Tulpe', gruppe: 'natur', hinweis: 'Die Blüte ist ein Kelch, berühmt aus den Niederlanden, ursprünglich aus Zentralasien.', titel: ['Tulpen'], suche: 'tulip flower' },
  { id: 'lavendel', name: 'Lavendel', gruppe: 'natur', hinweis: 'Die violetten Ähren, der Duft kommt aus der Provence.', titel: ['Lavendel'], suche: 'lavender field' },
  { id: 'lotusblume', name: 'Lotus', gruppe: 'natur', hinweis: 'Die Wasserpflanze mit der großen Blüte, die Blätter perlen ab.', titel: ['Lotosblume'], suche: 'lotus flower' },
  { id: 'ahorn', name: 'Ahorn', gruppe: 'natur', hinweis: 'Das Blatt ist handförmig, die Frucht ist eine Flügelfrucht.', titel: [], suche: 'maple leaf close-up' },
  { id: 'birke', name: 'Birke', gruppe: 'natur', hinweis: 'Die Rinde ist weiß und löst sich in Streifen.', titel: [], suche: 'silver birch tree white bark' },
  { id: 'palme', name: 'Palme', gruppe: 'natur', hinweis: 'Der Stamm ist unverzweigt, die Blätter sitzen als Schopf oben.', titel: ['Dattelpalme'], suche: 'date palm' },
  { id: 'bambus', name: 'Bambus', gruppe: 'natur', hinweis: 'Ein Gras mit hohlen Halmen, es wächst sehr schnell.', titel: ['Bambus'], suche: 'bamboo' },
  { id: 'fliegenpilz', name: 'Fliegenpilz', gruppe: 'natur', hinweis: 'Der rote Hut mit den weißen Punkten.', titel: ['Fliegenpilz'], suche: 'fly agaric' },
  { id: 'steinpilz', name: 'Steinpilz', gruppe: 'natur', hinweis: 'Der dicke Stiel und der braune Hut, ein Speisepilz.', titel: ['Steinpilz'], suche: 'porcini' },
  { id: 'loewenzahn', name: 'Löwenzahn', gruppe: 'natur', hinweis: 'Die gelbe Blüte wird zur Pusteblume.', titel: ['Löwenzahn'], suche: 'dandelion flower' },
  { id: 'gaensebluemchen', name: 'Gänseblümchen', gruppe: 'natur', hinweis: 'Die kleine Blüte mit den weißen Zungen und der gelben Mitte.', titel: ['Gänseblümchen'], suche: 'daisy flower' },
  { id: 'orchidee', name: 'Orchidee', gruppe: 'natur', hinweis: 'Die Blüte ist spiegelsymmetrisch, viele Arten wachsen auf Bäumen.', titel: ['Phalaenopsis'], suche: 'orchid flower' },
  { id: 'lilie', name: 'Lilie', gruppe: 'natur', hinweis: 'Die großen trompetenförmigen Blüten, oft weiß.', titel: ['Madonnenlilie'], suche: 'white lily flower' },
  { id: 'mohn', name: 'Klatschmohn', gruppe: 'natur', hinweis: 'Die rote Blüte am Feldrand, die Knospe nickt.', titel: [], suche: 'red poppy flower field photo' },
  { id: 'klee', name: 'Klee', gruppe: 'natur', hinweis: 'Das Blatt hat drei Fieder, selten vier.', titel: ['Weißklee'], suche: 'clover' },
  { id: 'aloe', name: 'Aloe', gruppe: 'natur', hinweis: 'Die dicken Blätter speichern Wasser, der Saft sitzt im Inneren.', titel: ['Echte Aloe'], suche: 'aloe vera plant' },
  { id: 'venus', name: 'Venusfliegenfalle', gruppe: 'natur', hinweis: 'Die Blätter klappen zu, wenn ein Insekt die Borsten berührt.', titel: ['Venusfliegenfalle'], suche: 'venus flytrap' },
  { id: 'seerose', name: 'Seerose', gruppe: 'natur', hinweis: 'Die Blüte schwimmt auf dem Wasser, die Blätter sind rund.', titel: ['Weiße Seerose'], suche: 'water lily' },
  { id: 'kiefer', name: 'Kiefer', gruppe: 'natur', hinweis: 'Die Nadeln sitzen zu zweit, die Zapfen sind holzig.', titel: [], suche: 'scots pine tree forest photo' },
  { id: 'weide', name: 'Weide', gruppe: 'natur', hinweis: 'Die Zweige hängen, sie steht oft am Wasser.', titel: [], suche: 'weeping willow tree photograph' },
  { id: 'baobab', name: 'Affenbrotbaum', gruppe: 'natur', hinweis: 'Der dicke Stamm speichert Wasser, die Krone ist sparrig.', titel: ['Afrikanischer Affenbrotbaum'], suche: 'baobab tree' },
  { id: 'ginkgo', name: 'Ginkgo', gruppe: 'natur', hinweis: 'Das Blatt ist fächerförmig, der Baum ist ein lebendes Fossil.', titel: ['Ginkgo'], suche: 'ginkgo leaf' },
  { id: 'edelweiss', name: 'Edelweiß', gruppe: 'natur', hinweis: 'Die wolligen Sterne wachsen in den Alpen.', titel: ['Edelweiß'], suche: 'edelweiss flower' },
  { id: 'kornblume', name: 'Kornblume', gruppe: 'natur', hinweis: 'Die blaue Blüte im Getreidefeld.', titel: ['Kornblume'], suche: 'cornflower' },
]
