// 💻 IT – verstehen, was im Kasten passiert. Kein Zertifikatskurs, sondern die Grundlagen,
// mit denen man ein Netzwerkproblem findet, einen Rechner zusammenstellt, einen Bug sieht
// und einem Kollegen erklären kann, was los ist.
import type { KursDef } from '../../typen'

export const IT: KursDef = {
  id: 'it',
  titel: 'IT',
  emoji: '💻',
  claim: 'Verstehen, was im Kasten passiert.',
  domain: 'technik',
  wissen: 'Technik-Wissen',
  thema: 'kurs-it',
  module: [
    { id: 'it.m1', titel: 'Grundlagen', emoji: '🧩', text: 'Hardware, Betriebssystem, Dateien' },
    { id: 'it.m2', titel: 'Netzwerk', emoji: '🌐', text: 'IP, Router, WLAN und warum nichts geht' },
    { id: 'it.m3', titel: 'Rechner bauen', emoji: '🔧', text: 'Bauteile, die zueinander passen' },
    { id: 'it.m4', titel: 'Programmieren', emoji: '🤖', text: 'Abläufe, Schleifen, Bedingungen' },
    { id: 'it.m5', titel: 'Code lesen', emoji: '🐛', text: 'Fehler finden, bevor sie jemand meldet' },
    { id: 'it.m6', titel: 'Daten', emoji: '💾', text: 'Formate, Speichern, Backup' },
    { id: 'it.m7', titel: 'Sicherheit', emoji: '🔒', text: 'Passwörter, Updates, Angriffe' },
    { id: 'it.m8', titel: 'Support', emoji: '🎧', text: 'Zuhören, eingrenzen, erklären' },
  ],
  ziele: [
    { id: 'it.hardware', titel: 'Hardware', modul: 'it.m1' },
    { id: 'it.os', titel: 'Betriebssystem', modul: 'it.m1' },
    { id: 'it.dateien', titel: 'Dateien und Formate', modul: 'it.m1' },
    { id: 'it.ip', titel: 'IP-Adressen', modul: 'it.m2' },
    { id: 'it.wlan', titel: 'WLAN', modul: 'it.m2' },
    { id: 'it.router', titel: 'Router und DNS', modul: 'it.m2' },
    { id: 'it.bauteile', titel: 'Bauteile', modul: 'it.m3' },
    { id: 'it.kompatibel', titel: 'Was zusammenpasst', modul: 'it.m3' },
    { id: 'it.logik', titel: 'Abläufe und Bedingungen', modul: 'it.m4' },
    { id: 'it.schleifen', titel: 'Schleifen und Funktionen', modul: 'it.m4' },
    { id: 'it.lesen', titel: 'Code lesen', modul: 'it.m5' },
    { id: 'it.debuggen', titel: 'Fehler finden', modul: 'it.m5' },
    { id: 'it.speichern', titel: 'Speichern und Formate', modul: 'it.m6' },
    { id: 'it.backup', titel: 'Backup', modul: 'it.m6' },
    { id: 'it.passwoerter', titel: 'Passwörter', modul: 'it.m7' },
    { id: 'it.updates', titel: 'Updates und Rechte', modul: 'it.m7' },
    { id: 'it.phishing', titel: 'Angriffe erkennen', modul: 'it.m7' },
    { id: 'it.support', titel: 'Probleme eingrenzen', modul: 'it.m8' },
    { id: 'it.kommunikation', titel: 'Verständlich erklären', modul: 'it.m8' },
  ],
  spiele: [
    {
      id: 'it.debugger',
      mechanik: 'fehler',
      name: 'Debugger',
      emoji: '🐛',
      kurz: 'Ein Zeichen zu viel, ein Zeichen zu wenig.',
      anleitung: 'Tippe die Stelle im Code an, die nicht stimmt, und wähle die richtige Fassung.',
      tempo: 'genau',
      runden: 3,
      skin: 'code',
      bitte: {
        wer: [
          { name: 'Nils', emoji: '🧑‍💻', rolle: 'Entwickler' },
          { name: 'Rana', emoji: '👩‍💻', rolle: 'Studentin' },
        ],
        saetze: [
          'Mein Skript läuft nicht und ich sehe den Fehler einfach nicht. Schaust du drüber?',
          'Ich übe für die Prüfung – findest du die Fehler schneller als ich?',
        ],
      },
    },
    {
      id: 'it.netz',
      mechanik: 'netz',
      name: 'Netzwerk-Notruf',
      emoji: '🌐',
      kurz: 'Ein Gerät kommt nicht ins Netz.',
      anleitung: 'Sieh dir die Geräte an, vergleiche die Adressen und finde, woran es liegt.',
      tempo: 'denken',
      runden: 3,
      bitte: {
        wer: [{ name: 'Frau Kühn', emoji: '👩‍🏫', rolle: 'Lehrerin' }],
        saetze: ['Der Rechner im Klassenzimmer kommt nicht ins Netz. Hilfst du mir suchen?'],
      },
    },
    {
      id: 'it.roboter',
      mechanik: 'roboter',
      name: 'Roboter programmieren',
      emoji: '🤖',
      kurz: 'Ein Programm, kein Klickweg.',
      anleitung: 'Lege die Befehle in die Liste und starte. Mit Schleife und Funktion geht es kürzer.',
      tempo: 'denken',
      runden: 1,
      lang: true,
      ab: 2,
    },
    {
      id: 'it.bauen',
      mechanik: 'baukasten',
      name: 'Rechner bauen',
      emoji: '🔧',
      kurz: 'Passt das zusammen?',
      anleitung: 'Stell die Teile zusammen – oder finde heraus, welches Teil nicht passt.',
      tempo: 'denken',
      runden: 1,
      lang: true,
      ab: 2,
    },
    {
      id: 'it.support',
      mechanik: 'fall',
      name: 'Support-Fall',
      emoji: '🎧',
      kurz: 'Zuhören, eingrenzen, lösen.',
      anleitung: 'Frag nach, was du wissen musst, und entscheide dann. Raten kostet.',
      tempo: 'kontext',
      runden: 2,
      lang: true,
      ab: 2,
    },
    {
      id: 'it.wissen',
      mechanik: 'wahl',
      name: 'IT-Wissen',
      emoji: '🎯',
      kurz: 'Der richtige Begriff.',
      anleitung: 'Eine Frage, vier Antworten. Nur eine stimmt.',
      tempo: 'schnell',
      runden: 4,
    },
    {
      id: 'it.duell',
      mechanik: 'duell',
      name: 'Stimmt das?',
      emoji: '⚖️',
      kurz: 'Zwei Aussagen, eine stimmt.',
      anleitung: 'Beide klingen technisch. Nur eine ist richtig.',
      tempo: 'schnell',
      runden: 5,
    },
    {
      id: 'it.paare',
      mechanik: 'paare',
      name: 'Fachbegriffe',
      emoji: '🔗',
      kurz: 'Begriff und Bedeutung.',
      anleitung: 'Verbinde jeden Begriff mit seiner Bedeutung: erst links antippen, dann rechts.',
      tempo: 'schnell',
      runden: 5,
      spalten: ['Begriff', 'Bedeutung'],
    },
    {
      id: 'it.sortieren',
      mechanik: 'sortieren',
      name: 'Hardware oder Software?',
      emoji: '🧲',
      kurz: 'Einsortieren, schnell.',
      anleitung: 'Schiebe jeden Begriff in sein Fach.',
      tempo: 'schnell',
      runden: 5,
      faecher: [
        { name: 'Hardware', emoji: '🔩' },
        { name: 'Software', emoji: '💿' },
      ],
    },
  ],
  laden: () => import('./inhalt').then((m) => m.INHALT),
}
